# TODO check location of snmpd_config_file

- name: set tlsAlgorithms
  lineinfile:
      path: "{{snmpd_config_file}}"
      regexp: ^\s*snmp\s+tlsAlgorithms\s+
      line: "snmp tlsAlgorithms {{openssl_cipher_suites}}"
      state: present
  notify:
      - restart snmpd
