# TODO check location of snmpd_config_file

- name: set tlsAlgorithms
  lineinfile:
      path: "{{snmpd_config_file}}"
      regexp: ^\s*snmp\s+tlsAlgorithms\s+
      line: "[snmp] tlsAlgorithms {{openssl_cipher_suites}}"
      state: present
  notify:
      - restart snmpd

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72313 (SV-86937r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38653 (SV-50454r1_rule)
- name: comment public com2sec
  replace:
      path: "{{snmpd_config_file}}"
      regexp: ^(\s*(com2sec|com2sec6|com2secunix)\s+.*public\s*(#.*)?)$
      replace: "#\\1"
  notify:
      - restart snmpd
- name: comment private com2sec
  replace:
      path: "{{snmpd_config_file}}"
      regexp: ^(\s*(com2sec|com2sec6|com2secunix)\s+.*private\s*(#.*)?)$
      replace: "#\\1"
  notify:
      - restart snmpd

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38660 (SV-50461r1_rule)
- name: comment v1/v2c groups
  replace:
      path: "{{snmpd_config_file}}"
      regexp: ^(\s*group\s+\S+\s+(v1|v2c).*)$
      replace: "#\\1"
  notify:
      - restart snmpd

- name: comment rocommunity/rwcommunity lines
  replace:
      path: "{{snmpd_config_file}}"
      regexp: ^(\s*(rocommunity|rwcommunity|rocommunity6|rwcommunity6).*)$
      replace: "#\\1"
  notify:
      - restart snmpd

- name: comment v1/v2c accesses
  replace:
      path: "{{snmpd_config_file}}"
      regexp: ^(\s*access\s+\S+\s+\S+\s+(v1|v2c).*)$
      replace: "#\\1"
  notify:
      - restart snmpd
