- name: blacklist module
  lineinfile:
      path: /etc/modprobe.d/stig-blacklist
      line: "blacklist tipc"
      state: present
      create: yes

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38517 (SV-50318r5_rule)
- name: prevent module installation
  lineinfile:
      path: /etc/modprobe.d/stig-install
      line: "install tipc /bin/true"
      state: present
      create: yes
