# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72217 (SV-86841r1_rule)
- name: set TMOUT
  copy:
    src: files/etc/profile.d/tmout.sh
    dest: /etc/profile.d/tmout.sh
    mode: 0755
    owner: root
    group: root

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38647 (SV-50448r1_rule)
- name: set umask in /etc/profile
  lineinfile:
      path: /etc/profile
      regexp: ^umask\s+
      line: umask 077
      state: present
