- name: install tcp_wrappers
  yum:
      name: tcp_wrappers
      state: latest

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72315
- name: template /etc/hosts.allow
  template:
      src: templates/etc/hosts.allow.j2
      dest: /etc/hosts.allow
      mode: 0644
      owner: root
      group: root

- name: template /etc/hosts.deny
  template:
      src: templates/etc/hosts.deny.j2
      dest: /etc/hosts.deny
      mode: 0644
      owner: root
      group: root
