# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72217 (SV-86841r1_rule)
- name: set TMOUT
  copy:
    src: files/etc/profile.d/tmout.sh
    dest: /etc/profile.d/tmout.sh
    mode: 0755
    owner: root
    group: root
