- name: install packages
  yum:
      state: installed
      name: cronie

- name: set cron.allow properties
  file:
      path: /etc/cron.allow
      owner: root
      group: root
      mode: 0600

- name: set cron.deny properties
  file:
      path: /etc/cron.deny
      owner: root
      group: root
      mode: 0600
      state: file

- name: set crontab properties
  file:
      path: /etc/crontab
      owner: root
      group: root
      mode: 0600
      state: file
