- name: install packages
  yum:
      state: installed
      name: cronie

- name: get cron.allow stat
  stat:
      path: /etc/cron.allow
  register: cron_allow_stat

- name: set cron.allow properties
  file:
      path: /etc/cron.allow
      owner: root
      group: root
      mode: 0600
  when:
      - cron_allow_stat.stat.exists

- name: set cron.deny properties
  file:
      path: /etc/cron.deny
      owner: root
      group: root
      mode: 0600

- name: set crontab properties
  file:
      path: /etc/crontab
      owner: root
      group: root
      mode: 0600
