# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71973 (SV-86597r1_rule)
# V-71975 (SV-86599r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38489 (SV-50290r1_rule)
# V-38670 (SV-50471r2_rule)
# V-38673 (SV-50474r2_rule)
# V-38695 (SV-50496r2_rule)
# V-38696 (SV-50497r2_rule)
# V-38698 (SV-50499r2_rule)
# V-38700 (SV-50501r2_rule)
- name: install aide
  yum:
      state: installed
      name: aide
  notify: aide db init

- name: configure aide daily cron
  template:
      src: etc/cron.daily/aide.j2
      dest: /etc/cron.daily/aide
      mode: 0700
  when:
      - aide_frequency == 'daily'

- name: configure aide weekly cron
  template:
      src: etc/cron.weekly/aide.j2
      dest: /etc/cron.weekly/aide
      mode: 0700
  when:
      - aide_frequency == 'weekly'

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-51391 (SV-65601r1_rule)
- name: check if /var/lib/aide/aide.db.gz exists
  stat:
      path: /var/lib/aide/aide.db.gz
  register: aide_db_stat
  changed_when: aide_db_stat.exists == False
  notify: aide db init

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72069 (SV-86693r2_rule)
# V-72071 (SV-86695r2_rule)
# V-72073 (SV-86697r2_rule)
- name: aide.conf
  template:
      src: etc/aide.conf
      dest: /etc/aide.conf
      mode: 0600
  notify: aide db init
