# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71973, V-71975
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38489, V-38670, V-38673, V-38695, V-38696, V-38698, V-38700
- name: install aide
  yum:
      state: installed
      name: aide
  notify: aide db init

- name: configure aide daily cron
  template:
      src: etc/cron.daily/aide.j2
      dest: /etc/cron.daily/aide
      mode: 0700
  when:
      - aide_frequency == 'daily'

- name: configure aide weekly cron
  template:
      src: etc/cron.weekly/aide.j2
      dest: /etc/cron.weekly/aide
      mode: 0700
  when:
      - aide_frequency == 'weekly'

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-51391
- name: check if /var/lib/aide/aide.db.gz exists
  stat:
      path: /var/lib/aide/aide.db.gz
  register: aide_db_stat
  changed_when: aide_db_stat.exists == False
  notify: aide db init

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72069, V-72071, V-72073
- name: aide.conf
  template:
      src: etc/aide.conf
      dest: /etc/aide.conf
      mode: 0600
  notify: aide db init
