# local_events = yes
# write_logs = yes
# log_file = /var/log/audit/audit.log
# log_group = root
# log_format = RAW
# flush = INCREMENTAL_ASYNC
# freq = 50
# max_log_file = 8
# num_logs = 5
# priority_boost = 4
# disp_qos = lossy
# dispatcher = /sbin/audispd
# name_format = NONE
# ##name = mydomain
# max_log_file_action = ROTATE
# admin_space_left = 50
# admin_space_left_action = SUSPEND
# disk_full_action = SUSPEND
# disk_error_action = SUSPEND
# use_libwrap = yes
# ##tcp_listen_port =
# tcp_listen_queue = 5
# tcp_max_per_addr = 1
# ##tcp_client_ports = 1024-65535
# tcp_client_max_idle = 0
# enable_krb5 = yes
# krb5_principal = auditd
# ##krb5_key_file = /etc/audit/audit.key
# distribute_network = no

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72089 (SV-86713r1_rule)
- name: df /var/log/audit/audit.log | tail -n 1 | awk '{print $2}'
  shell: df /var/log/audit/audit.log | tail -n 1 | awk '{print $2}'
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: auditing_log_partition_size

- name: calculate space_left size; 75% of auditing_log_partition_size
  set_fact:
      auditing_log_partition_75: '{{ ( ( auditing_log_partition_size.stdout|int / 1024 ) * 0.75 )|int }}'

- name: set space_left
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: ^\s*space_left\s*=
      line: "space_left = {{auditing_log_partition_75}}"
      state: present
  notify: restart auditd

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72091 (SV-86715r1_rule)
- name: set space_left_action
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: ^\s*space_left_action\s*=
      line: "space_left_action = email"
      state: present
  notify: restart auditd

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72093 (SV-86717r2_rule)
- name: set action_mail_acct
  lineinfile:
      path: /etc/audit/auditd.conf
      regexp: ^\s*action_mail_acct\s*=
      line: "action_mail_acct = {{auditing_email}}"
      state: present
  notify: restart auditd
