# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72079 (SV-86703r2_rule)
- name: install packages
  yum:
      state: installed
      name: '{{item}}'
  with_items:
      - audit
      - audispd-plugins

# NOTE: service running,enabled is at the bottom so rules can be defined before
# startup

- include_tasks: auditd.yml
- include_tasks: audisp.yml
- include_tasks: rules.yml

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72079 (SV-86703r2_rule)
- name: service running
  systemd:
      name: auditd
      enabled: yes
      state: started
