# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72079 (SV-86703r2_rule)
- name: install packages
  yum:
      state: installed
      name: '{{item}}'
  with_items:
      - audit
      - audispd-plugins

# NOTE: service running,enabled is at the bottom so rules can be defined before
# startup


- name: copy rule files
  copy:
      src: "files/etc/audit/rules.d/{{item}}"
      dest: "/etc/audit/rules.d/{{item}}"
      owner: root
      group: root
      mode: 0600
  loop:
      - 00_delete_rules.rules
      - 01_backlog.rules
      - 02_failure.rules
      - access.rules
      - delete.rules
      - identity.rules
      - logins.rules
      - module-change.rules
      - perm_mod.rules
      - privileged-actions.rules
      - privileged-cron.rules
      - privileged-mount.rules
      - privileged-pam.rules
      - privileged-passwd.rules
      - privileged-postfix.rules
      - privileged-priv_change.rules
      - privileged-ssh.rules
      - zz_enabled.rules
  notify: generate audit rules

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72083 (SV-86707r1_rule)
# V-72085 (SV-86709r1_rule)
# V-72087 (SV-86711r2_rule)
# V-73163 (SV-87815r2_rule)
- name: configure audisp-remote.conf
  template:
      src: templates/etc/audisp/audisp-remote.conf.j2
      dest: /etc/audisp/audisp-remote.conf
      owner: root
      group: root
      mode: 0600
  notify: restart auditd

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72089 (SV-86713r1_rule)
# V-72091 (SV-86715r1_rule)
# V-72093 (SV-86717r2_rule)
- name: df /var/log/audit/audit.log | tail -n 1 | awk '{print $2}'
  shell: df /var/log/audit/audit.log | tail -n 1 | awk '{print $2}'
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: auditing_log_partition_size

- name: calculate space_left size; 75% of auditing_log_partition_size
  set_fact:
      auditing_log_partition_75: '{{ ( ( auditing_log_partition_size.stdout|int / 1024 ) * 0.75 )|int }}'

- name: configure auditd.conf
  template:
      src: templates/etc/audit/auditd.conf.j2
      dest: /etc/audit/auditd.conf
      mode: 0600
  notify: restart auditd

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72095 (SV-86719r5_rule)
- name: df | grep -i '^/' | awk '{print $6}'
  shell: df | grep -i '^/' | awk '{print $6}' || true
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: auditing_local_filesystems

- name: find {{item}} -xdev -type f \( -perm -4000 -o -perm -2000 \) 2>/dev/null
  shell: find {{item}} -xdev -type f \( -perm -4000 -o -perm -2000 \) 2>/dev/null || true
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: auditing_setuid_setgid
  with_items: '{{auditing_local_filesystems.stdout_lines}}'

- set_fact:
    auditing_setuid_setgid_combined: []

- name: combine auditing_setuid_setgid results
  set_fact:
      auditing_setuid_setgid_combined: '{{auditing_setuid_setgid_combined}} + {{item.stdout_lines}}'
  with_items: '{{auditing_setuid_setgid.results}}'

- name: setuid_setgid audit rules
  template:
      src: etc/audit/rules.d/setuid_setgid.rules.j2
      dest: /etc/audit/rules.d/setuid_setgid.rules
      mode: 0600
  notify: generate audit rules

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72079 (SV-86703r2_rule)
- name: service running
  systemd:
      name: auditd
      enabled: yes
      state: started
