- name: verify packages
  rpm_verify_all_dump:
  register: rpm_verify_all_dump

- name: collect modified packages
  command: "rpm -qf {{item.path}}"
  args:
    warn: False
  changed_when: False
  loop: "{{rpm_verify_all_dump.rpm_verify_all}}"
  register: filesystem_file_pkgs

- name: combine pkg & verify
  set_fact:
    filesystem_pkg_V: "{{ filesystem_pkg_V | default([]) + [ { 'package': item.stdout, 'verify': item.item } ] }}"
  when: not item is skipped
  loop: "{{filesystem_file_pkgs.results}}"

- name: collect package query dump
  rpm_query_dump:
      name: "{{item.package}}"
      path: "{{item.verify.path}}"
  loop: "{{filesystem_pkg_V}}"
  register: rpm_query_dump

- name: combine pkg, verify, query
  set_fact:
    filesystem_pkg_V_q: "{{ filesystem_pkg_V_q | default([]) + [ { 'package': item.item.package, 'verify': item.item.verify, 'query': item.rpm_query_dump[0] } ] }}"
  loop: "{{rpm_query_dump.results}}"

- name: collect file stat
  stat:
      checksum_algorithm: "{{rpm_checksum_algorithm}}"
      path: "{{item.verify.path}}"
  loop: "{{filesystem_pkg_V_q}}"
  register: stat

- name: combine pkg, verify, query, stat
  set_fact:
    filesystem_pkg_V_q_s: "{{ filesystem_pkg_V_q_s | default([]) + [ { 'package': item.item.package, 'verify': item.item.verify, 'query': item.item.query, 'stat': item.stat } ] }}"
  loop: "{{stat.results}}"

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71849 (SV-86473r2_rule)
- name: reset file user permissions
  file:
      path: "{{item.verify.path}}"
      mode: "{{item.query.mode_permissions}}"
  loop: "{{filesystem_pkg_V_q_s}}"
  when:
      - item.verify.mode_differs
      - item.stat.mode is more_permissive(item.query.mode_permissions)

- name: reset file owner
  file:
      path: "{{item.verify.path}}"
      owner: "{{item.query.owner}}"
  loop: "{{filesystem_pkg_V_q_s}}"
  when:
      - item.verify.owner_differs
      - item.stat.pw_name != item.query.owner

- name: reset file group
  file:
      path: "{{item.verify.path}}"
      group: "{{item.query.group}}"
  loop: "{{filesystem_pkg_V_q_s}}"
  when:
      - item.verify.group_differs
      - item.stat.gr_name != item.query.group

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71855 (SV-86479r2_rule)

# TODO add check for package in repo. if it doesn't exist this errors
# - name: reinstall for checksum mismatch
#   command: "yum reinstall -y {{item.package}}"
#   args:
#       warn: False
#   loop: "{{filesystem_pkg_V_q_s}}"
#   when:
#       - item.verify.digest_differs
#       - not item.verify.is_config
#       - not item.verify.is_ghost
