fs_file_contexts: "/etc/selinux/{{selinux_policy}}/contexts/files/file_contexts"

fs_world_writable_users:
    - root
    - sys
    - bin

fs_world_writable_groups:
    - root
    - sys
    - bin

fs_find_fstypes: "\\( -fstype {{fs_types_local|join(' -o -fstype ')}} \\)"

fs_lib_dirs:
    - /lib
    - /lib64
    - /usr/lib
    - /usr/lib64
    - /usr/local/lib
    - /usr/local/lib64
