- name: test firewall_cmd_zone module
  hosts: stig-rhel7
  tasks:

    - name: get firewall version
      firewall_cmd:
          state: get_version
      register: firewalld_version


    ### Positives

    - name: create zone; permanent is implied
      firewall_cmd_zone:
        name: test
        state: present

    - name: reload permanent configuration into runtime (necessary after zone creation)
      firewall_cmd:
        state: reload

    - name: set zone description; permanent is implied
      firewall_cmd_zone:
        name: test
        description: Long description of a zone for testing
      when: firewalld_version['firewalld']['version'] is version('0.4.3.2', '>')

    - name: set zone short description; permanent is implied
      firewall_cmd_zone:
        name: test
        short: Zone for testing
      when: firewalld_version['firewalld']['version'] is version('0.4.3.2', '>')

    - name: set zone target; permanent is implied
      firewall_cmd_zone:
        name: test
        target: ACCEPT

    # - name: add an interface to a zone
    #   firewall_cmd_zone:
    #     name: test
    #     interface: eth0
    #     state: present

    - name: set zone icmp block inversion
      firewall_cmd_zone:
        name: test
        icmp_block_inversion: true

    - name: add a source to a zone
      firewall_cmd_zone:
        name: test
        source: 192.168.0.0/16
        state: present

    - name: add a service to a zone
      firewall_cmd_zone:
        name: test
        service: ssh
        state: present

    - name: add a port to a zone
      firewall_cmd_zone:
        name: test
        port: 22/tcp
        state: present

    - name: add a protocol to a zone
      firewall_cmd_zone:
        name: test
        protocol: gre
        state: present

    - name: set zone masquerading
      firewall_cmd_zone:
        name: test
        masquerade: true

    - name: add a forward-port to a zone
      firewall_cmd_zone:
        name: test
        forward_port: port=3389:proto=tcp:toport=3389:toaddr=192.168.42.42
        state: present

    - name: add a source-port to a zone
      firewall_cmd_zone:
        name: test
        source_port: 68/udp
        state: present

    - name: add an icmp-block to a zone
      firewall_cmd_zone:
        name: test
        icmp_block: echo-request
        state: present

    - name: add a rich rule to a zone
      firewall_cmd_zone:
        name: test
        rich_rule: rule protocol value="ah" accept
        state: present


    ### Refresh

    - name: refresh firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    # - debug:
    #     msg: '{{firewalld_config}}'


    ### Positive Tests

    - fail:
        msg: "zone is created"
      when:
          - firewalld_config['firewalld']['permanent_zones'] is not_containing('test')

    - fail:
        msg: "description is set"
      when:
          - firewalld_version['firewalld']['version'] is version('0.4.3.2', '>')
          - firewalld_config['firewalld']['permanent_zones']['test']['description'] != 'Long description of a zone for testing'

    - fail:
        msg: "short is set"
      when:
          - firewalld_version['firewalld']['version'] is version('0.4.3.2', '>')
          - firewalld_config['firewalld']['permanent_zones']['test']['short'] != 'Zone for testing'

    - fail:
        msg: "icmp_block_inversion true"
      when:
          - not firewalld_config['firewalld']['permanent_zones']['test']['icmp_block_inversion']

    - fail:
        msg: "source added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['sources'] is not_containing('192.168.0.0/16')

    - fail:
        msg: "service added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['services'] is not_containing('ssh')

    - fail:
        msg: "port added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['ports'] is not_containing('22/tcp')

    - fail:
        msg: "protocol added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['protocols'] is not_containing('gre')

    - fail:
        msg: "masquerade true"
      when:
          - not firewalld_config['firewalld']['permanent_zones']['test']['masquerade']

    - fail:
        msg: "forward-port added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['forward_ports'] is not_containing('port=3389:proto=tcp:toport=3389:toaddr=192.168.42.42')

    - fail:
        msg: "source-port added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['source_ports'] is not_containing('68/udp')

    - fail:
        msg: "icmp block added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['icmp_blocks'] is not_containing('echo-request')

    - fail:
        msg: "rich rule added"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['rich_rules'] is not_containing('rule protocol value="ah" accept')

    ### Negatives

    - name: set zone target; permanent is implied
      firewall_cmd_zone:
        name: test
        target: DROP

    # - name: remove an interface from a zone
    #   firewall_cmd_zone:
    #     name: test
    #     interface: eth0
    #     state: absent

    - name: reset zone icmp block inversion
      firewall_cmd_zone:
        name: test
        icmp_block_inversion: false

    - name: remove a source from a zone
      firewall_cmd_zone:
        name: test
        source: 192.168.0.0/16
        state: absent

    - name: remove a service from a zone
      firewall_cmd_zone:
        name: test
        service: ssh
        state: absent

    - name: remove a port from a zone
      firewall_cmd_zone:
        name: test
        port: 22/tcp
        state: absent

    - name: remove a protocol from a zone
      firewall_cmd_zone:
        name: test
        protocol: gre
        state: absent

    - name: reset zone masquerading
      firewall_cmd_zone:
        name: test
        masquerade: false

    - name: remove a forward-port from a zone
      firewall_cmd_zone:
        name: test
        forward_port: port=3389:proto=tcp:toport=3389:toaddr=192.168.42.42
        state: absent

    - name: remove a source-port from a zone
      firewall_cmd_zone:
        name: test
        source_port: 68/udp
        state: absent

    - name: remove an icmp-block from a zone
      firewall_cmd_zone:
        name: test
        icmp_block: echo-request
        state: absent

    - name: remove a rich rule from a zone
      firewall_cmd_zone:
        name: test
        rich_rule: rule protocol value="ah" accept
        state: absent


    ### Refresh

    - name: refresh firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    # - debug:
    #     msg: '{{firewalld_config}}'


    ### Negative Tests

    - fail:
        msg: "target is DROP"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['target'] != 'DROP'

    # TODO interface removal test

    - fail:
        msg: "icmp_block_inversion false"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['icmp_block_inversion']

    - fail:
        msg: "source removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['sources'] is containing('192.168.0.0/16')

    - fail:
        msg: "service removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['services'] is containing('ssh')

    - fail:
        msg: "port removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['ports'] is containing('22/tcp')

    - fail:
        msg: "protocol removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['protocols'] is containing('gre')

    - fail:
        msg: "masquerade false"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['masquerade']

    - fail:
        msg: "forward-port removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['forward_ports'] is containing('port=3389:proto=tcp:toport=3389:toaddr=192.168.42.42')

    - fail:
        msg: "source-port removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['source_ports'] is containing('68/udp')

    - fail:
        msg: "icmp block removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['icmp_blocks'] is containing('echo-request')

    - fail:
        msg: "rich rule removed"
      when:
          - firewalld_config['firewalld']['permanent_zones']['test']['rich_rules'] is containing('rule protocol value="ah" accept')

    ### Delete

    - name: delete zone; permanent is implied
      firewall_cmd_zone:
        name: test
        state: absent

    - name: reload permanent configuration into runtime (necessary after zone deletion)
      firewall_cmd:
        state: reload

    ### Refresh

    - name: refresh firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    # - debug:
    #     msg: '{{firewalld_config}}'

    ### Delete Test

    - fail:
        msg: "deleted zone"
      when:
          - firewalld_config['firewalld']['permanent_zones'] is containing('test')
