- name: test firewall_cmd_direct module
  hosts: stig-rhel7
  tasks:

    - name: create zone; permanent is implied
      firewall_cmd_zone:
        name: test
        state: present

    - name: reload permanent configuration into runtime (necessary after zone creation)
      firewall_cmd:
        state: reload

    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config

    - name: set zone description; permanent is implied
      firewall_cmd_zone:
        name: test
        description: Long description of a zone for testing
      when: firewalld_config['firewalld']['version'] is version('0.4.3.2', '>')

    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
      when:
          - firewalld_config['firewalld']['version'] is version('0.4.3.2', '>')
    # - debug:
    #     msg: '{{firewalld_config}}'
    - fail:
        msg: "description"
      when:
          - firewalld_config['firewalld']['version'] is version('0.4.3.2', '>')
          - firewalld_config['firewalld']['permanent_zones']['description'] != 'Long description of a zone for testing'

    - name: set zone short description; permanent is implied
      firewall_cmd_zone:
        name: test
        short: Zone for testing
      when: firewalld_config['firewalld']['version'] is version('0.4.3.2', '>')

    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
      when:
          - firewalld_config['firewalld']['version'] is version('0.4.3.2', '>')
    # - debug:
    #     msg: '{{firewalld_config}}'
    - fail:
        msg: "short"
      when:
          - firewalld_config['firewalld']['version'] is version('0.4.3.2', '>')
          - firewalld_config['firewalld']['permanent_zones']['short'] != 'Zone for testing'

    - name: set zone target; permanent is implied
      firewall_cmd_zone:
        name: test
        target: ACCEPT

    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'

    # - name: add an interface to a zone
    #   firewall_cmd_zone:
    #     name: test
    #     interface: eth0
    #     state: present
    # - name: get firewall configuration
    #   firewall_cmd:
    #       state: get
    #   register: firewalld_config
    # - debug:
    #     msg: '{{firewalld_config}}'
    # - name: remove an interface from a zone
    #   firewall_cmd_zone:
    #     name: test
    #     interface: eth0
    #     state: absent

    - name: set zone icmp block inversion
      firewall_cmd_zone:
        name: test
        icmp_block_inversion: true
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: reset zone icmp block inversion
      firewall_cmd_zone:
        name: test
        icmp_block_inversion: false

    - name: add a source to a zone
      firewall_cmd_zone:
        name: test
        source: 192.168.0.0/16
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove a source from a zone
      firewall_cmd_zone:
        name: test
        source: 192.168.0.0/16
        state: absent

    - name: add a service to a zone
      firewall_cmd_zone:
        name: test
        service: ssh
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove a service from a zone
      firewall_cmd_zone:
        name: test
        service: ssh
        state: absent

    - name: add a port to a zone
      firewall_cmd_zone:
        name: test
        port: 22/tcp
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove a port from a zone
      firewall_cmd_zone:
        name: test
        port: 22/tcp
        state: absent

    - name: add a protocol to a zone
      firewall_cmd_zone:
        name: test
        protocol: gre
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove a protocol from a zone
      firewall_cmd_zone:
        name: test
        protocol: gre
        state: absent

    - name: set zone masquerading
      firewall_cmd_zone:
        name: test
        masquerade: true
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: reset zone masquerading
      firewall_cmd_zone:
        name: test
        masquerade: false

    - name: add a forward-port to a zone
      firewall_cmd_zone:
        name: test
        forward_port: port=3389:proto=tcp:toport=3389:toaddr=192.168.42.42
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove a forward-port from a zone
      firewall_cmd_zone:
        name: test
        forward_port: port=3389:proto=tcp:toport=3389:toaddr=192.168.42.42
        state: absent

    - name: add a source-port to a zone
      firewall_cmd_zone:
        name: test
        source_port: 68/udp
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove a source-port from a zone
      firewall_cmd_zone:
        name: test
        source_port: 68/udp
        state: absent

    - name: add an icmp-block to a zone
      firewall_cmd_zone:
        name: test
        icmp_block: echo-request
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove an icmp-block from a zone
      firewall_cmd_zone:
        name: test
        icmp_block: echo-request
        state: absent

    - name: add a rich rule to a zone
      firewall_cmd_zone:
        name: test
        rich_rule: rule protocol value="ah" accept
        state: present
    - name: get firewall configuration
      firewall_cmd:
          state: get
      register: firewalld_config
    - debug:
        msg: '{{firewalld_config}}'
    - name: remove a rich rule from a zone
      firewall_cmd_zone:
        name: test
        rich_rule: rule protocol value="ah" accept
        state: absent

    - name: delete zone; permanent is implied
      firewall_cmd_zone:
        name: test
        state: absent

    - name: reload permanent configuration into runtime (necessary after zone deletion)
      firewall_cmd:
        state: reload
