aide_conf_sha1: a0c76a14d918a55fe059ff9592e708fe62b75aca
aide_frequency: daily
aide_notification_email: root

auditing_email: root
auditing_aggregation_server:
auditing_network_failure_action: syslog
auditing_disk_full_action: syslog
auditing_log_file_default: /var/log/audit/audit.log

dhcp_required: True

filesystems_types_local:
    - btrfs
    - ext2
    - ext3
    - ext4
    - reiserfs
    - xfs
    - squashfs
    - romfs
    - ramfs
    - fuse
filesystems_types_network:
    - cifs
    - nfs
    - nfs4
    - smbfs
filesystems_types_removable:
    - iso9660
    - msdos
    - vfat
    - udf
    - ubifs         # flash filesystem
    - jffs2         # flash filesystem
filesystems_types_pseudo:
    - sysfs
    - rootfs
    - proc
    - cgroup
    - cpuset
    - devtmpfs
    - debugfs
    - securityfs
    - configfs
    - devpts
    - selinuxfs
    - mqueue
    - hugetlbfs
    - systemd-1

# TODO ipset definitions
# TODO icmptype definitions
# TODO service definitions
# TODO helper definitions
# TODO direct chain definitions
# TODO passthrough definitions
# TODO lockdown
# TODO lockdown whitelist defintion
firewalld_zones:
    block:
        target: '%%REJECT%%'
        icmp_block_inversion: no
        sources:
        services:
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    dmz:
        target: default
        icmp_block_inversion: no
        sources:
        services: ssh
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    drop:
        target: DROP
        icmp_block_inversion: no
        sources:
        services:
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    external:
        target: default
        icmp_block_inversion: no
        sources:
        services: ssh
        ports:
        protocols:
        masquerade: yes
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    home:
        target: default
        icmp_block_inversion: no
        sources:
        services: dhcpv6-client mdns samba-client ssh
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    internal:
        target: default
        icmp_block_inversion: no
        sources:
        services: dhcpv6-client mdns samba-client ssh
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    public:
        target: default
        icmp_block_inversion: no
        sources:
        services: dhcpv6-client ssh
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    trusted:
        target: ACCEPT
        icmp_block_inversion: no
        sources:
        services:
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
    work:
        target: default
        icmp_block_inversion: no
        sources:
        services: dhcpv6-client ssh
        ports:
        protocols:
        masquerade: no
        forward_ports:
        source_ports:
        icmp_blocks:
        rich_rules:
firewalld_default_zone: drop
firewalld_interface_zones:
firewalld_direct_rules:
    - ipv4 filter IN_drop_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100 -j ACCEPT

nfs_required: False

ntp_server: localhost

samba_required: False

snmpd_required: True

tftpd_required: False

vsftpd_required: True
