# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72051 (SV-86675r1_rule)
- name: cron logging
  lineinfile:
      path: "{{rsyslogd_config_file}}"
      regexp: ^cron\..*/var/log/cron.log
      line: cron.* /var/log/cron.log
      insertbefore: ^\*\.\*
      state: present

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72209 (SV-86833r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38520 (SV-50321r1_rule), V-38521 (SV-50322r1_rule)
- name: comment ~ line
  replace:
      path: "{{rsyslogd_config_file}}"
      regexp: ^(\*\.\*\s+~\s*(#.*)?)$
      replace: '#\1'

- name: log aggregation target
  lineinfile:
      path: "{{rsyslogd_config_file}}"
      regexp: ^\*\.\*\s+@@.*
      line: "*.* @{{log_aggregation_server}}"
      insertafter: EOF
      state: present
  when: log_aggregation_protocol == 'udp'

- name: log aggregation target
  lineinfile:
      path: "{{rsyslogd_config_file}}"
      regexp: ^\*\.\*\s+@@.*
      line: "*.* @@{{log_aggregation_server}}"
      insertafter: EOF
      state: present
  when: log_aggregation_protocol == 'tcp'

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72211 (SV-86835r1_rule)
# TODO comment "ModLoad imtcp" unless this is a log aggregation server
