# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72275 (SV-86899r2_rule)
- name: remove default pam_lastlog lines
  replace:
      path: /etc/pam.d/postlogin
      regexp: ^session\s+\[default=1\]\s+pam_lastlog.so.*\n
      replace: ''

- name: remove default pam_lastlog lines
  replace:
      path: /etc/pam.d/postlogin
      regexp: ^session\s+optional\s+pam_lastlog.so.*\n
      replace: ''

- name: set pam_lastlog.so
  pamd:
      name: postlogin
      new_type: session
      new_control: required
      new_module_path: pam_lastlog.so
      module_arguments:
          - showfailed
      state: after
      type: session
      control: '[success=1 default=ignore]'
      module_path: pam_succeed_if.so
  notify: noeol postlogin
