# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38437 (SV-50237r1_rule)
- name: disable, stop autofs service
  service:
      name: autofs
      enabled: no
      state: stopped
