- name: install packages
  yum:
      state: installed
      name: usbguard

- name: usbguard config
  template:
      src: "templates{{usbguard_daemon_config_file}}.j2"
      dest: "{{usbguard_daemon_config_file}}"
      owner: root
      group: root
      mode: 0600

- name: usbguard rules
  copy:
      src: "files{{usbguard_rules_config_file}}"
      dest: "{{usbguard_rules_config_file}}"
      owner: root
      group: root
      mode: 0600

- name: usbguard logrotate
  copy:
      src: files/etc/logrotate.d/usbguard
      dest: /etc/logrotate.d/usbguard
      owner: root
      group: root
      mode: 0600

- name: usbguard service
  service:
      name: usbguard
      enabled: yes
      state: started
