- name: read /etc/syconfig/authconfig
  command: cat /etc/syconfig/authconfig
  register: authconfig

- name: include sssd tasks
  include_tasks: ldap.yml
  when:
    - authconfig.stdout is in('USELDAP=yes')
    - authconfig.stdout is in('USELDAPAUTH=yes')
    - authconfig.stdout is in('FORCELEGACY=no')
