- name: blacklist module
  lineinfile:
      path: /etc/modprobe.d/stig-blacklist
      line: "blacklist {{item}}"
      state: present
      create: yes
  loop:
      - bluetooth
      - net-pf-31

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38682 (SV-50483r5_rule)
- name: prevent module installation
  lineinfile:
      path: /etc/modprobe.d/stig-install
      line: "install {{item}} /bin/true"
      state: present
      create: yes
  loop:
      - bluetooth
      - net-pf-31

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38691 (SV-50492r2_rule)
- name: disable, stop services
  service:
      name: bluetooth
      enabled: no
      state: stopped
