### Constants; probably shouldn't be overriden


### Variables; could be overriden depending on environment

auditing_email: root

# Compliance requires syslog, single, or halt
auditing_disk_full_action: syslog

# Compliance requires syslog, single, or halt
auditing_network_failure_action: syslog

auditing_log_file_default: /var/log/audit/audit.log
