# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38627 (SV-50428r2_rule)
- name: remove openldap-servers
  yum:
      name: openldap-servers
      state: absent
  when: not is_ldap_server
