- name: Apply anti-DDoS sysctl settings
  sysctl:
      name: "{{item.name}}"
      value: "{{item.value}}"
      state: present
  notify: reload sysctl
  with_items:
      - { name: 'kernel.printk', value: '4 4 1 7' }
      - { name: 'kernel.panic', value: '10' }
      - { name: 'kernel.sysrq', value: '0' }
      - { name: 'kernel.shmmax', value: '4294967296' }
      - { name: 'kernel.shmall', value: '4194304' }
      - { name: 'kernel.core_uses_pid', value: '1' }
      - { name: 'kernel.msgmnb', value: '65536' }
      - { name: 'kernel.msgmax', value: '65536' }
      - { name: 'vm.swappiness', value: '20' }
      - { name: 'vm.dirty_ratio', value: '80' }
      - { name: 'vm.dirty_background_ratio', value: '5' }
      - { name: 'fs.file-max', value: '2097152' }
      - { name: 'net.core.netdev_max_backlog', value: '262144' }
      - { name: 'net.core.rmem_default', value: '31457280' }
      - { name: 'net.core.rmem_max', value: '67108864' }
      - { name: 'net.core.wmem_default', value: '31457280' }
      - { name: 'net.core.wmem_max', value: '67108864' }
      - { name: 'net.core.somaxconn', value: '65535' }
      - { name: 'net.core.optmem_max', value: '25165824' }
      - { name: 'net.ipv4.neigh.default.gc_thresh1', value: '4096' }
      - { name: 'net.ipv4.neigh.default.gc_thresh2', value: '8192' }
      - { name: 'net.ipv4.neigh.default.gc_thresh3', value: '16384' }
      - { name: 'net.ipv4.neigh.default.gc_interval', value: '5' }
      - { name: 'net.ipv4.neigh.default.gc_stale_time', value: '120' }
      - { name: 'net.netfilter.nf_conntrack_max', value: '10000000' }
      - { name: 'net.netfilter.nf_conntrack_tcp_loose', value: '0' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_established', value: '1800' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_close', value: '10' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_close_wait', value: '10' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_fin_wait', value: '20' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_last_ack', value: '20' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_syn_recv', value: '20' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_syn_sent', value: '20' }
      - { name: 'net.netfilter.nf_conntrack_tcp_timeout_time_wait', value: '10' }
      - { name: 'net.ipv4.tcp_slow_start_after_idle', value: '0' }
      - { name: 'net.ipv4.ip_local_port_range', value: '1024 65000' }
      - { name: 'net.ipv4.ip_no_pmtu_disc', value: '1' }
      - { name: 'net.ipv4.route.flush', value: '1' }
      - { name: 'net.ipv4.route.max_size', value: '8048576' }
      - { name: 'net.ipv4.tcp_congestion_control', value: 'htcp' }
      - { name: 'net.ipv4.tcp_mem', value: '65536 131072 262144' }
      - { name: 'net.ipv4.udp_mem', value: '65536 131072 262144' }
      - { name: 'net.ipv4.tcp_rmem', value: '4096 87380 33554432' }
      - { name: 'net.ipv4.udp_rmem_min', value: '16384' }
      - { name: 'net.ipv4.tcp_wmem', value: '4096 87380 33554432' }
      - { name: 'net.ipv4.udp_wmem_min', value: '16384' }
      - { name: 'net.ipv4.tcp_max_tw_buckets', value: '1440000' }
      - { name: 'net.ipv4.tcp_tw_recycle', value: '0' }
      - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
      - { name: 'net.ipv4.tcp_max_orphans', value: '400000' }
      - { name: 'net.ipv4.tcp_window_scaling', value: '1' }
      - { name: 'net.ipv4.tcp_rfc1337', value: '1' }
      - { name: 'net.ipv4.tcp_synack_retries', value: '1' }
      - { name: 'net.ipv4.tcp_syn_retries', value: '2' }
      - { name: 'net.ipv4.tcp_max_syn_backlog', value: '16384' }
      - { name: 'net.ipv4.tcp_timestamps', value: '1' }
      - { name: 'net.ipv4.tcp_sack', value: '1' }
      - { name: 'net.ipv4.tcp_fack', value: '1' }
      - { name: 'net.ipv4.tcp_ecn', value: '2' }
      - { name: 'net.ipv4.tcp_fin_timeout', value: '10' }
      - { name: 'net.ipv4.tcp_keepalive_time', value: '600' }
      - { name: 'net.ipv4.tcp_keepalive_intvl', value: '60' }
      - { name: 'net.ipv4.tcp_keepalive_probes', value: '10' }
      - { name: 'net.ipv4.tcp_no_metrics_save', value: '1' }

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-77825 (SV-92521r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38596 (SV-50397r2_rule)
- name: Apply kernel.randomize_va_space
  sysctl:
      name: kernel.randomize_va_space
      value: 2
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38597 (SV-50398r2_rule)
- name: Apply kernel.exec-shield
  sysctl:
      name: kernel.exec-shield
      value: 1
      state: present
  notify: reload sysctl
  when: ansible_distribution_major_version == '6'

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72283 (SV-86907r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38523 (SV-50324r2_rule)
- name: Apply net.ipv4.conf.all.accept_source_route
  sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72285 (SV-86909r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38529 (SV-50330r2_rule)
- name: Apply net.ipv4.conf.default.accept_source_route
  sysctl:
      name: net.ipv4.conf.default.accept_source_route
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72287 (SV-86911r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38535 (SV-50336r2_rule)
- name: Apply net.ipv4.icmp_echo_ignore_broadcasts
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72289 (SV-86913r2_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38533 (SV-50334r3_rule)
- name: Apply net.ipv4.conf.default.accept_redirects
  sysctl:
      name: net.ipv4.conf.default.accept_redirects
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72291 (SV-86915r3_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38600 (SV-50401r2_rule)
- name: Apply net.ipv4.conf.default.send_redirects
  sysctl:
      name: net.ipv4.conf.default.send_redirects
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72293 (SV-86917r2_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38601 (SV-50402r2_rule)
- name: Apply net.ipv4.conf.all.send_redirects
  sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72295 (SV-86919r1_rule)
- name: Get interface promisc mode
  command: "ip link show {{item}}"
  loop: "{{network_interfaces.keys()}}"
  changed_when: False
  register: network_interface_state

- name: set promisc off
  command: "ip link set {{item}} promisc off"
  loop: "{{network_interface_state.results}}"
  when: "'promisc' in item.stdout"

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72309 (SV-86933r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38511 (SV-50312r2_rule)
- name: Apply net.ipv4.ip_forward
  sysctl:
      name: net.ipv4.ip_forward
      value: 0
      state: present
  when: not is_routing
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72319 (SV-86943r1_rule)
- name: Apply net.ipv6.conf.all.accept_source_route
  sysctl:
      name: net.ipv6.conf.all.accept_source_route
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-73175 (SV-87827r3_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38524 (SV-50325r2_rule)
- name: Apply net.ipv4.conf.all.accept_redirects
  sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38526 (SV-50327r2_rule)
- name: Apply net.ipv4.conf.all.secure_redirects
  sysctl:
      name: net.ipv4.conf.all.secure_redirects
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38528 (SV-50329r2_rule)
- name: Apply net.ipv4.conf.all.log_martians
  sysctl:
      name: net.ipv4.conf.all.log_martians
      value: 1
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38532 (SV-50333r2_rule)
- name: Apply net.ipv4.conf.default.secure_redirects
  sysctl:
      name: net.ipv4.conf.default.secure_redirects
      value: 0
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38537 (SV-50338r2_rule)
- name: Apply net.ipv4.icmp_ignore_bogus_error_responses
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38539 (SV-50340r2_rule)
- name: Apply net.ipv4.tcp_syncookies
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38542 (SV-50343r2_rule)
- name: Apply net.ipv4.conf.all.rp_filter
  sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: 1
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38544 (SV-50345r2_rule)
- name: Apply net.ipv4.conf.default.rp_filter
  sysctl:
      name: net.ipv4.conf.default.rp_filter
      value: 1
      state: present
  notify: reload sysctl

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38548 (SV-50349r3_rule)
- name: Apply net.ipv6.conf.default.accept_redirects
  sysctl:
      name: net.ipv6.conf.default.accept_redirects
      value: 0
      state: present
  notify: reload sysctl
