- name: generate audit rules
  command: augenrules
  register: auditing_augenrules
  changed_when: "'No change' not in auditing_augenrules.stdout"
  notify: reload audit rules

- name: reload audit rules
  command: auditctl -R /etc/audit/audit.rules
  register: auditing_reload
  changed_when: "'No change' not in auditing_reload.stdout"
  notify: restart auditd

- name: restart auditd
  command: systemctl restart auditd
  register: auditd_restart
  changed_when: "'Operation refused' in auditd_restart.stderr"
  failed_when: False
  notify: needs restart
