- name: generate audit rules
  command: augenrules
  register: auditing_augenrules
  changed_when: "'No change' not in auditing_augenrules.stdout"
  notify: reload audit rules

- name: reload audit rules
  command: auditctl -R /etc/audit/audit.rules
  register: auditing_reload
  changed_when: "'No change' not in auditing_reload.stdout"
  notify: restart auditd

- name: restart auditd
  systemd:
      name: auditd
      state: restarted
  # if everything has been configured, we can't restart, but we want to show
  ignore_errors: yes
