---
dependencies:
  # - { role: harden_aide }
  # - { role: harden_antivirus }
  # - { role: harden_auditing }
  # - { role: harden_backup }
  # - { role: harden_cron }
  # - { role: harden_filesystems }
  - { role: harden_firewall }
  # - { role: harden_gdm }
  # - { role: harden_grub }
  # - { role: harden_home_dirs }
  # - { role: harden_init }
  # - { role: harden_ips }
  # - { role: harden_kernel }
  # - { role: harden_ldap }
  # - { role: harden_logins }
  # - { role: harden_modules }
  # - { role: harden_network }
  # - { role: harden_nfs }
  # - { role: harden_ntpd }
  # - { role: harden_packages }
  # - { role: harden_pam }
  # - { role: harden_passwords }
  # - { role: harden_postfix }
  # - { role: harden_prohibited_files }
  # - { role: harden_rsyslogd }
  # - { role: harden_samba }
  # - { role: harden_selinux }
  # - { role: harden_services }
  # - { role: harden_snmpd }
  # - { role: harden_sshd }
  # - { role: harden_sssd }
  # - { role: harden_sudo }
  # - { role: harden_systemd }
  # - { role: harden_system_dirs }
  # - { role: harden_tftpd }
  # - { role: harden_umask }
  # - { role: harden_vsftpd }
  # - { role: harden_xorg }
  # - { role: harden_yum }
