- name: nfs-server status
  command: systemctl status nfs-server
  failed_when: False
  changed_when: False
  register: nfs_server_status

- name: include harden
  include_tasks: harden.yml
  when: nfs_server_status is successful
