# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71967 (SV-86591r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38591 (SV-50392r1_rule)
- name: remove package
  yum:
      name: rsh-server
      state: absent

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38594 (SV-50395r2_rule)
- name: disable, stop service
  service:
      name: rsh
      enabled: no
      state: stopped
