- name: auditing generate rules
  command: augenrules
  register: auditing_augenrules
  changed_when: "'No change' not in auditing_augenrules.stdout"
  notify: auditing reload

- name: auditing reload
  command: auditctl -R /etc/audit/audit.rules
  register: auditing_reload
  changed_when: "'No change' not in auditing_reload.stdout"
  notify: auditing restart

- name: auditing restart
  systemd:
      name: auditd
      state: restarted
  # if everything has been configured, we can't restart, but we want to show
  ignore_errors: yes
