# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38586 (SV-50387r1_rule)
- name: set SINGLE
  lineinfile:
      path: /etc/sysconfig/init
      regexp: ^\s*SINGLE\s*=
      line: SINGLE=/sbin/sulogin
      state: present

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38588 (SV-50389r1_rule)
- name: set PROMPT
  lineinfile:
      path: /etc/sysconfig/init
      regexp: ^\s*PROMPT\s*=
      line: PROMPT=no
      state: present

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38668 (SV-50469r3_rule)
- name: set exec
  lineinfile:
      path: /etc/init/control-alt-delete.override
      regexp: ^\s*exec\s*=
      line: exec /usr/bin/logger -p security.info "Ctrl-Alt-Delete pressed"
      state: present

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38674 (SV-50475r1_rule)
- name: set default runlevel
  lineinfile:
      path: /etc/inittab
      regexp: initdefault
      line: id:3:initdefault:
      state: present
  when:
      - not is_X_required
