# Vuln ID: V-38666
# Severity: medium
# Group Title: SRG-OS-000270
# Rule ID: SV-50467r3_rule
# STIG ID: RHEL-06-000284
# Rule Title: The system must use and update a virus scan program.
# Discussion: Virus scanning software can be used to protect a system from penetration by computer viruses and to limit their spread through intermediate systems.
#
# The virus scanning software should be configured to perform scans dynamically on accessed files. If this capability is not available, the system must be configured to scan, at a minimum, all altered files on the system on a daily basis.
#
# If the system processes inbound SMTP mail, the virus scanner must be configured to scan all received mail.
#
# IA Controls:
# Check Content: Check for the existence of a virus scan tool to be executed daily in the cron file:
#
# # crontab -l
#
# With the assistance of the system administrator, ensure the virus definition signature files are not older than seven (7) days.
#
# If a virus scanner is not being run daily or the virus definitions are older than seven (7) days, this is a finding.
#
# Fix Text: Install a virus scan tool.
#
# Ensure the virus signature definition files are no older than seven (7) days.
#
# Ensure the command line virus scan tool is run on a regular basis using a utility, such as cron.
#
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001668
# The organization employs malicious code protection mechanisms at workstations, servers, or mobile computing devices on the network to detect and eradicate malicious code transported by electronic mail, electronic mail attachments, web accesses, removable media, or other common means or inserted through the exploitation of information system vulnerabilities.
# NIST SP 800-53 :: SI-3 a
# NIST SP 800-53A :: SI-3.1 (ii)
#
#
- name: check stig_rhel6_v1r18 v_38666
  set_fact: stig_rhel6_v1r18_results['v_38666'] = 'fail'
  when: '"v_38666" in stig_rhel6_v1r18_check_findings'
