# Vuln ID: V-38486
# Severity: medium
# Group Title: SRG-OS-000100
# Rule ID: SV-50287r1_rule
# STIG ID: RHEL-06-000505
# Rule Title: The operating system must conduct backups of system-level information contained in the information system per organization defined frequency to conduct backups that are consistent with recovery time and recovery point objectives.
# Discussion: Operating system backup is a critical step in maintaining data assurance and availability. System-level information includes system-state information, operating system and application software, and licenses. Backups must be consistent with organizational recovery time and recovery point objectives.
# IA Controls:
# Check Content: Ask an administrator if a process exists to back up OS data from the system, including configuration data.
#
# If such a process does not exist, this is a finding.
# Fix Text: Procedures to back up OS data from the system must be established and executed. The Red Hat operating system provides utilities for automating such a process.  Commercial and open-source products are also available.
#
# Implement a process whereby OS data is backed up from the system in accordance with local policies.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000537
# The organization conducts backups of system-level information contained in the information system per organization-defined frequency that is consistent with recovery time and recovery point objectives.
# NIST SP 800-53 :: CP-9 (b)
# NIST SP 800-53A :: CP-9.1 (v)
# NIST SP 800-53 Revision 4 :: CP-9 (b)
#
#
- name: check stig_rhel6_v1r18 v_38486
  set_fact: stig_rhel6_v1r18_results['v_38486'] = 'fail'
  when: '"v_38486" in stig_rhel6_v1r18_check_findings'


# Vuln ID: V-38488
# Severity: medium
# Group Title: SRG-OS-000099
# Rule ID: SV-50289r1_rule
# STIG ID: RHEL-06-000504
# Rule Title: The operating system must conduct backups of user-level information contained in the operating system per organization defined frequency to conduct backups consistent with recovery time and recovery point objectives.
# Discussion: Operating system backup is a critical step in maintaining data assurance and availability. User-level information is data generated by information system and/or application users. Backups shall be consistent with organizational recovery time and recovery point objectives.
# IA Controls:
# Check Content: Ask an administrator if a process exists to back up user data from the system.
#
# If such a process does not exist, this is a finding.
# Fix Text: Procedures to back up user data from the system must be established and executed. The Red Hat operating system provides utilities for automating such a process.  Commercial and open-source products are also available.
#
# Implement a process whereby user data is backed up from the system in accordance with local policies.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000535
# The organization conducts backups of user-level information contained in the information system per organization-defined frequency that is consistent with recovery time and recovery point objectives.
# NIST SP 800-53 :: CP-9 (a)
# NIST SP 800-53A :: CP-9.1 (iv)
# NIST SP 800-53 Revision 4 :: CP-9 (a)
#
#
- name: check stig_rhel6_v1r18 v_38488
  set_fact: stig_rhel6_v1r18_results['v_38488'] = 'fail'
  when: '"v_38488" in stig_rhel6_v1r18_check_findings'
