# Vuln ID: V-38444
# Severity: medium
# Group Title: SRG-OS-000231
# Rule ID: SV-50244r2_rule
# STIG ID: RHEL-06-000523
# Rule Title: The systems local IPv6 firewall must implement a deny-all, allow-by-exception policy for inbound packets.
# Discussion: In "ip6tables" the default policy is applied only after all the applicable rules in the table are examined for a match. Setting the default policy to "DROP" implements proper design for a firewall, i.e., any packets which are not explicitly permitted should not be accepted.
# IA Controls:
# Check Content: If IPv6 is disabled, this is not applicable.
#
# Inspect the file "/etc/sysconfig/ip6tables" to determine the default policy for the INPUT chain. It should be set to DROP:
#
# # grep ":INPUT" /etc/sysconfig/ip6tables
#
# If the default policy for the INPUT chain is not set to DROP, this is a finding.
# Fix Text: To set the default policy to DROP (instead of ACCEPT) for the built-in INPUT chain which processes incoming packets, add or correct the following line in "/etc/sysconfig/ip6tables":
#
# :INPUT DROP [0:0]
#
# Restart the IPv6 firewall:
#
# # service ip6tables restart
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000066
# The organization enforces requirements for remote connections to the information system.
# NIST SP 800-53 :: AC-17 e
# NIST SP 800-53A :: AC-17.1 (v)
#
#
- name: check stig_rhel6_v1r18 v_38444
  set_fact: stig_rhel6_v1r18_results['v_38444'] = 'fail'
  when: '"v_38444" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38512
# Severity: medium
# Group Title: SRG-OS-000146
# Rule ID: SV-50313r2_rule
# STIG ID: RHEL-06-000117
# Rule Title: The operating system must prevent public IPv4 access into an organizations internal networks, except as appropriately mediated by managed interfaces employing boundary protection devices.
# Discussion: The "iptables" service provides the system's host-based firewalling capability for IPv4 and ICMP.
# IA Controls:
# Check Content: If the system is a cross-domain system, this is not applicable.
#
# Run the following command to determine the current status of the "iptables" service:
#
# # service iptables status
#
# If the service is not running, it should return the following:
#
# iptables: Firewall is not running.
#
#
# If the service is not running, this is a finding.
# Fix Text: The "iptables" service can be enabled with the following commands:
#
# # chkconfig iptables on
# # service iptables start
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001100
# The information system prevents public access into the organization's internal networks except as appropriately mediated by managed interfaces employing boundary protection devices.
# NIST SP 800-53 :: SC-7 (2)
# NIST SP 800-53A :: SC-7 (2).1 (ii)
#
#
- name: check stig_rhel6_v1r18 v_38512
  set_fact: stig_rhel6_v1r18_results['v_38512'] = 'fail'
  when: '"v_38512" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38513
# Severity: medium
# Group Title: SRG-OS-000231
# Rule ID: SV-50314r2_rule
# STIG ID: RHEL-06-000120
# Rule Title: The systems local IPv4 firewall must implement a deny-all, allow-by-exception policy for inbound packets.
# Discussion: In "iptables" the default policy is applied only after all the applicable rules in the table are examined for a match. Setting the default policy to "DROP" implements proper design for a firewall, i.e., any packets which are not explicitly permitted should not be accepted.
# IA Controls:
# Check Content: Run the following command to ensure the default "INPUT" policy is "DROP":
#
# # iptables -nvL | grep -i input
#
# Chain INPUT (policy DROP 0 packets, 0 bytes)
#
# If the default policy for the INPUT chain is not set to DROP, this is a finding.
# Fix Text: To set the default policy to DROP (instead of ACCEPT) for the built-in INPUT chain which processes incoming packets, add or correct the following line in "/etc/sysconfig/iptables":
#
# :INPUT DROP [0:0]
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000066
# The organization enforces requirements for remote connections to the information system.
# NIST SP 800-53 :: AC-17 e
# NIST SP 800-53A :: AC-17.1 (v)
#
#
- name: check stig_rhel6_v1r18 v_38513
  set_fact: stig_rhel6_v1r18_results['v_38513'] = 'fail'
  when: '"v_38513" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38549
# Severity: medium
# Group Title: SRG-OS-000152
# Rule ID: SV-50350r3_rule
# STIG ID: RHEL-06-000103
# Rule Title: The system must employ a local IPv6 firewall.
# Discussion: The "ip6tables" service provides the system's host-based firewalling capability for IPv6 and ICMPv6.
# IA Controls:
# Check Content: If the system is a cross-domain system, this is not applicable.
#
# If IPv6 is disabled, this is not applicable.
#
# Run the following command to determine the current status of the "ip6tables" service:
#
# # service ip6tables status
#
# If the service is not running, it should return the following:
#
# ip6tables: Firewall is not running.
#
#
# If the service is not running, this is a finding.
# Fix Text: The "ip6tables" service can be enabled with the following commands:
#
# # chkconfig ip6tables on
# # service ip6tables start
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001118
# The information system implements host-based boundary protection mechanisms for servers, workstations, and mobile devices.
# NIST SP 800-53 :: SC-7 (12)
# NIST SP 800-53A :: SC-7 (12).1
#
#
- name: check stig_rhel6_v1r18 v_38549
  set_fact: stig_rhel6_v1r18_results['v_38549'] = 'fail'
  when: '"v_38549" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38551
# Severity: medium
# Group Title: SRG-OS-000145
# Rule ID: SV-50352r3_rule
# STIG ID: RHEL-06-000106
# Rule Title: The operating system must connect to external networks or information systems only through managed IPv6 interfaces consisting of boundary protection devices arranged in accordance with an organizational security architecture.
# Discussion: The "ip6tables" service provides the system's host-based firewalling capability for IPv6 and ICMPv6.
# IA Controls:
# Check Content: If the system is a cross-domain system, this is not applicable.
#
# If IPV6 is disabled, this is not applicable.
#
# Run the following command to determine the current status of the "ip6tables" service:
#
# # service ip6tables status
#
# If the service is not running, it should return the following:
#
# ip6tables: Firewall is not running.
#
#
# If the service is not running, this is a finding.
# Fix Text: The "ip6tables" service can be enabled with the following commands:
#
# # chkconfig ip6tables on
# # service ip6tables start
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001098
# The information system connects to external networks or information systems only through managed interfaces consisting of boundary protection devices arranged in accordance with an organizational security architecture.
# NIST SP 800-53 :: SC-7 b
# NIST SP 800-53A :: SC-7.1 (iv)
# NIST SP 800-53 Revision 4 :: SC-7 c
#
#
- name: check stig_rhel6_v1r18 v_38551
  set_fact: stig_rhel6_v1r18_results['v_38551'] = 'fail'
  when: '"v_38551" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38553
# Severity: medium
# Group Title: SRG-OS-000146
# Rule ID: SV-50354r3_rule
# STIG ID: RHEL-06-000107
# Rule Title: The operating system must prevent public IPv6 access into an organizations internal networks, except as appropriately mediated by managed interfaces employing boundary protection devices.
# Discussion: The "ip6tables" service provides the system's host-based firewalling capability for IPv6 and ICMPv6.
# IA Controls:
# Check Content: If the system is a cross-domain system, this is not applicable.
#
# If IPv6 is disabled, this is not applicable.
#
# Run the following command to determine the current status of the "ip6tables" service:
#
# # service ip6tables status
#
# If the service is not running, it should return the following:
#
# ip6tables: Firewall is not running.
#
#
# If the service is not running, this is a finding.
# Fix Text: The "ip6tables" service can be enabled with the following commands:
#
# # chkconfig ip6tables on
# # service ip6tables start
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001100
# The information system prevents public access into the organization's internal networks except as appropriately mediated by managed interfaces employing boundary protection devices.
# NIST SP 800-53 :: SC-7 (2)
# NIST SP 800-53A :: SC-7 (2).1 (ii)
#
#
- name: check stig_rhel6_v1r18 v_38553
  set_fact: stig_rhel6_v1r18_results['v_38553'] = 'fail'
  when: '"v_38553" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38555
# Severity: medium
# Group Title: SRG-OS-000152
# Rule ID: SV-50356r2_rule
# STIG ID: RHEL-06-000113
# Rule Title: The system must employ a local IPv4 firewall.
# Discussion: The "iptables" service provides the system's host-based firewalling capability for IPv4 and ICMP.
# IA Controls:
# Check Content: If the system is a cross-domain system, this is not applicable.
#
# Run the following command to determine the current status of the "iptables" service:
#
# # service iptables status
#
# If the service is not running, it should return the following:
#
# iptables: Firewall is not running.
#
#
# If the service is not running, this is a finding.
# Fix Text: The "iptables" service can be enabled with the following commands:
#
# # chkconfig iptables on
# # service iptables start
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001118
# The information system implements host-based boundary protection mechanisms for servers, workstations, and mobile devices.
# NIST SP 800-53 :: SC-7 (12)
# NIST SP 800-53A :: SC-7 (12).1
#
#
- name: check stig_rhel6_v1r18 v_38555
  set_fact: stig_rhel6_v1r18_results['v_38555'] = 'fail'
  when: '"v_38555" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38560
# Severity: medium
# Group Title: SRG-OS-000145
# Rule ID: SV-50361r2_rule
# STIG ID: RHEL-06-000116
# Rule Title: The operating system must connect to external networks or information systems only through managed IPv4 interfaces consisting of boundary protection devices arranged in accordance with an organizational security architecture.
# Discussion: The "iptables" service provides the system's host-based firewalling capability for IPv4 and ICMP.
# IA Controls:
# Check Content: If the system is a cross-domain system, this is not applicable.
#
# Run the following command to determine the current status of the "iptables" service:
#
# # service iptables status
#
# If the service is not running, it should return the following:
#
# iptables: Firewall is not running.
#
#
# If the service is not running, this is a finding.
# Fix Text: The "iptables" service can be enabled with the following commands:
#
# # chkconfig iptables on
# # service iptables start
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001098
# The information system connects to external networks or information systems only through managed interfaces consisting of boundary protection devices arranged in accordance with an organizational security architecture.
# NIST SP 800-53 :: SC-7 b
# NIST SP 800-53A :: SC-7.1 (iv)
# NIST SP 800-53 Revision 4 :: SC-7 c
#
#
- name: check stig_rhel6_v1r18 v_38560
  set_fact: stig_rhel6_v1r18_results['v_38560'] = 'fail'
  when: '"v_38560" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38686
# Severity: medium
# Group Title: SRG-OS-000147
# Rule ID: SV-50487r2_rule
# STIG ID: RHEL-06-000320
# Rule Title: The systems local firewall must implement a deny-all, allow-by-exception policy for forwarded packets.
# Discussion: In "iptables" the default policy is applied only after all the applicable rules in the table are examined for a match. Setting the default policy to "DROP" implements proper design for a firewall, i.e., any packets which are not explicitly permitted should not be accepted.
# IA Controls:
# Check Content: Run the following command to ensure the default "FORWARD" policy is "DROP":
#
# # iptables -nvL | grep -i forward
#
# Chain FORWARD (policy DROP 0 packets, 0 bytes)
#
# If the default policy for the FORWARD chain is not set to DROP, this is a finding.
# Fix Text: To set the default policy to DROP (instead of ACCEPT) for the built-in FORWARD chain which processes packets that will be forwarded from one interface to another, add or correct the following line in "/etc/sysconfig/iptables":
#
# :FORWARD DROP [0:0]
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001109
# The information system at managed interfaces denies network communications traffic by default and allows network communications traffic by exception (i.e., deny all, permit by exception).
# NIST SP 800-53 :: SC-7 (5)
# NIST SP 800-53A :: SC-7 (5).1 (i) (ii)
# NIST SP 800-53 Revision 4 :: SC-7 (5)
#
#
- name: check stig_rhel6_v1r18 v_38686
  set_fact: stig_rhel6_v1r18_results['v_38686'] = 'fail'
  when: '"v_38686" in stig_rhel6_v1r18_checks'
