# Vuln ID: V-38579
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-50380r2_rule
# STIG ID: RHEL-06-000065
# Rule Title: The system boot loader configuration file(s) must be owned by root.
# Discussion: Only root should be able to modify important boot parameters.
# IA Controls:
# Check Content: To check the ownership of "/boot/grub/grub.conf", run the command:
#
# $ ls -lL /boot/grub/grub.conf
#
# If properly configured, the output should indicate that the owner is "root".
# If it does not, this is a finding.
# Fix Text: The file "/boot/grub/grub.conf" should be owned by the "root" user to prevent destruction or modification of the file. To properly set the owner of "/boot/grub/grub.conf", run the command:
#
# # chown root /boot/grub/grub.conf
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38579
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38579: 'fail'})}}
  when: '"v_38579" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38581
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-50382r2_rule
# STIG ID: RHEL-06-000066
# Rule Title: The system boot loader configuration file(s) must be group-owned by root.
# Discussion: The "root" group is a highly-privileged group. Furthermore, the group-owner of this file should not have any access privileges anyway.
# IA Controls:
# Check Content: To check the group ownership of "/boot/grub/grub.conf", run the command:
#
# $ ls -lL /boot/grub/grub.conf
#
# If properly configured, the output should indicate the group-owner is "root".
# If it does not, this is a finding.
# Fix Text: The file "/boot/grub/grub.conf" should be group-owned by the "root" group to prevent destruction or modification of the file. To properly set the group owner of "/boot/grub/grub.conf", run the command:
#
# # chgrp root /boot/grub/grub.conf
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38581
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38581: 'fail'})}}
  when: '"v_38581" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38583
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-50384r4_rule
# STIG ID: RHEL-06-000067
# Rule Title: The system boot loader configuration file(s) must have mode 0600 or less permissive.
# Discussion: Proper permissions ensure that only the root user can modify important boot parameters.
# IA Controls:
# Check Content: To check the permissions of "/boot/grub/grub.conf", run the command:
#
# $ sudo ls -lL /boot/grub/grub.conf
#
# If the system uses UEFI check the permissions of “/boot/efi/EFI/redhat/grub.conf” file:
#
# $ sudo ls –lL /boot/efi/EFI/redhat/grub.conf
#
# If properly configured, the output should indicate the following permissions: "-rw-------"
#
# If it does not, this is a finding.
# Fix Text: File permissions for "/boot/grub/grub.conf" and “/boot/efi/EFI/redhat/grub.conf” should be set to 600, which is the default.
#
# To properly set the permissions of "/boot/grub/grub.conf", run the command:
#
# $ chmod 600 /boot/grub/grub.conf
#
# To properly set the permissions of “/boot/efi/EFI/redhat/grub.conf”, run the command:
#
# $ chmod 600 /boot/efi/EFI/redhat/grub.conf
#
# Boot partitions based on VFAT, NTFS, or other non-standard configurations may require alternative measures.
#
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38583
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38583: 'fail'})}}
  when: '"v_38583" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38585
# Severity: medium
# Group Title: SRG-OS-000080
# Rule ID: SV-50386r4_rule
# STIG ID: RHEL-06-000068
# Rule Title: The system boot loader must require authentication.
# Discussion: Password protection on the boot loader configuration ensures users with physical access cannot trivially alter important bootloader settings. These include which kernel to use, and whether to enter single-user mode.
# IA Controls:
# Check Content: To verify the boot loader password has been set and encrypted, run the following command:
#
# # grep password /boot/grub/grub.conf
#
# The output should show the following:
#
# password --encrypted $6$[rest-of-the-password-hash]
#
# If it does not, this is a finding.
#
# If the system uses UEFI verify the boot loader password has been set and encrypted:
#
# # grep password /boot/efi/EFI/redhat/grub.conf
# Fix Text: The grub boot loader should have password protection enabled to protect boot-time settings. To do so, select a password and then generate a hash from it by running the following command:
#
# # grub-crypt --sha-512
#
# When prompted to enter a password, insert the following line into "/boot/grub/grub.conf" or “/boot/efi/EFI/redhat/grub.conf” immediately after the header comments. (Use the output from "grub-crypt" as the value of [password-hash]):
#
# password --encrypted [password-hash]
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000213
# The information system enforces approved authorizations for logical access to information and system resources in accordance with applicable access control policies.
# NIST SP 800-53 :: AC-3
# NIST SP 800-53A :: AC-3.1
# NIST SP 800-53 Revision 4 :: AC-3
#
#
- name: check stig_rhel6_v1r18 v_38585
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38585: 'fail'})}}
  when: '"v_38585" in stig_rhel6_v1r18_checks'


# Vuln ID: V-51337
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-65547r2_rule
# STIG ID: RHEL-06-000017
# Rule Title: The system must use a Linux Security Module at boot time.
# Discussion: Disabling a major host protection feature, such as SELinux, at boot time prevents it from confining system services at boot time. Further, it increases the chances that it will remain off during system operation.
# IA Controls:
# Check Content: Inspect "/boot/grub/grub.conf" for any instances of "selinux=0" in the kernel boot arguments. Presence of "selinux=0" indicates that SELinux is disabled at boot time. If SELinux is disabled at boot time, this is a finding.
# Fix Text: SELinux can be disabled at boot time by an argument in "/boot/grub/grub.conf". Remove any instances of "selinux=0" from the kernel arguments in that file to prevent SELinux from being disabled at boot.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_51337
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_51337: 'fail'})}}
  when: '"v_51337" in stig_rhel6_v1r18_checks'
