# Vuln ID: V-38586
# Severity: medium
# Group Title: SRG-OS-000080
# Rule ID: SV-50387r1_rule
# STIG ID: RHEL-06-000069
# Rule Title: The system must require authentication upon booting into single-user and maintenance modes.
# Discussion: This prevents attackers with physical access from trivially bypassing security on the machine and gaining root access. Such accesses are further prevented by configuring the bootloader password.
# IA Controls:
# Check Content: To check if authentication is required for single-user mode, run the following command:
#
# $ grep SINGLE /etc/sysconfig/init
#
# The output should be the following:
#
# SINGLE=/sbin/sulogin
#
#
# If the output is different, this is a finding.
# Fix Text: Single-user mode is intended as a system recovery method, providing a single user root access to the system by providing a boot option at startup. By default, no authentication is performed if single-user mode is selected.
#
# To require entry of the root password even if the system is started in single-user mode, add or correct the following line in the file "/etc/sysconfig/init":
#
# SINGLE=/sbin/sulogin
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000213
# The information system enforces approved authorizations for logical access to information and system resources in accordance with applicable access control policies.
# NIST SP 800-53 :: AC-3
# NIST SP 800-53A :: AC-3.1
# NIST SP 800-53 Revision 4 :: AC-3
#
#
- name: check stig_rhel6_v1r18 v_38586
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38586: 'fail'})}}
  when: '"v_38586" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38588
# Severity: medium
# Group Title: SRG-OS-000080
# Rule ID: SV-50389r1_rule
# STIG ID: RHEL-06-000070
# Rule Title: The system must not permit interactive boot.
# Discussion: Using interactive boot, the console user could disable auditing, firewalls, or other services, weakening system security.
# IA Controls:
# Check Content: To check whether interactive boot is disabled, run the following command:
#
# $ grep PROMPT /etc/sysconfig/init
#
# If interactive boot is disabled, the output will show:
#
# PROMPT=no
#
#
# If it does not, this is a finding.
# Fix Text: To disable the ability for users to perform interactive startups, edit the file "/etc/sysconfig/init". Add or correct the line:
#
# PROMPT=no
#
# The "PROMPT" option allows the console user to perform an interactive system startup, in which it is possible to select the set of services which are started on boot.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000213
# The information system enforces approved authorizations for logical access to information and system resources in accordance with applicable access control policies.
# NIST SP 800-53 :: AC-3
# NIST SP 800-53A :: AC-3.1
# NIST SP 800-53 Revision 4 :: AC-3
#
#
- name: check stig_rhel6_v1r18 v_38588
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38588: 'fail'})}}
  when: '"v_38588" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38668
# Severity: high
# Group Title: SRG-OS-999999
# Rule ID: SV-50469r3_rule
# STIG ID: RHEL-06-000286
# Rule Title: The x86 Ctrl-Alt-Delete key sequence must be disabled.
# Discussion: A locally logged-in user who presses Ctrl-Alt-Delete, when at the console, can reboot the system. If accidentally pressed, as could happen in the case of mixed OS environment, this can create the risk of short-term loss of availability of systems due to unintentional reboot. In the GNOME graphical environment, risk of unintentional reboot from the Ctrl-Alt-Delete sequence is reduced because the user will be prompted before any action is taken.
# IA Controls:
# Check Content: To ensure the system is configured to log a message instead of rebooting the system when Ctrl-Alt-Delete is pressed, ensure the following line is in "/etc/init/control-alt-delete.override":
#
# exec /usr/bin/logger -p security.info "Ctrl-Alt-Delete pressed"
#
# If the system is not configured to block the shutdown command when Ctrl-Alt-Delete is pressed, this is a finding.
# Fix Text: By default, the system includes the following line in "/etc/init/control-alt-delete.conf" to reboot the system when the Ctrl-Alt-Delete key sequence is pressed:
#
# exec /sbin/shutdown -r now "Ctrl-Alt-Delete pressed"
#
#
# To configure the system to log a message instead of rebooting the system, add the following line to "/etc/init/control-alt-delete.override" to read as follows:
#
# exec /usr/bin/logger -p security.info "Ctrl-Alt-Delete pressed"
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38668
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38668: 'fail'})}}
  when: '"v_38668" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38674
# Severity: medium
# Group Title: SRG-OS-000248
# Rule ID: SV-50475r1_rule
# STIG ID: RHEL-06-000290
# Rule Title: X Windows must not be enabled unless required.
# Discussion: Unnecessary services should be disabled to decrease the attack surface of the system.
# IA Controls:
# Check Content: To verify the default runlevel is 3, run the following command:
#
# # grep initdefault /etc/inittab
#
# The output should show the following:
#
# id:3:initdefault:
#
#
# If it does not, this is a finding.
# Fix Text: Setting the system's runlevel to 3 will prevent automatic startup of the X server. To do so, ensure the following line in "/etc/inittab" features a "3" as shown:
#
# id:3:initdefault:
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001436
# The organization disables organization defined networking protocols within the information system deemed to be nonsecure except for explicitly identified components in support of specific operational requirements.
# NIST SP 800-53 :: AC-17 (8)
# NIST SP 800-53A :: AC-17 (8).1 (ii)
#
#
- name: check stig_rhel6_v1r18 v_38674
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38674: 'fail'})}}
  when: '"v_38674" in stig_rhel6_v1r18_checks'
