# Vuln ID: V-38490
# Severity: medium
# Group Title: SRG-OS-000273
# Rule ID: SV-50291r6_rule
# STIG ID: RHEL-06-000503
# Rule Title: The operating system must enforce requirements for the connection of mobile devices to operating systems.
# Discussion: USB storage devices such as thumb drives can be used to introduce unauthorized software and other vulnerabilities. Support for these devices should be disabled and the devices themselves should be tightly controlled.
# IA Controls:
# Check Content: If the system is configured to prevent the loading of the "usb-storage" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf":
#
# $ grep -r usb-storage /etc/modprobe.conf /etc/modprobe.d | grep -i “/bin/true” | grep -v “#”
#
# If no line is returned, this is a finding.
# Fix Text: To prevent USB storage devices from being used, configure the kernel module loading system to prevent automatic loading of the USB storage driver. To configure the system to prevent the "usb-storage" kernel module from being loaded, add the following line to a file in the directory "/etc/modprobe.d":
#
# install usb-storage /bin/true
#
# This will prevent the "modprobe" program from loading the "usb-storage" module, but will not prevent an administrator (or another program) from using the "insmod" program to load the module manually.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000086
# The organization enforces requirements for the connection of mobile devices to organizational information systems.
# NIST SP 800-53 :: AC-19 d
# NIST SP 800-53A :: AC-19.1 (iv)
#
#
- name: check stig_rhel6_v1r18 v_38490
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38490: 'fail'})}}
  when: '"v_38490" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38514
# Severity: medium
# Group Title: SRG-OS-000096
# Rule ID: SV-50315r5_rule
# STIG ID: RHEL-06-000124
# Rule Title: The Datagram Congestion Control Protocol (DCCP) must be disabled unless required.
# Discussion: Disabling DCCP protects the system against exploitation of any flaws in its implementation.
# IA Controls:
# Check Content: If the system is configured to prevent the loading of the "dccp" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf":
#
# $ grep -r dccp /etc/modprobe.conf /etc/modprobe.d | grep -i “/bin/true”| grep -v “#”
#
# If no line is returned, this is a finding.
# Fix Text: The Datagram Congestion Control Protocol (DCCP) is a relatively new transport layer protocol, designed to support streaming media and telephony. To configure the system to prevent the "dccp" kernel module from being loaded, add the following line to a file in the directory "/etc/modprobe.d":
#
# install dccp /bin/true
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000382
# The organization configures the information system to prohibit or restrict the use of organization defined functions, ports, protocols, and/or services.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (iii)
# NIST SP 800-53 Revision 4 :: CM-7 b
#
#
- name: check stig_rhel6_v1r18 v_38514
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38514: 'fail'})}}
  when: '"v_38514" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38515
# Severity: medium
# Group Title: SRG-OS-000096
# Rule ID: SV-50316r5_rule
# STIG ID: RHEL-06-000125
# Rule Title: The Stream Control Transmission Protocol (SCTP) must be disabled unless required.
# Discussion: Disabling SCTP protects the system against exploitation of any flaws in its implementation.
# IA Controls:
# Check Content: If the system is configured to prevent the loading of the "sctp" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf":
#
# $ grep -r sctp /etc/modprobe.conf /etc/modprobe.d | grep -i “/bin/true”| grep -v “#”
#
# If no line is returned, this is a finding.
# Fix Text: The Stream Control Transmission Protocol (SCTP) is a transport layer protocol, designed to support the idea of message-oriented communication, with several streams of messages within one connection. To configure the system to prevent the "sctp" kernel module from being loaded, add the following line to a file in the directory "/etc/modprobe.d":
#
# install sctp /bin/true
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000382
# The organization configures the information system to prohibit or restrict the use of organization defined functions, ports, protocols, and/or services.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (iii)
# NIST SP 800-53 Revision 4 :: CM-7 b
#
#
- name: check stig_rhel6_v1r18 v_38515
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38515: 'fail'})}}
  when: '"v_38515" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38516
# Severity: low
# Group Title: SRG-OS-000096
# Rule ID: SV-50317r3_rule
# STIG ID: RHEL-06-000126
# Rule Title: The Reliable Datagram Sockets (RDS) protocol must be disabled unless required.
# Discussion: Disabling RDS protects the system against exploitation of any flaws in its implementation.
# IA Controls:
# Check Content: If the system is configured to prevent the loading of the "rds" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated "/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf":
#
# $ grep -r rds /etc/modprobe.conf /etc/modprobe.d
#
# If no line is returned, this is a finding.
# Fix Text: The Reliable Datagram Sockets (RDS) protocol is a transport layer protocol designed to provide reliable high-bandwidth, low-latency communications between nodes in a cluster. To configure the system to prevent the "rds" kernel module from being loaded, add the following line to a file in the directory "/etc/modprobe.d":
#
# install rds /bin/true
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000382
# The organization configures the information system to prohibit or restrict the use of organization defined functions, ports, protocols, and/or services.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (iii)
# NIST SP 800-53 Revision 4 :: CM-7 b
#
#
- name: check stig_rhel6_v1r18 v_38516
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38516: 'fail'})}}
  when: '"v_38516" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38517
# Severity: medium
# Group Title: SRG-OS-000096
# Rule ID: SV-50318r5_rule
# STIG ID: RHEL-06-000127
# Rule Title: The Transparent Inter-Process Communication (TIPC) protocol must be disabled unless required.
# Discussion: Disabling TIPC protects the system against exploitation of any flaws in its implementation.
# IA Controls:
# Check Content: If the system is configured to prevent the loading of the "tipc" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf":
#
# $ grep -r tipc /etc/modprobe.conf /etc/modprobe.d | grep -i “/bin/true”| grep -v “#”
#
# If no line is returned, this is a finding.
# Fix Text: The Transparent Inter-Process Communication (TIPC) protocol is designed to provide communications between nodes in a cluster. To configure the system to prevent the "tipc" kernel module from being loaded, add the following line to a file in the directory "/etc/modprobe.d":
#
# install tipc /bin/true
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000382
# The organization configures the information system to prohibit or restrict the use of organization defined functions, ports, protocols, and/or services.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (iii)
# NIST SP 800-53 Revision 4 :: CM-7 b
#
#
- name: check stig_rhel6_v1r18 v_38517
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38517: 'fail'})}}
  when: '"v_38517" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38682
# Severity: medium
# Group Title: SRG-OS-000034
# Rule ID: SV-50483r5_rule
# STIG ID: RHEL-06-000315
# Rule Title: The Bluetooth kernel module must be disabled.
# Discussion: If Bluetooth functionality must be disabled, preventing the kernel from loading the kernel module provides an additional safeguard against its activation.
# IA Controls:
# Check Content: If the system is configured to prevent the loading of the "bluetooth" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf":
#
# $ grep -r bluetooth /etc/modprobe.conf /etc/modprobe.d | grep -i “/bin/true”| grep -v “#”
#
# If no line is returned, this is a finding.
#
# If the system is configured to prevent the loading of the "net-pf-31" kernel module, it will contain lines inside any file in "/etc/modprobe.d" or the deprecated"/etc/modprobe.conf". These lines instruct the module loading system to run another program (such as "/bin/true") upon a module "install" event. Run the following command to search for such lines in all files in "/etc/modprobe.d" and the deprecated "/etc/modprobe.conf":
#
# $ grep -r net-pf-31 /etc/modprobe.conf /etc/modprobe.d | grep -i “/bin/true” | grep -v “#”
#
# If no line is returned, this is a finding.
# Fix Text: The kernel's module loading system can be configured to prevent loading of the Bluetooth module. Add the following to the appropriate "/etc/modprobe.d" configuration file to prevent the loading of the Bluetooth module:
#
# install net-pf-31 /bin/true
# install bluetooth /bin/true
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000085
# The organization monitors for unauthorized connections of mobile devices to organizational information systems.
# NIST SP 800-53 :: AC-19 c
# NIST SP 800-53A :: AC-19.1 (iii)
#
#
- name: check stig_rhel6_v1r18 v_38682
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38682: 'fail'})}}
  when: '"v_38682" in stig_rhel6_v1r18_checks'
