# Vuln ID: V-38497
# Severity: high
# Group Title: SRG-OS-999999
# Rule ID: SV-50298r2_rule
# STIG ID: RHEL-06-000030
# Rule Title: The system must not have accounts configured with blank or null passwords.
# Discussion: If an account has an empty password, anyone could log in and run commands with the privileges of that account. Accounts with empty passwords should never be used in operational environments.
# IA Controls:
# Check Content: To verify that null passwords cannot be used, run the following command:
#
# # grep nullok /etc/pam.d/system-auth
#
# If this produces any output, it may be possible to log into accounts with empty passwords.
# If NULL passwords can be used, this is a finding.
# Fix Text: If an account is configured for password authentication but does not have an assigned password, it may be possible to log onto the account without authentication. Remove any instances of the "nullok" option in "/etc/pam.d/system-auth" to prevent logons with empty passwords.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38497
  set_fact: stig_rhel6_v1r18_results['v_38497'] = 'fail'
  when: '"v_38497" in check_findings'


# Vuln ID: V-38501
# Severity: medium
# Group Title: SRG-OS-000249
# Rule ID: SV-50302r4_rule
# STIG ID: RHEL-06-000357
# Rule Title: The system must disable accounts after excessive login failures within a 15-minute interval.
# Discussion: Locking out user accounts after a number of incorrect attempts within a specific period of time prevents direct password guessing attacks.
# IA Controls:
# Check Content: To ensure the failed password attempt policy is configured correctly, run the following command:
#
# $ grep pam_faillock /etc/pam.d/system-auth /etc/pam.d/password-auth
#
# For each file, the output should show "fail_interval=<interval-in-seconds>" where "interval-in-seconds" is 900 (15 minutes) or greater. If the "fail_interval" parameter is not set, the default setting of 900 seconds is acceptable. If that is not the case, this is a finding.
# Fix Text: Utilizing "pam_faillock.so", the "fail_interval" directive configures the system to lock out accounts after a number of incorrect logon attempts. Modify the content of both "/etc/pam.d/system-auth" and "/etc/pam.d/password-auth" as follows:
#
# Add the following line immediately before the "pam_unix.so" statement in the "AUTH" section:
#
# auth required pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900
#
# Add the following line immediately after the "pam_unix.so" statement in the "AUTH" section:
#
# auth [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900
#
# Add the following line immediately before the "pam_unix.so" statement in the "ACCOUNT" section:
#
# account required pam_faillock.so
#
# Note that any updates made to "/etc/pam.d/system-auth" and "/etc/pam.d/password-auth" may be overwritten by the "authconfig" program.  The "authconfig" program should not be used.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001452
# The information system enforces the organization defined time period during which the limit of consecutive invalid access attempts by a user is counted.
# NIST SP 800-53 :: AC-7 a
# NIST SP 800-53A :: AC-7.1 (ii)
#
#
- name: check stig_rhel6_v1r18 v_38501
  set_fact: stig_rhel6_v1r18_results['v_38501'] = 'fail'
  when: '"v_38501" in check_findings'


# Vuln ID: V-38573
# Severity: medium
# Group Title: SRG-OS-000021
# Rule ID: SV-50374r4_rule
# STIG ID: RHEL-06-000061
# Rule Title: The system must disable accounts after three consecutive unsuccessful logon attempts.
# Discussion: Locking out user accounts after a number of incorrect attempts prevents direct password guessing attacks.
# IA Controls:
# Check Content: To ensure the failed password attempt policy is configured correctly, run the following command:
#
# # grep pam_faillock /etc/pam.d/system-auth /etc/pam.d/password-auth
#
# The output should show "deny=3" for both files.
# If that is not the case, this is a finding.
# Fix Text: To configure the system to lock out accounts after a number of incorrect logon attempts using "pam_faillock.so", modify the content of both "/etc/pam.d/system-auth" and "/etc/pam.d/password-auth" as follows:
#
# Add the following line immediately before the "pam_unix.so" statement in the "AUTH" section:
#
# auth required pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900
#
# Add the following line immediately after the "pam_unix.so" statement in the "AUTH" section:
#
# auth [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900
#
# Add the following line immediately before the "pam_unix.so" statement in the "ACCOUNT" section:
#
# account required pam_faillock.so
#
# Note that any updates made to "/etc/pam.d/system-auth" and "/etc/pam.d/password-auth" may be overwritten by the "authconfig" program.  The "authconfig" program should not be used.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000044
# The information system enforces the organization-defined limit of consecutive invalid logon attempts by a user during the organization-defined time period.
# NIST SP 800-53 :: AC-7 a
# NIST SP 800-53A :: AC-7.1 (ii)
# NIST SP 800-53 Revision 4 :: AC-7 a
#
#
- name: check stig_rhel6_v1r18 v_38573
  set_fact: stig_rhel6_v1r18_results['v_38573'] = 'fail'
  when: '"v_38573" in check_findings'


# Vuln ID: V-38574
# Severity: medium
# Group Title: SRG-OS-000120
# Rule ID: SV-50375r3_rule
# STIG ID: RHEL-06-000062
# Rule Title: The system must use a FIPS 140-2 approved cryptographic hashing algorithm for generating account password hashes (system-auth).
# Discussion: Using a stronger hashing algorithm makes password cracking attacks more difficult.
# IA Controls:
# Check Content: Inspect the "password" section of "/etc/pam.d/system-auth", "/etc/pam.d/system-auth-ac", and other files in "/etc/pam.d" to identify the number of occurrences where the “pam_unix.so” module is used in the “password” section.
# $ grep -E -c 'password.*pam_unix.so' /etc/pam.d/*
#
# /etc/pam.d/atd:0
# /etc/pam.d/config-util:0
# /etc/pam.d/crond:0
# /etc/pam.d/login:0
# /etc/pam.d/other:0
# /etc/pam.d/passwd:0
# /etc/pam.d/password-auth:1
# /etc/pam.d/password-auth-ac:1
# /etc/pam.d/sshd:0
# /etc/pam.d/su:0
# /etc/pam.d/sudo:0
# /etc/pam.d/system-auth:1
# /etc/pam.d/system-auth-ac:1
# /etc/pam.d/vlock:0
#
# Note: The number adjacent to the file name indicates how many occurrences of the “pam_unix.so” module are found in the password section.
#
# If the “pam_unix.so” module is not defined in the “password” section of “/etc/pam.d/system-auth”, “/etc/pam.d/system-auth-ac”, “/etc/pam.d/password-auth”, and “/etc/pam.d/password-auth-ac” at a minimum, this is a finding.
#
# Verify that the “sha512” variable is used with each instance of the “pam_unix.so” module in the “password” section:
#
# $ grep password /etc/pam.d/* | grep pam_unix.so | grep sha512
#
# /etc/pam.d/password-auth:password    	sufficient    pam_unix.so sha512 [other arguments…]
# /etc/pam.d/password-auth-ac:password    sufficient    pam_unix.so sha512 [other arguments…]
# /etc/pam.d/system-auth:password    	sufficient    pam_unix.so sha512 [other arguments…]
# /etc/pam.d/system-auth-ac:password    	sufficient    pam_unix.so sha512 [other arguments…]
#
# If this list of files does not coincide with the previous command, this is a finding.
#
# If any of the identified “pam_unix.so” modules do not use the “sha512” variable, this is a finding.
#
# Fix Text: In "/etc/pam.d/system-auth”, "/etc/pam.d/system-auth-ac", “/etc/pam.d/password-auth”, and “/etc/pam.d/password-auth-ac”, among potentially other files, the "password" section of the files controls which PAM modules execute during a password change. Set the "pam_unix.so" module in the "password" section to include the argument "sha512", as shown below:
#
# password sufficient pam_unix.so sha512 [other arguments...]
#
# This will help ensure when local users change their passwords, hashes for the new passwords will be generated using the SHA-512 algorithm. This is the default.
#
# Note that any updates made to "/etc/pam.d/system-auth" will be overwritten by the "authconfig" program. The "authconfig" program should not be used.
#
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000803
# The information system implements mechanisms for authentication to a cryptographic module that meet the requirements of applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance for such authentication.
# NIST SP 800-53 :: IA-7
# NIST SP 800-53A :: IA-7.1
# NIST SP 800-53 Revision 4 :: IA-7
#
#
- name: check stig_rhel6_v1r18 v_38574
  set_fact: stig_rhel6_v1r18_results['v_38574'] = 'fail'
  when: '"v_38574" in check_findings'


# Vuln ID: V-38592
# Severity: medium
# Group Title: SRG-OS-000022
# Rule ID: SV-50393r4_rule
# STIG ID: RHEL-06-000356
# Rule Title: The system must require administrator action to unlock an account locked by excessive failed login attempts.
# Discussion: Locking out user accounts after a number of incorrect attempts prevents direct password guessing attacks. Ensuring that an administrator is involved in unlocking locked accounts draws appropriate attention to such situations.
# IA Controls:
# Check Content: To ensure the failed password attempt policy is configured correctly, run the following command:
#
# # grep pam_faillock /etc/pam.d/system-auth /etc/pam.d/password-auth
#
# The output should show "unlock_time=<some-large-number>"; the largest acceptable value is 604800 seconds (one week).
# If that is not the case, this is a finding.
# Fix Text: To configure the system to lock out accounts after a number of incorrect logon attempts and require an administrator to unlock the account using "pam_faillock.so", modify the content of both "/etc/pam.d/system-auth" and "/etc/pam.d/password-auth" as follows:
#
# Add the following line immediately before the "pam_unix.so" statement in the "AUTH" section:
#
# auth required pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900
#
# Add the following line immediately after the "pam_unix.so" statement in the "AUTH" section:
#
# auth [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900
#
# Add the following line immediately before the "pam_unix.so" statement in the "ACCOUNT" section:
#
# account required pam_faillock.so
#
# Note that any updates made to "/etc/pam.d/system-auth" and "/etc/pam.d/password-auth" may be overwritten by the "authconfig" program.  The "authconfig" program should not be used.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000047
# The information system delays next login prompt according to organization defined delay algorithm, when the maximum number of unsuccessful attempts is exceeded, automatically locks the account/node for an organization defined time period or locks the account/node until released by an Administrator IAW organizational policy.
# NIST SP 800-53 :: AC-7 b
# NIST SP 800-53A :: AC-7.1 (iv)
#
#
- name: check stig_rhel6_v1r18 v_38592
  set_fact: stig_rhel6_v1r18_results['v_38592'] = 'fail'
  when: '"v_38592" in check_findings'


# Vuln ID: V-38658
# Severity: medium
# Group Title: SRG-OS-000077
# Rule ID: SV-50459r5_rule
# STIG ID: RHEL-06-000274
# Rule Title: The system must prohibit the reuse of passwords within five iterations.
# Discussion: Preventing reuse of previous passwords helps ensure that a compromised password is not reused by a user.
# IA Controls:
# Check Content: To verify the password reuse setting is compliant, run the following command:
#
# # grep remember /etc/pam.d/system-auth
#
# The output must be a line beginning with "password required pam_pwhistory.so" or "password requisite pam_pwhistory.so" and end with "remember=5".
#
# If the line is commented out, the line does not contain the specified elements, or the value for "remember" is less than 5, this is a finding.
# Fix Text: Do not allow users to reuse recent passwords. This can be accomplished by using the "remember" option for the "pam_pwhistory" PAM module. In the file "/etc/pam.d/system-auth", append "remember=5" to the line which refers to the "pam_pwhistory.so" module, as shown:
#
# password required pam_pwhistory.so [existing_options] remember=5
#
# or
#
# password requisite pam_pwhistory.so [existing_options] remember=5
#
# The DoD requirement is five passwords.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000200
# The information system prohibits password reuse for the organization defined number of generations.
# NIST SP 800-53 :: IA-5 (1) (e)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (e)
#
#
- name: check stig_rhel6_v1r18 v_38658
  set_fact: stig_rhel6_v1r18_results['v_38658'] = 'fail'
  when: '"v_38658" in check_findings'


# Vuln ID: V-51875
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-66089r1_rule
# STIG ID: RHEL-06-000372
# Rule Title: The operating system, upon successful logon/access, must display to the user the number of unsuccessful logon/access attempts since the last successful logon/access.
# Discussion: Users need to be aware of activity that occurs regarding their account. Providing users with information regarding the number of unsuccessful attempts that were made to login to their account allows the user to determine if any unauthorized activity has occurred and gives them an opportunity to notify administrators.
# IA Controls:
# Check Content: To ensure that last logon/access notification is configured correctly, run the following command:
#
# # grep pam_lastlog.so /etc/pam.d/system-auth
#
# The output should show output "showfailed". If that is not the case, this is a finding.
# Fix Text: To configure the system to notify users of last logon/access using "pam_lastlog", add the following line immediately after "session required pam_limits.so":
#
# session required pam_lastlog.so showfailed
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_51875
  set_fact: stig_rhel6_v1r18_results['v_51875'] = 'fail'
  when: '"v_51875" in check_findings'
