# Vuln ID: V-38475
# Severity: medium
# Group Title: SRG-OS-000078
# Rule ID: SV-50275r3_rule
# STIG ID: RHEL-06-000050
# Rule Title: The system must require passwords to contain a minimum of 15 characters.
# Discussion: Requiring a minimum password length makes password cracking attacks more difficult by ensuring a larger search space. However, any security benefit from an onerous requirement must be carefully weighed against usability problems, support costs, or counterproductive behavior that may result.
#
# While it does not negate the password length requirement, it is preferable to migrate from a password-based authentication scheme to a stronger one based on PKI (public key infrastructure).
# IA Controls:
# Check Content: To check the minimum password length, run the command:
#
# $ grep PASS_MIN_LEN /etc/login.defs
#
# The DoD requirement is "15".
#
# If it is not set to the required value, this is a finding.
#
# $ grep –E ‘pam_cracklib.so.*minlen’ /etc/pam.d/*
#
# If no results are returned, this is not a finding.
#
# If any results are returned and are not set to “15” or greater, this is a finding.
#
# Fix Text: To specify password length requirements for new accounts, edit the file "/etc/login.defs" and add or correct the following lines:
#
# PASS_MIN_LEN 15
#
# The DoD requirement is "15". If a program consults "/etc/login.defs" and also another PAM module (such as "pam_cracklib") during a password change operation, then the most restrictive must be satisfied.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000205
# The information system enforces minimum password length.
# NIST SP 800-53 :: IA-5 (1) (a)
# NIST SP 800-53A :: IA-5 (1).1 (i)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (a)
#
#
- name: check stig_rhel6_v1r18 v_38475
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38475': 'fail'})}}"
  when: '"v_38475" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38477
# Severity: medium
# Group Title: SRG-OS-000075
# Rule ID: SV-50277r1_rule
# STIG ID: RHEL-06-000051
# Rule Title: Users must not be able to change passwords more than once every 24 hours.
# Discussion: Setting the minimum password age protects against users cycling back to a favorite password after satisfying the password reuse requirement.
# IA Controls:
# Check Content: To check the minimum password age, run the command:
#
# $ grep PASS_MIN_DAYS /etc/login.defs
#
# The DoD requirement is 1.
# If it is not set to the required value, this is a finding.
# Fix Text: To specify password minimum age for new accounts, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately:
#
# PASS_MIN_DAYS [DAYS]
#
# A value of 1 day is considered sufficient for many environments. The DoD requirement is 1.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000198
# The information system enforces minimum password lifetime restrictions.
# NIST SP 800-53 :: IA-5 (1) (d)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (d)
#
#
- name: check stig_rhel6_v1r18 v_38477
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38477': 'fail'})}}"
  when: '"v_38477" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38479
# Severity: medium
# Group Title: SRG-OS-000076
# Rule ID: SV-50279r1_rule
# STIG ID: RHEL-06-000053
# Rule Title: User passwords must be changed at least every 60 days.
# Discussion: Setting the password maximum age ensures users are required to periodically change their passwords. This could possibly decrease the utility of a stolen password. Requiring shorter password lifetimes increases the risk of users writing down the password in a convenient location subject to physical compromise.
# IA Controls:
# Check Content: To check the maximum password age, run the command:
#
# $ grep PASS_MAX_DAYS /etc/login.defs
#
# The DoD requirement is 60.
# If it is not set to the required value, this is a finding.
# Fix Text: To specify password maximum age for new accounts, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately:
#
# PASS_MAX_DAYS [DAYS]
#
# The DoD requirement is 60.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000199
# The information system enforces maximum password lifetime restrictions.
# NIST SP 800-53 :: IA-5 (1) (d)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (d)
#
#
- name: check stig_rhel6_v1r18 v_38479
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38479': 'fail'})}}"
  when: '"v_38479" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38480
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50280r1_rule
# STIG ID: RHEL-06-000054
# Rule Title: Users must be warned 7 days in advance of password expiration.
# Discussion: Setting the password warning age enables users to make the change at a practical time.
# IA Controls:
# Check Content: To check the password warning age, run the command:
#
# $ grep PASS_WARN_AGE /etc/login.defs
#
# The DoD requirement is 7.
# If it is not set to the required value, this is a finding.
# Fix Text: To specify how many days prior to password expiration that a warning will be issued to users, edit the file "/etc/login.defs" and add or correct the following line, replacing [DAYS] appropriately:
#
# PASS_WARN_AGE [DAYS]
#
# The DoD requirement is 7.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38480
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38480': 'fail'})}}"
  when: '"v_38480" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38482
# Severity: low
# Group Title: SRG-OS-000071
# Rule ID: SV-50282r1_rule
# STIG ID: RHEL-06-000056
# Rule Title: The system must require passwords to contain at least one numeric character.
# Discussion: Requiring digits makes password guessing attacks more difficult by ensuring a larger search space.
# IA Controls:
# Check Content: To check how many digits are required in a password, run the following command:
#
# $ grep pam_cracklib /etc/pam.d/system-auth
#
# The "dcredit" parameter (as a negative number) will indicate how many digits are required. The DoD requires at least one digit in a password. This would appear as "dcredit=-1".
# If dcredit is not found or not set to the required value, this is a finding.
# Fix Text: The pam_cracklib module's "dcredit" parameter controls requirements for usage of digits in a password. When set to a negative number, any password will be required to contain that many digits. When set to a positive number, pam_cracklib will grant +1 additional length credit for each digit. Add "dcredit=-1" after pam_cracklib.so to require use of a digit in passwords.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000194
# The information system enforces password complexity by the minimum number of numeric characters used.
# NIST SP 800-53 :: IA-5 (1) (a)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (a)
#
#
- name: check stig_rhel6_v1r18 v_38482
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38482': 'fail'})}}"
  when: '"v_38482" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38569
# Severity: low
# Group Title: SRG-OS-000069
# Rule ID: SV-50370r1_rule
# STIG ID: RHEL-06-000057
# Rule Title: The system must require passwords to contain at least one uppercase alphabetic character.
# Discussion: Requiring a minimum number of uppercase characters makes password guessing attacks more difficult by ensuring a larger search space.
# IA Controls:
# Check Content: To check how many uppercase characters are required in a password, run the following command:
#
# $ grep pam_cracklib /etc/pam.d/system-auth
#
# The "ucredit" parameter (as a negative number) will indicate how many uppercase characters are required. The DoD requires at least one uppercase character in a password. This would appear as "ucredit=-1".
# If ucredit is not found or not set to the required value, this is a finding.
# Fix Text: The pam_cracklib module's "ucredit=" parameter controls requirements for usage of uppercase letters in a password. When set to a negative number, any password will be required to contain that many uppercase characters. When set to a positive number, pam_cracklib will grant +1 additional length credit for each uppercase character. Add "ucredit=-1" after pam_cracklib.so to require use of an uppercase character in passwords.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000192
# The information system enforces password complexity by the minimum number of upper case characters used.
# NIST SP 800-53 :: IA-5 (1) (a)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (a)
#
#
- name: check stig_rhel6_v1r18 v_38569
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38569': 'fail'})}}"
  when: '"v_38569" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38570
# Severity: low
# Group Title: SRG-OS-000266
# Rule ID: SV-50371r1_rule
# STIG ID: RHEL-06-000058
# Rule Title: The system must require passwords to contain at least one special character.
# Discussion: Requiring a minimum number of special characters makes password guessing attacks more difficult by ensuring a larger search space.
# IA Controls:
# Check Content: To check how many special characters are required in a password, run the following command:
#
# $ grep pam_cracklib /etc/pam.d/system-auth
#
# The "ocredit" parameter (as a negative number) will indicate how many special characters are required. The DoD requires at least one special character in a password. This would appear as "ocredit=-1".
# If ocredit is not found or not set to the required value, this is a finding.
# Fix Text: The pam_cracklib module's "ocredit=" parameter controls requirements for usage of special (or ``other'') characters in a password. When set to a negative number, any password will be required to contain that many special characters. When set to a positive number, pam_cracklib will grant +1 additional length credit for each special character. Add "ocredit=-1" after pam_cracklib.so to require use of a special character in passwords.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001619
# The information system enforces password complexity by the minimum number of special characters used.
# NIST SP 800-53 :: IA-5 (1) (a)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (a)
#
#
- name: check stig_rhel6_v1r18 v_38570
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38570': 'fail'})}}"
  when: '"v_38570" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38571
# Severity: low
# Group Title: SRG-OS-000070
# Rule ID: SV-50372r2_rule
# STIG ID: RHEL-06-000059
# Rule Title: The system must require passwords to contain at least one lower-case alphabetic character.
# Discussion: Requiring a minimum number of lower-case characters makes password guessing attacks more difficult by ensuring a larger search space.
# IA Controls:
# Check Content: To check how many lower-case characters are required in a password, run the following command:
#
# $ grep pam_cracklib /etc/pam.d/system-auth
#
# The "lcredit" parameter (as a negative number) will indicate how many lower-case characters are required. The DoD requires at least one lower-case character in a password. This would appear as "lcredit=-1".
#
# If lcredit is not found or not set to the required value, this is a finding.
#
# Fix Text: The pam_cracklib module's "lcredit=" parameter controls requirements for usage of lower-case letters in a password. When set to a negative number, any password will be required to contain that many lower-case characters. Add "lcredit=-1" after pam_cracklib.so to require use of a lower-case character in passwords.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000193
# The information system enforces password complexity by the minimum number of lower case characters used.
# NIST SP 800-53 :: IA-5 (1) (a)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (a)
#
#
- name: check stig_rhel6_v1r18 v_38571
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38571': 'fail'})}}"
  when: '"v_38571" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38572
# Severity: low
# Group Title: SRG-OS-000072
# Rule ID: SV-50373r2_rule
# STIG ID: RHEL-06-000060
# Rule Title: The system must require at least eight characters be changed between the old and new passwords during a password change.
# Discussion: Requiring a minimum number of different characters during password changes ensures that newly changed passwords should not resemble previously compromised ones. Note that passwords which are changed on compromised systems will still be compromised, however.
# IA Controls:
# Check Content: To check how many characters must differ during a password change, run the following command:
#
# $ grep pam_cracklib /etc/pam.d/system-auth
#
# The "difok" parameter will indicate how many characters must differ. The DoD requires eight characters differ during a password change. This would appear as "difok=8".
#
# If difok is not found or not set to the required value, this is a finding.
# Fix Text: The pam_cracklib module's "difok" parameter controls requirements for usage of different characters during a password change. Add "difok=[NUM]" after pam_cracklib.so to require differing characters when changing passwords, substituting [NUM] appropriately. The DoD requirement is 8.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000195
# The information system, for password-based authentication, when new passwords are created, enforces that at least an organization-defined number of characters are changed.
# NIST SP 800-53 :: IA-5 (1) (b)
# NIST SP 800-53A :: IA-5 (1).1 (v)
# NIST SP 800-53 Revision 4 :: IA-5 (1) (b)
#
#
- name: check stig_rhel6_v1r18 v_38572
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38572': 'fail'})}}"
  when: '"v_38572" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38693
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50494r2_rule
# STIG ID: RHEL-06-000299
# Rule Title: The system must require passwords to contain no more than three consecutive repeating characters.
# Discussion: Passwords with excessive repeating characters may be more vulnerable to password-guessing attacks.
# IA Controls:
# Check Content: To check the maximum value for consecutive repeating characters, run the following command:
#
# $ grep pam_cracklib /etc/pam.d/system-auth
#
# Look for the value of the "maxrepeat" parameter. The DoD requirement is 3.
# If maxrepeat is not found or not set to the required value, this is a finding.
# Fix Text: The pam_cracklib module's "maxrepeat" parameter controls requirements for consecutive repeating characters. When set to a positive number, it will reject passwords which contain more than that number of consecutive characters. Add "maxrepeat=3" after pam_cracklib.so to prevent a run of (3 + 1) or more identical characters.
#
# password required pam_cracklib.so maxrepeat=3
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38693
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({'v_38693': 'fail'})}}"
  when: '"v_38693" in stig_rhel6_v1r18_checks'
