# Vuln ID: V-38656
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50457r1_rule
# STIG ID: RHEL-06-000272
# Rule Title: The system must use SMB client signing for connecting to samba servers using smbclient.
# Discussion: Packet signing can prevent man-in-the-middle attacks which modify SMB packets in transit.
# IA Controls:
# Check Content: To verify that Samba clients running smbclient must use packet signing, run the following command:
#
# # grep signing /etc/samba/smb.conf
#
# The output should show:
#
# client signing = mandatory
#
#
# If it is not, this is a finding.
# Fix Text: To require samba clients running "smbclient" to use packet signing, add the following to the "[global]" section of the Samba configuration file in "/etc/samba/smb.conf":
#
# client signing = mandatory
#
# Requiring samba clients such as "smbclient" to use packet signing ensures they can only communicate with servers that support packet signing.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38656
  set_fact: stig_rhel6_v1r18_results['v_38656'] = 'fail'
  when: '"v_38656" in stig_rhel6_v1r18_check_findings'


# Vuln ID: V-38657
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50458r2_rule
# STIG ID: RHEL-06-000273
# Rule Title: The system must use SMB client signing for connecting to samba servers using mount.cifs.
# Discussion: Packet signing can prevent man-in-the-middle attacks which modify SMB packets in transit.
# IA Controls:
# Check Content: If Samba is not in use, this is not applicable.
#
# To verify that Samba clients using mount.cifs must use packet signing, run the following command:
#
# # grep sec /etc/fstab /etc/mtab
#
# The output should show either "krb5i" or "ntlmv2i" in use.
# If it does not, this is a finding.
# Fix Text: Require packet signing of clients who mount Samba shares using the "mount.cifs" program (e.g., those who specify shares in "/etc/fstab"). To do so, ensure signing options (either "sec=krb5i" or "sec=ntlmv2i") are used.
#
# See the "mount.cifs(8)" man page for more information. A Samba client should only communicate with servers who can support SMB packet signing.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38657
  set_fact: stig_rhel6_v1r18_results['v_38657'] = 'fail'
  when: '"v_38657" in stig_rhel6_v1r18_check_findings'
