# Vuln ID: V-51363
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-65573r1_rule
# STIG ID: RHEL-06-000020
# Rule Title: The system must use a Linux Security Module configured to enforce limits on system services.
# Discussion: Setting the SELinux state to enforcing ensures SELinux is able to confine potentially compromised processes to the security policy, which is designed to prevent them from causing damage to the system or further elevating their privileges.
# IA Controls:
# Check Content: Check the file "/etc/selinux/config" and ensure the following line appears:
#
# SELINUX=enforcing
#
# If SELINUX is not set to enforcing, this is a finding.
# Fix Text: The SELinux state should be set to "enforcing" at system boot time. In the file "/etc/selinux/config", add or correct the following line to configure the system to boot into enforcing mode:
#
# SELINUX=enforcing
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_51363
  set_fact: stig_rhel6_v1r18_v_51363_result = 'fail'
  when: '"v_51363" in check_findings'


# Vuln ID: V-51369
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-65579r1_rule
# STIG ID: RHEL-06-000023
# Rule Title: The system must use a Linux Security Module configured to limit the privileges of system services.
# Discussion: Setting the SELinux policy to "targeted" or a more specialized policy ensures the system will confine processes that are likely to be targeted for exploitation, such as network or system services.
# IA Controls:
# Check Content: Check the file "/etc/selinux/config" and ensure the following line appears:
#
# SELINUXTYPE=targeted
#
# If it does not, this is a finding.
# Fix Text: The SELinux "targeted" policy is appropriate for general-purpose desktops and servers, as well as systems in many other roles. To configure the system to use this policy, add or correct the following line in "/etc/selinux/config":
#
# SELINUXTYPE=targeted
#
# Other policies, such as "mls", provide additional security labeling and greater confinement but are not compatible with many general-purpose use cases.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_51369
  set_fact: stig_rhel6_v1r18_v_51369_result = 'fail'
  when: '"v_51369" in check_findings'


# Vuln ID: V-51379
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-65589r1_rule
# STIG ID: RHEL-06-000025
# Rule Title: All device files must be monitored by the system Linux Security Module.
# Discussion: If a device file carries the SELinux type "unlabeled_t", then SELinux cannot properly restrict access to the device file.
# IA Controls:
# Check Content: To check for unlabeled device files, run the following command:
#
# # ls -RZ /dev | grep unlabeled_t
#
# It should produce no output in a well-configured system.
#
# If there is output, this is a finding.
# Fix Text: Device files, which are used for communication with important system resources, should be labeled with proper SELinux types. If any device files carry the SELinux type "unlabeled_t", investigate the cause and correct the file's context.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_51379
  set_fact: stig_rhel6_v1r18_v_51379_result = 'fail'
  when: '"v_51379" in check_findings'
