# Vuln ID: V-38653
# Severity: high
# Group Title: SRG-OS-999999
# Rule ID: SV-50454r1_rule
# STIG ID: RHEL-06-000341
# Rule Title: The snmpd service must not use a default password.
# Discussion: Presence of the default SNMP password enables querying of different system aspects and could result in unauthorized knowledge of the system.
# IA Controls:
# Check Content: To ensure the default password is not set, run the following command:
#
# # grep -v "^#" /etc/snmp/snmpd.conf| grep public
#
# There should be no output.
# If there is output, this is a finding.
# Fix Text: Edit "/etc/snmp/snmpd.conf", remove default community string "public". Upon doing that, restart the SNMP service:
#
# # service snmpd restart
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38653
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({v_38653: 'fail'})}}"
  when: '"v_38653" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38660
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-50461r1_rule
# STIG ID: RHEL-06-000340
# Rule Title: The snmpd service must use only SNMP protocol version 3 or newer.
# Discussion: Earlier versions of SNMP are considered insecure, as they potentially allow unauthorized access to detailed system management information.
#
# IA Controls:
# Check Content: To ensure only SNMPv3 or newer is used, run the following command:
#
# # grep 'v1\|v2c\|com2sec' /etc/snmp/snmpd.conf | grep -v '^#'
#
# There should be no output.
# If there is output, this is a finding.
# Fix Text: Edit "/etc/snmp/snmpd.conf", removing any references to "v1", "v2c", or "com2sec". Upon doing that, restart the SNMP service:
#
# # service snmpd restart
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel6_v1r18 v_38660
  set_fact:
    stig_rhel6_v1r18_results: "{{stig_rhel6_v1r18_results|combine({v_38660: 'fail'})}}"
  when: '"v_38660" in stig_rhel6_v1r18_checks'
