# Vuln ID: V-38599
# Severity: medium
# Group Title: SRG-OS-000023
# Rule ID: SV-50400r2_rule
# STIG ID: RHEL-06-000348
# Rule Title: The FTPS/FTP service on the system must be configured with the Department of Defense (DoD) login banner.
# Discussion: This setting will cause the system greeting banner to be used for FTP connections as well.
# IA Controls:
# Check Content: To verify this configuration, run the following command:
#
# grep "banner_file" /etc/vsftpd/vsftpd.conf
#
# The output should show the value of "banner_file" is set to "/etc/issue", an example of which is shown below.
#
# # grep "banner_file" /etc/vsftpd/vsftpd.conf
# banner_file=/etc/issue
#
#
# If it does not, this is a finding.
# Fix Text: Edit the vsftpd configuration file, which resides at "/etc/vsftpd/vsftpd.conf" by default. Add or correct the following configuration options.
#
# banner_file=/etc/issue
#
# Restart the vsftpd daemon.
#
# # service vsftpd restart
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000048
# The information system displays an organization-defined system use notification message or banner before granting access to the system that provides privacy and security notices consistent with applicable federal laws, Executive Orders, directives, policies, regulations, standards, and guidance.
# NIST SP 800-53 :: AC-8 a
# NIST SP 800-53A :: AC-8.1 (ii)
# NIST SP 800-53 Revision 4 :: AC-8 a
#
#
- name: check stig_rhel6_v1r18 v_38599
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38599: 'fail'})}}
  when: '"v_38599" in stig_rhel6_v1r18_checks'


# Vuln ID: V-38702
# Severity: low
# Group Title: SRG-OS-000037
# Rule ID: SV-50503r1_rule
# STIG ID: RHEL-06-000339
# Rule Title: The FTP daemon must be configured for logging or verbose mode.
# Discussion: To trace malicious activity facilitated by the FTP service, it must be configured to ensure that all commands sent to the ftp server are logged using the verbose vsftpd log format. The default vsftpd log file is /var/log/vsftpd.log.
# IA Controls:
# Check Content: Find if logging is applied to the ftp daemon.
#
# Procedures:
#
# If vsftpd is started by xinetd the following command will indicate the xinetd.d startup file.
#
# # grep vsftpd /etc/xinetd.d/*
#
#
#
# # grep server_args [vsftpd xinetd.d startup file]
#
# This will indicate the vsftpd config file used when starting through xinetd. If the [server_args]line is missing or does not include the vsftpd configuration file, then the default config file (/etc/vsftpd/vsftpd.conf) is used.
#
# # grep xferlog_enable [vsftpd config file]
#
#
# If xferlog_enable is missing, or is not set to yes, this is a finding.
# Fix Text: Add or correct the following configuration options within the "vsftpd" configuration file, located at "/etc/vsftpd/vsftpd.conf".
#
# xferlog_enable=YES
# xferlog_std_format=NO
# log_ftp_protocol=YES
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000130
# The information system generates audit records containing information that establishes what type of event occurred.
# NIST SP 800-53 :: AU-3
# NIST SP 800-53A :: AU-3.1
# NIST SP 800-53 Revision 4 :: AU-3
#
#
- name: check stig_rhel6_v1r18 v_38702
  set_fact:
    stig_rhel6_v1r18_results: '{{stig_rhel6_v1r18_results|combine({v_38702: 'fail'})}}
  when: '"v_38702" in stig_rhel6_v1r18_checks'
