- name: install packages
  yum:
      name: nfs-utils
      state: installed
  loop:
      - nfs-utils

- name: set up rpcbind service
  service:
      name: rpcbind
      enabled: yes
      state: started

- name: set up nfs service
  service:
      name: nfs
      enabled: yes
      state: started

- name: add firewall exception
  firewall_cmd_zone:
      service: nfs
      permanent: no
      state: present
  when: ansible_distribution_major_version == '7'

- name: add firewall exception
  firewall_cmd_zone:
      service: nfs
      state: present
  when: ansible_distribution_major_version == '7'

# TODO rhel6 firewall exception
