- name: forward zone
  template:
      src: templates/var/named/forward.zone
      dest: "/var/named/named.{{zone.forward}}"
      owner: root
      group: named
      mode: 0640
  notify:
      - check named config
      - restart named

- name: reverse zone
  template:
      src: templates/var/named/reverse.zone
      dest: "/var/named/named.{{zone.reverse}}"
      owner: root
      group: named
      mode: 0640
  notify:
      - check named config
      - restart named
