- name: template zone
  template:
      src: templates/var/named/named.zone
      dest: "/var/named/named.{{zone.name}}"
      owner: root
      group: named
      mode: 0640
  notify:
      - check named config
      - restart named
