- name: template zone
  template:
      src: templates/var/named/named.zone
      dest: "/var/named/dynamic/named.{{zone.name}}"
      owner: root
      group: named
      mode: 0640
  notify:
      - remove journal files
      - check named config
      - restart named
  when:
      - zone.type in ['master', 'slave']
