- name: parse /etc/fstab
  fstab_dump:
  register: fstab

# - name: fstab
#   debug:
#     msg: '{{fstab}}'

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72041 (SV-86665r3_rule)
- name: add nosuid to /home
  include_tasks: fstab-opt-present.yml
  vars:
    point: /home
    opt: nosuid

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72043 (SV-86667r1_rule)
- name: add nosuid to removable
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: nosuid
  with_items: "{{fstab}}"
  when:
      - item.fstype in fs_types_removable

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72045 (SV-86669r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38654 (SV-50455r2_rule)
- name: add nosuid to network
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: nosuid
  with_items: "{{fstab}}"
  when:
      - item.fstype in fs_types_network

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72311 (SV-86935r3_rule)
- name: add sec=krb5:krb5i:krb5p to nfs mounts
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: sec=krb5:krb5i:krb5p
  with_items: "{{fstab}}"
  when:
      - item.fstype in ['nfs', 'nfs4']

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-73161 (SV-87813r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38655 (SV-50456r1_rule)
- name: add noexec to network
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: noexec
  with_items: "{{fstab}}"
  when:
      - item.fstype in fs_types_network

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38652 (SV-50453r2_rule)
- name: add nodev to nfs mounts
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: nodev
  with_items: "{{fstab}}"
  when:
      - item.fstype in ['nfs', 'nfs4']

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-57569 (SV-71919r1_rule)
- name: add noexec to /tmp
  include_tasks: fstab-opt-present.yml
  vars:
    point: /tmp
    opt: noexec
