- name: parse /etc/fstab
  fstab_dump:
  register: fstab

- name: fstab
  debug:
    msg: '{{fstab}}'

- name: add nosuid to /home
  include_tasks: fstab-opt-present.yml
  vars:
    point: /home
    opt: nosuid

- name: add nosuid to removable
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: nosuid
  with_items: "{{fstab}}"
  when:
      - item.fstype in filesystems_types_removable

- name: add nosuid to network
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: nosuid
  with_items: "{{fstab}}"
  when:
      - item.fstype in filesystems_types_network

# NOTE: not sure this is a really good idea, despite STIG direction. This uses
# memory in RAM for /tmp instead of the hard drive. The intent of this would be
# speed, not security. The tmpfs could be grown to cause memory allocation
# failures
- name: enable (and start) tmp.mount
  systemd:
      name: tmp.mount
      enabled: yes
      state: started

- name: add sec=krb5:krb5i:krb5p to nfs mounts
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: sec=krb5:krb5i:krb5p
  with_items: "{{fstab}}"
  when:
      - item.fstype in ['nfs', 'nfs4']

- name: add noexec to network
  include_tasks: fstab-opt-present.yml
  vars:
    point: "{{item.mount_point}}"
    opt: noexec
  with_items: "{{fstab}}"
  when:
      - item.fstype in filesystems_types_network
