- name: disable, stop service
  service:
      name: ypserv
      enabled: no
      state: stopped

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71969 (SV-86593r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38603 (SV-50404r1_rule)
- name: remove package
  yum:
      name: ypserv
      state: absent
