- name: repo mount
  mount:
      src: "{{repo_server}}:{{repo_share}}"
      path: "{{repo_share}}"
      fstype: nfs
      opts: ro
      state: mounted

- name: repo link
  file:
      path: "/etc/yum.repos.d/{{repo_server}}.repo"
      src: "{{repo_share}}/{{repo_server}}.repo"
      state: link

- name: remove subscription-manager, rhn* pkags
  yum:
      name: "{{item}}"
      state: absent
  loop:
      - rhnsd
      - rhn-check
      - rhn-client-tools
      - rhn-setup
      - rhnlib
      - subscription-manager
      - yum-rhn-plugin

- name: trust distro key
  rpm_key:
      key: "{{distribution_key_file}}"
      state: present
