### Constants; probably shouldn't be overriden


### Variables; could be overriden depending on environment

audit_log_file: /var/log/audit/audit.log

#audit_space_left is calculated

audit_space_left_action: email

audit_action_mail_acct: "{{email_notifications}}"

audit_log_group: root

# Compliance requires "syslog", "exec", "single", or "halt"
audit_disk_error_action: syslog

# Compliance requires syslog, single, or halt
audit_disk_full_action: syslog

# Compliance requires at least 6. 8 is RHEL7 default
audit_max_log_file: 8

audit_write_logs: 'yes'

audit_max_log_file_action: rotate

audit_num_logs: 5

# Compliance requires single, suspend, halt
audit_admin_space_left_action: single

# Set to 0640 if the group needs to read the file. This is automatic if
# audit_log_group is something other than root
audit_log_file_mode: 0600

# Set to 0750 if the group needs to access the dir
audit_log_dir_mode: 0700

### audisp

audisp_remote_server: "{{log_aggregation_server}}"

# Compliance requires yes
audisp_enable_krb5: 'yes'

# Compliance requires syslog, single, or halt
audisp_disk_full_action: syslog

# Compliance requires syslog, single, or halt
audisp_network_failure_action: syslog
