# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71983 (SV-86607r2_rule)
- name: blacklist usb-storage
  lineinfile:
      path: /etc/modprobe.d/stig-blacklist
      line: "blacklist {{item}}"
      state: present
      create: yes
  loop:
      - usb-storage
      - dccp
      - dccp_diag
      - dccp_ipv4
      - dccp_ipv6
      - sctp
      - rds
      - tipc
      - bluetooth
      - net-pf-31

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-77821 (SV-92517r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38490 (SV-50291r6_rule)
# V-38514 (SV-50315r5_rule)
# V-38515 (SV-50316r5_rule)
# V-38516 (SV-50317r3_rule)
# V-38517 (SV-50318r5_rule)
# V-38682 (SV-50483r5_rule)
- name: prevent module installation
  lineinfile:
      path: /etc/modprobe.d/stig
      line: "install {{item}} /bin/true"
      state: present
      create: yes
  loop:
      - usb-storage
      - dccp
      - dccp_diag
      - dccp_ipv4
      - dccp_ipv6
      - sctp
      - rds
      - tipc
      - bluetooth
      - net-pf-31
