# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38603 (SV-50404r1_rule)
# V-38671 (SV-50472r1_rule)
- name: remove prohibited packages
  yum:
      name: "{{item}}"
      state: absent
  loop:
      - sendmail

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38627 (SV-50428r2_rule)
- name: remove openldap-servers
  yum:
      name: openldap-servers
      state: absent
  when: not is_ldap_server
