- name: firewalld is installed
  yum:
      name: firewalld
      state: present

- name: firewalld is running
  service:
      name: firewalld.service
      enabled: yes
      state: started

- name: zones
  firewall_cmd_zone:
      name: "{{item}}"
      state: exists
  with_items: "{{ firewalld_zone_names }}"
