- name: firewalld is installed
  yum:
      name: firewalld
      state: present

- name: firewalld is running
  service:
      name: firewalld.service
      enabled: yes
      state: started

- name: get firewall state
  firewall_cmd:
      state: get
  register: firewalld_state

- debug:
    msg: "{{firewalld_state}}"

- name: add missing zones
  firewall_cmd_zone:
      name: "{{item}}"
      state: present
  with_items: "{{ firewalld_zone_names }}"

- name: remove extra zones
  firewall_cmd_zone:
      name: "{{item}}"
      state: absent
  with_items: "{{ firewalld_state['firewalld']['permanent_zones'].keys() | difference(firewalld_zone_names) }}"

- name: reload firewall from permanent
  firewall_cmd:
      state: reload
