- debug:
    msg: "Setting {{firewalld_zone}} with {{firewalld_zone_configs[firewalld_zone]}}"

- name: add forward_ports
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      forward_port: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['forward_ports']}}"

- name: remove forward_ports
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      forward_port: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['forward_ports'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['forward_ports']) }}"

- name: set icmp_block_inversion
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      icmp_block_inversion: "{{firewalld_zone_configs[firewalld_zone]['icmp_block_inversion']}}"

- name: add icmp_blocks
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      icmp_block: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['icmp_blocks']}}"

- name: remove icmp_blocks
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      icmp_block: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['icmp_blocks'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['icmp_blocks']) }}"

# - name: add interfaces
#   firewall_cmd_zone:
#       name: "{{firewalld_zone}}"
#       interface: "{{item}}"
#       state: present
#   with_items: "{{firewalld_zone_configs[firewalld_zone]['interfaces']}}"
#
# - name: remove interfaces
#   firewall_cmd_zone:
#       name: "{{firewalld_zone}}"
#       interface: "{{item}}"
#       state: absent
#   with_items: "{{ firewalld_zone_configs[firewalld_zone]['interfaces'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['interfaces']) }}"

- name: set masquerade
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      masquerade: "{{firewalld_zone_configs[firewalld_zone]['masquerade']}}"

- name: add ports
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      port: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['ports']}}"

- name: remove ports
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      port: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['ports'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['ports']) }}"

- name: add protocols
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      protocol: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['protocols']}}"

- name: remove protocols
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      protocol: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['protocols'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['protocols']) }}"

- name: add rich_rules
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      rich_rule: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['rich_rules']}}"

- name: remove rich_rules
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      rich_rule: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['rich_rules'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['rich_rules']) }}"

- name: add services
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      service: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['services']}}"

- name: remove services
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      service: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['services'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['services']) }}"

- name: add source_ports
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      source_port: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['source_ports']}}"

- name: remove source_ports
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      source_port: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['source_ports'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['source_ports']) }}"

- name: add sources
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      source: "{{item}}"
      state: present
  with_items: "{{firewalld_zone_configs[firewalld_zone]['sources']}}"

- name: remove sources
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      source: "{{item}}"
      state: absent
  with_items: "{{ firewalld_zone_configs[firewalld_zone]['sources'] | difference(firewalld_state['firewalld']['permanent_zones'][firewalld_zone]['sources']) }}"

- name: set target
  firewall_cmd_zone:
      name: "{{firewalld_zone}}"
      target: "{{firewalld_zone_configs[firewalld_zone]['target']}}"
