# Vuln ID: V-72083
# Severity: medium
# Group Title: SRG-OS-000342-GPOS-00133
# Rule ID: SV-86707r1_rule
# STIG ID: RHEL-07-030300
# Rule Title: The operating system must off-load audit records onto a different system or media from the system being audited.
# Discussion: Information stored in one location is vulnerable to accidental or incidental deletion or alteration.
#
# Off-loading is a common process in information systems with limited audit storage capacity.
#
# Satisfies: SRG-OS-000342-GPOS-00133, SRG-OS-000479-GPOS-00224
# IA Controls:
# Check Content: Verify the operating system off-loads audit records onto a different system or media from the system being audited.
#
# To determine the remote server that the records are being sent to, use the following command:
#
# # grep -i remote_server /etc/audisp/audisp-remote.conf
# remote_server = 10.0.21.1
#
# If a remote server is not configured, or the line is commented out, ask the System Administrator to indicate how the audit logs are off-loaded to a different system or media.
#
# If there is no evidence that the audit logs are being off-loaded to another system or media, this is a finding.
# Fix Text: Configure the operating system to off-load audit records onto a different system or media from the system being audited.
#
# Set the remote server option in "/etc/audisp/audisp-remote.conf" with the IP address of the log aggregation server.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001851
# The information system off-loads audit records per organization-defined frequency onto a different system or media than the system being audited.
# NIST SP 800-53 Revision 4 :: AU-4 (1)
#
#
- name: check stig_rhel7_v1r4 v_72083
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_72083: 'fail'})}}
  when: '"v_72083" in stig_rhel7_v1r4_checks'


# Vuln ID: V-72085
# Severity: medium
# Group Title: SRG-OS-000342-GPOS-00133
# Rule ID: SV-86709r1_rule
# STIG ID: RHEL-07-030310
# Rule Title: The operating system must encrypt the transfer of audit records off-loaded onto a different system or media from the system being audited.
# Discussion: Information stored in one location is vulnerable to accidental or incidental deletion or alteration.
#
# Off-loading is a common process in information systems with limited audit storage capacity.
#
# Satisfies: SRG-OS-000342-GPOS-00133, SRG-OS-000479-GPOS-00224
# IA Controls:
# Check Content: Verify the operating system encrypts audit records off-loaded onto a different system or media from the system being audited.
#
# To determine if the transfer is encrypted, use the following command:
#
# # grep -i enable_krb5 /etc/audisp/audisp-remote.conf
# enable_krb5 = yes
#
# If the value of the "enable_krb5" option is not set to "yes" or the line is commented out, ask the System Administrator to indicate how the audit logs are off-loaded to a different system or media.
#
# If there is no evidence that the transfer of the audit logs being off-loaded to another system or media is encrypted, this is a finding.
# Fix Text: Configure the operating system to encrypt the transfer of off-loaded audit records onto a different system or media from the system being audited.
#
# Uncomment the "enable_krb5" option in "/etc/audisp/audisp-remote.conf" and set it with the following line:
#
# enable_krb5 = yes
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001851
# The information system off-loads audit records per organization-defined frequency onto a different system or media than the system being audited.
# NIST SP 800-53 Revision 4 :: AU-4 (1)
#
#
- name: check stig_rhel7_v1r4 v_72085
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_72085: 'fail'})}}
  when: '"v_72085" in stig_rhel7_v1r4_checks'


# Vuln ID: V-72087
# Severity: medium
# Group Title: SRG-OS-000342-GPOS-00133
# Rule ID: SV-86711r2_rule
# STIG ID: RHEL-07-030320
# Rule Title: The audit system must take appropriate action when the audit storage volume is full.
# Discussion: Taking appropriate action in case of a filled audit storage volume will minimize the possibility of losing audit records.
# IA Controls:
# Check Content: Verify the action the operating system takes if the disk the audit records are written to becomes full.
#
# To determine the action that takes place if the disk is full on the remote server, use the following command:
#
# # grep -i disk_full_action /etc/audisp/audisp-remote.conf
# disk_full_action = single
#
# To determine the action that takes place if the network connection fails, use the following command:
#
# # grep -i network_failure_action /etc/audisp/audisp-remote.conf
# network_failure_action = stop
#
# If the value of the "network_failure_action" option is not "syslog", "single", or "halt", or the line is commented out, this is a finding.
#
# If the value of the "disk_full_action" option is not "syslog", "single", or "halt", or the line is commented out, this is a finding.
# Fix Text: Configure the action the operating system takes if the disk the audit records are written to becomes full.
#
# Uncomment or edit the "disk_full_action" option in "/etc/audisp/audisp-remote.conf" and set it to "syslog", "single", or "halt", such as the following line:
#
# disk_full_action = single
#
# Uncomment the "network_failure_action" option in "/etc/audisp/audisp-remote.conf" and set it to "syslog", "single", or "halt".
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001851
# The information system off-loads audit records per organization-defined frequency onto a different system or media than the system being audited.
# NIST SP 800-53 Revision 4 :: AU-4 (1)
#
#
- name: check stig_rhel7_v1r4 v_72087
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_72087: 'fail'})}}
  when: '"v_72087" in stig_rhel7_v1r4_checks'


# Vuln ID: V-73163
# Severity: medium
# Group Title: SRG-OS-000342-GPOS-00133
# Rule ID: SV-87815r2_rule
# STIG ID: RHEL-07-030321
# Rule Title: The audit system must take appropriate action when there is an error sending audit records to a remote system.
# Discussion: Taking appropriate action when there is an error sending audit records to a remote system will minimize the possibility of losing audit records.
# IA Controls:
# Check Content: Verify the action the operating system takes if there is an error sending audit records to a remote system.
#
# Check the action that takes place if there is an error sending audit records to a remote system with the following command:
#
# # grep -i network_failure_action /etc/audisp/audisp-remote.conf
# network_failure_action = stop
#
# If the value of the "network_failure_action" option is not "syslog", "single", or "halt", or the line is commented out, this is a finding.
# Fix Text: Configure the action the operating system takes if there is an error sending audit records to a remote system.
#
# Uncomment the "network_failure_action" option in "/etc/audisp/audisp-remote.conf" and set it to "syslog", "single", or "halt".
#
# network_failure_action = single
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001851
# The information system off-loads audit records per organization-defined frequency onto a different system or media than the system being audited.
# NIST SP 800-53 Revision 4 :: AU-4 (1)
#
#
- name: check stig_rhel7_v1r4 v_73163
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_73163: 'fail'})}}
  when: '"v_73163" in stig_rhel7_v1r4_checks'
