# Vuln ID: V-72079
# Severity: high
# Group Title: SRG-OS-000038-GPOS-00016
# Rule ID: SV-86703r2_rule
# STIG ID: RHEL-07-030000
# Rule Title: Auditing must be configured to produce records containing information to establish what type of events occurred, where the events occurred, the source of the events, and the outcome of the events.
#
# These audit records must also identify individual identities of group account users.
# Discussion: Without establishing what type of events occurred, it would be difficult to establish, correlate, and investigate the events leading up to an outage or attack.
#
# Audit record content that may be necessary to satisfy this requirement includes, for example, time stamps, source and destination addresses, user/process identifiers, event descriptions, success/fail indications, filenames involved, and access control or flow control rules invoked.
#
# Associating event types with detected events in the operating system audit logs provides a means of investigating an attack; recognizing resource utilization or capacity thresholds; or identifying an improperly configured operating system.
#
# Satisfies: SRG-OS-000038-GPOS-00016, SRG-OS-000039-GPOS-00017, SRG-OS-000042-GPOS-00021, SRG-OS-000254-GPOS-00095, SRG-OS-000255-GPOS-00096
# IA Controls:
# Check Content: Verify the operating system produces audit records containing information to establish when (date and time) the events occurred.
#
# Check to see if auditing is active by issuing the following command:
#
# # systemctl is-active auditd.service
# Active: active (running) since Tue 2015-01-27 19:41:23 EST; 22h ago
#
# If the "auditd" status is not active, this is a finding.
# Fix Text: Configure the operating system to produce audit records containing information to establish when (date and time) the events occurred.
#
# Enable the auditd service with the following command:
#
# # systemctl start auditd.service
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000126
# The organization determines that the organization-defined subset of the auditable events defined in AU-2 are to be audited within the information system.
# NIST SP 800-53 :: AU-2 d
# NIST SP 800-53A :: AU-2.1 (v)
# NIST SP 800-53 Revision 4 :: AU-2 d
#
# CCI-000131
# The information system generates audit records containing information that establishes when an event occurred.
# NIST SP 800-53 :: AU-3
# NIST SP 800-53A :: AU-3.1
# NIST SP 800-53 Revision 4 :: AU-3
#
#
- name: check stig_rhel7_v1r4 v_72079
  set_fact:
    stig_rhel7_v1r4_results: "{{stig_rhel7_v1r4_results|combine({v_72079: 'fail'})}}"
  when: '"v_72079" in stig_rhel7_v1r4_checks'


# Vuln ID: V-72089
# Severity: medium
# Group Title: SRG-OS-000343-GPOS-00134
# Rule ID: SV-86713r1_rule
# STIG ID: RHEL-07-030330
# Rule Title: The operating system must immediately notify the System Administrator (SA) and Information System Security Officer ISSO (at a minimum) when allocated audit record storage volume reaches 75% of the repository maximum audit record storage capacity.
# Discussion: If security personnel are not notified immediately when storage volume reaches 75 percent utilization, they are unable to plan for audit record storage capacity expansion.
# IA Controls:
# Check Content: Verify the operating system immediately notifies the SA and ISSO (at a minimum) when allocated audit record storage volume reaches 75 percent of the repository maximum audit record storage capacity.
#
# Check the system configuration to determine the partition the audit records are being written to with the following command:
#
# # grep log_file /etc/audit/auditd.conf
# log_file = /var/log/audit/audit.log
#
# Check the size of the partition that audit records are written to (with the example being "/var/log/audit/"):
#
# # df -h /var/log/audit/
# 0.9G /var/log/audit
#
# If the audit records are not being written to a partition specifically created for audit records (in this example "/var/log/audit" is a separate partition), determine the amount of space other files in the partition are currently occupying with the following command:
#
# # du -sh <partition>
# 1.8G /var
#
# Determine what the threshold is for the system to take action when 75 percent of the repository maximum audit record storage capacity is reached:
#
# # grep -i space_left /etc/audit/auditd.conf
# space_left = 225
#
# If the value of the "space_left" keyword is not set to 25 percent of the total partition size, this is a finding.
# Fix Text: Configure the operating system to immediately notify the SA and ISSO (at a minimum) when allocated audit record storage volume reaches 75 percent of the repository maximum audit record storage capacity.
#
# Check the system configuration to determine the partition the audit records are being written to:
#
# # grep log_file /etc/audit/auditd.conf
#
# Determine the size of the partition that audit records are written to (with the example being "/var/log/audit/"):
#
# # df -h /var/log/audit/
#
# Set the value of the "space_left" keyword in "/etc/audit/auditd.conf" to 75 percent of the partition size.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001855
# The information system provides a warning to organization-defined personnel, roles, and/or locations within organization-defined time period when allocated audit record storage volume reaches organization-defined percentage of repository maximum audit record storage capacity.
# NIST SP 800-53 Revision 4 :: AU-5 (1)
#
#
- name: check stig_rhel7_v1r4 v_72089
  set_fact:
    stig_rhel7_v1r4_results: "{{stig_rhel7_v1r4_results|combine({v_72089: 'fail'})}}"
  when: '"v_72089" in stig_rhel7_v1r4_checks'


# Vuln ID: V-72091
# Severity: medium
# Group Title: SRG-OS-000343-GPOS-00134
# Rule ID: SV-86715r1_rule
# STIG ID: RHEL-07-030340
# Rule Title: The operating system must immediately notify the System Administrator (SA) and Information System Security Officer (ISSO) (at a minimum) via email when the threshold for the repository maximum audit record storage capacity is reached.
# Discussion: If security personnel are not notified immediately when the threshold for the repository maximum audit record storage capacity is reached, they are unable to expand the audit record storage capacity before records are lost.
# IA Controls:
# Check Content: Verify the operating system immediately notifies the SA and ISSO (at a minimum) via email when the allocated audit record storage volume reaches 75 percent of the repository maximum audit record storage capacity.
#
# Check what action the operating system takes when the threshold for the repository maximum audit record storage capacity is reached with the following command:
#
# # grep -i space_left_action  /etc/audit/auditd.conf
# space_left_action = email
#
# If the value of the "space_left_action" keyword is not set to "email", this is a finding.
# Fix Text: Configure the operating system to immediately notify the SA and ISSO (at a minimum) when the threshold for the repository maximum audit record storage capacity is reached.
#
# Uncomment or edit the "space_left_action" keyword in "/etc/audit/auditd.conf" and set it to "email".
#
# space_left_action = email
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001855
# The information system provides a warning to organization-defined personnel, roles, and/or locations within organization-defined time period when allocated audit record storage volume reaches organization-defined percentage of repository maximum audit record storage capacity.
# NIST SP 800-53 Revision 4 :: AU-5 (1)
#
#
- name: check stig_rhel7_v1r4 v_72091
  set_fact:
    stig_rhel7_v1r4_results: "{{stig_rhel7_v1r4_results|combine({v_72091: 'fail'})}}"
  when: '"v_72091" in stig_rhel7_v1r4_checks'


# Vuln ID: V-72093
# Severity: medium
# Group Title: SRG-OS-000343-GPOS-00134
# Rule ID: SV-86717r2_rule
# STIG ID: RHEL-07-030350
# Rule Title: The operating system must immediately notify the System Administrator (SA) and Information System Security Officer (ISSO) (at a minimum) when the threshold for the repository maximum audit record storage capacity is reached.
# Discussion: If security personnel are not notified immediately when the threshold for the repository maximum audit record storage capacity is reached, they are unable to expand the audit record storage capacity before records are lost.
# IA Controls:
# Check Content: Verify the operating system immediately notifies the SA and ISSO (at a minimum) via email when the threshold for the repository maximum audit record storage capacity is reached.
#
# Check what account the operating system emails when the threshold for the repository maximum audit record storage capacity is reached with the following command:
#
# # grep -i action_mail_acct  /etc/audit/auditd.conf
# action_mail_acct = root
#
# If the value of the "action_mail_acct" keyword is not set to "root" and other accounts for security personnel, this is a finding.
# Fix Text: Configure the operating system to immediately notify the SA and ISSO (at a minimum) when the threshold for the repository maximum audit record storage capacity is reached.
#
# Uncomment or edit the "action_mail_acct" keyword in "/etc/audit/auditd.conf" and set it to root and any other accounts associated with security personnel.
#
# action_mail_acct = root
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-001855
# The information system provides a warning to organization-defined personnel, roles, and/or locations within organization-defined time period when allocated audit record storage volume reaches organization-defined percentage of repository maximum audit record storage capacity.
# NIST SP 800-53 Revision 4 :: AU-5 (1)
#
#
- name: check stig_rhel7_v1r4 v_72093
  set_fact:
    stig_rhel7_v1r4_results: "{{stig_rhel7_v1r4_results|combine({v_72093: 'fail'})}}"
  when: '"v_72093" in stig_rhel7_v1r4_checks'
