- name: systemctl status firewalld
  shell: systemctl status firewalld || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: systemctl_status_firewalld

- set_fact:
    firewalld_active: true
  when:
      - "'Loaded: loaded' in systemctl_status_firewalld.stdout"
      - "'Active: active (running)' in systemctl_status_firewalld.stdout"
      - not systemctl_status_firewalld.failed

- set_fact:
    firewalld_active: false
  when:
      - not firewalld_active

- name: firewalld_active
  debug:
    msg: '{{firewalld_active}}'
  when:
      - not systemctl_status_firewalld.failed

- name: firewall-cmd --state
  shell: firewall-cmd --state || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: firewalld_state

- set_fact:
    firewalld_running: true
  when:
      - "'running' in firewalld_state.stdout"
      - not firewalld_state.failed

- set_fact:
    firewalld_running: false
  when:
      - not firewalld_running

- name: firewall-cmd --get-default-zone
  shell: firewall-cmd --get-default-zone || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: firewalld_get_default_zone
  when:
    - firewalld_active
    - firewalld_running

- set_fact:
    firewalld_get_default_zone: "{{firewalld_get_default_zone.stdout}}"
  when:
    - firewalld_active
    - firewalld_running

- name: firewall-cmd --get-zones
  shell: firewall-cmd --get-zones || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: firewalld_get_zones
  when:
    - firewalld_active
    - firewalld_running

- name: split zones
  set_fact:
      firewalld_get_zones: "{{firewalld_get_zones.stdout.split(' ')}}"
  when:
    - firewalld_active
    - firewalld_running

- debug:
    msg: "{{firewalld_get_zones}}"
  when:
    - firewalld_active
    - firewalld_running

- name: firewall-cmd --info-zone {{item}}
  shell: firewall-cmd --info-zone {{item}} || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: firewalld_info_zones
  with_items: "{{firewalld_get_zones}}"
  when:
    - firewalld_active
    - firewalld_running

- debug:
    msg: "{{ item|map(attribute='stdout')|string|parse_cli_textfsm('textfsm_templates/firewall-cmd_info_zone') }}"
  with_items:
      firewalld_info_zones
  when:
    - firewalld_active
    - firewalld_running

# Vuln ID: V-72219
# Severity: medium
# Group Title: SRG-OS-000096-GPOS-00050
# Rule ID: SV-86843r1_rule
# STIG ID: RHEL-07-040100
# Rule Title: The host must be configured to prohibit or restrict the use of functions, ports, protocols, and/or services, as defined in the Ports, Protocols, and Services Management Component Local Service Assessment (PPSM CLSA) and vulnerability assessments.
# Discussion: In order to prevent unauthorized connection of devices, unauthorized transfer of information, or unauthorized tunneling (i.e., embedding of data types within data types), organizations must disable or restrict unused or unnecessary physical and logical ports/protocols on information systems.
#
# Operating systems are capable of providing a wide variety of functions and services. Some of the functions and services provided by default may not be necessary to support essential organizational operations. Additionally, it is sometimes convenient to provide multiple services from a single component (e.g., VPN and IPS); however, doing so increases risk over limiting the services provided by any one component.
#
# To support the requirements and principles of least functionality, the operating system must support the organizational requirements, providing only essential capabilities and limiting the use of ports, protocols, and/or services to only those required, authorized, and approved to conduct official business or to address authorized quality of life issues.
#
# Satisfies: SRG-OS-000096-GPOS-00050, SRG-OS-000297-GPOS-00115
# IA Controls:
# Check Content: Inspect the firewall configuration and running services to verify that it is configured to prohibit or restrict the use of functions, ports, protocols, and/or services that are unnecessary or prohibited.
#
# Check which services are currently active with the following command:
#
# # firewall-cmd --list-all
# public (default, active)
#   interfaces: enp0s3
#   sources:
#   services: dhcpv6-client dns http https ldaps rpc-bind ssh
#   ports:
#   masquerade: no
#   forward-ports:
#   icmp-blocks:
#   rich rules:
#
# Ask the System Administrator for the site or program PPSM CLSA. Verify the services allowed by the firewall match the PPSM CLSA.
#
# If there are additional ports, protocols, or services that are not in the PPSM CLSA, or there are ports, protocols, or services that are prohibited by the PPSM Category Assurance List (CAL), this is a finding.
# Fix Text: Update the host's firewall settings and/or running services to comply with the PPSM CLSA for the site or program and the PPSM CAL.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000382
# The organization configures the information system to prohibit or restrict the use of organization defined functions, ports, protocols, and/or services.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (iii)
# NIST SP 800-53 Revision 4 :: CM-7 b
#
# CCI-002314
# The information system controls remote access methods.
# NIST SP 800-53 Revision 4 :: AC-17 (1)
#
#


- name: fail stig_rhel7_v1r4 v_72219
  set_fact:
    stig_rhel7_v1r4_v_72219_result: 'fail'
  when:
    - "'v_72219' in stig_rhel7_v1r4_checks"
    - stig_rhel7_v1r4_v_72219_result != 'pass'


# Vuln ID: V-72271
# Severity: medium
# Group Title: SRG-OS-000420-GPOS-00186
# Rule ID: SV-86895r2_rule
# STIG ID: RHEL-07-040510
# Rule Title: The operating system must protect against or limit the effects of Denial of Service (DoS) attacks by validating the operating system is implementing rate-limiting measures on impacted network interfaces.
# Discussion: DoS is a condition when a resource is not available for legitimate users. When this occurs, the organization either cannot accomplish its mission or must operate at degraded capacity.
#
# This requirement addresses the configuration of the operating system to mitigate the impact of DoS attacks that have occurred or are ongoing on system availability. For each system, known and potential DoS attacks must be identified and solutions for each type implemented. A variety of technologies exist to limit or, in some cases, eliminate the effects of DoS attacks (e.g., limiting processes or establishing memory partitions). Employing increased capacity and bandwidth, combined with service redundancy, may reduce the susceptibility to some DoS attacks.
# IA Controls:
# Check Content: Verify the operating system protects against or limits the effects of DoS attacks by ensuring the operating system is implementing rate-limiting measures on impacted network interfaces.
#
# Check the firewall configuration with the following command:
#
# Note: The command is to query rules for the public zone.
#
# # firewall-cmd --direct --get-rule ipv4 filter IN_public_allow
# rule ipv4 filter IN_public_allow 0 -p tcp -m limit --limit 25/minute --limit-burst 100  -j ACCEPT
#
# If a rule with both the limit and limit-burst arguments parameters does not exist, this is a finding.
# Fix Text: Create a direct firewall rule to protect against DoS attacks with the following command:
#
# Note: The command is to add a rule to the public zone.
#
# # firewall-cmd --direct --permanent --add-rule ipv4 filter IN_public_allow 0 -m tcp -p tcp -m limit --limit 25/minute --limit-burst 100 -j ACCEPT
#
# The firewalld service will need to be restarted for this to take effect:
#
# # systemctl restart firewalld
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-002385
# The information system protects against or limits the effects of organization-defined types of denial of service attacks by employing organization-defined security safeguards.
# NIST SP 800-53 Revision 4 :: SC-5
#
#
# - name: fail stig_rhel7_v1r4 v_72271
#   set_fact:
#     stig_rhel7_v1r4_v_72271_result: 'fail'
#   when:
#     - "'v_72271' in stig_rhel7_v1r4_checks"
#     - stig_rhel7_v1r4_v_72271_result != 'pass'


# Vuln ID: V-72273
# Severity: medium
# Group Title: SRG-OS-000480-GPOS-00227
# Rule ID: SV-86897r1_rule
# STIG ID: RHEL-07-040520
# Rule Title: The operating system must enable an application firewall, if available.
# Discussion: Firewalls protect computers from network attacks by blocking or limiting access to open network ports. Application firewalls limit which applications are allowed to communicate over the network.
#
# Satisfies: SRG-OS-000480-GPOS-00227, SRG-OS-000480-GPOS-00231, SRG-OS-000480-GPOS-00232
# IA Controls:
# Check Content: Verify the operating system enabled an application firewall.
#
# Check to see if "firewalld" is installed with the following command:
#
# # yum list installed firewalld
# firewalld-0.3.9-11.el7.noarch.rpm
#
# If the "firewalld" package is not installed, ask the System Administrator if another firewall application (such as iptables) is installed.
#
# If an application firewall is not installed, this is a finding.
#
# Check to see if the firewall is loaded and active with the following command:
#
# # systemctl status firewalld
# firewalld.service - firewalld - dynamic firewall daemon
#
#    Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled)
#    Active: active (running) since Tue 2014-06-17 11:14:49 CEST; 5 days ago
#
# If "firewalld" does not show a status of "loaded" and "active", this is a finding.
#
# Check the state of the firewall:
#
# # firewall-cmd --state
# running
#
# If "firewalld" does not show a state of "running", this is a finding.
# Fix Text: Ensure the operating system's application firewall is enabled.
#
# Install the "firewalld" package, if it is not on the system, with the following command:
#
# # yum install firewalld
#
# Start the firewall via "systemctl" with the following command:
#
# # systemctl start firewalld
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
# - name: fail stig_rhel7_v1r4 v_72273
#   set_fact:
#     stig_rhel7_v1r4_v_72273_result: 'fail'
#   when:
#     - "'v_72273' in stig_rhel7_v1r4_checks"
#     - stig_rhel7_v1r4_v_72273_result != 'pass'


# Vuln ID: V-72315
# Severity: medium
# Group Title: SRG-OS-000480-GPOS-00227
# Rule ID: SV-86939r2_rule
# STIG ID: RHEL-07-040810
# Rule Title: The system access control program must be configured to grant or deny system access to specific hosts and services.
# Discussion: If the systems access control program is not configured with appropriate rules for allowing and denying access to system network resources, services may be accessible to unauthorized hosts.
# IA Controls:
# Check Content: If the "firewalld" package is not installed, ask the System Administrator (SA) if another firewall application (such as iptables) is installed. If an application firewall is not installed, this is a finding.
#
# Verify the system's access control program is configured to grant or deny system access to specific hosts.
#
# Check to see if "firewalld" is active with the following command:
#
# # systemctl status firewalld
# firewalld.service - firewalld - dynamic firewall daemon
#    Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled)
#    Active: active (running) since Sun 2014-04-20 14:06:46 BST; 30s ago
#
# If "firewalld" is active, check to see if it is configured to grant or deny access to specific hosts or services with the following commands:
#
# # firewall-cmd --get-default-zone
# public
#
# # firewall-cmd --list-all --zone=public
# public (default, active)
#   interfaces: eth0
#   sources:
#   services: mdns ssh
#   ports:
#   masquerade: no
#   forward-ports:
#   icmp-blocks:
#   rich rules:
#  rule family="ipv4" source address="92.188.21.1/24" accept
#  rule family="ipv4" source address="211.17.142.46/32" accept
#
# If "firewalld" is not active, determine whether "tcpwrappers" is being used by checking whether the "hosts.allow" and "hosts.deny" files are empty with the following commands:
#
# # ls -al /etc/hosts.allow
# rw-r----- 1 root root 9 Aug  2 23:13 /etc/hosts.allow
#
# # ls -al /etc/hosts.deny
# -rw-r----- 1 root root  9 Apr  9  2007 /etc/hosts.deny
#
# If "firewalld" and "tcpwrappers" are not installed, configured, and active, ask the SA if another access control program (such as iptables) is installed and active. Ask the SA to show that the running configuration grants or denies access to specific hosts or services.
#
# If "firewalld" is active and is not configured to grant access to specific hosts or "tcpwrappers" is not configured to grant or deny access to specific hosts, this is a finding.
# Fix Text: If "firewalld" is installed and active on the system, configure rules for allowing specific services and hosts.
#
# If "firewalld" is not "active", enable "tcpwrappers" by configuring "/etc/hosts.allow" and "/etc/hosts.deny" to allow or deny access to specific hosts.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: pass stig_rhel7_v1r4 v_72315
  set_fact:
    stig_rhel7_v1r4_v_72315_result: 'pass'
  when:
    - "'v_72315' in stig_rhel7_v1r4_checks"
    - firewalld_active
    - firewalld_running

- name: fail stig_rhel7_v1r4 v_72315
  set_fact:
    stig_rhel7_v1r4_v_72315_result: 'fail'
  when:
    - "'v_72315' in stig_rhel7_v1r4_checks"
    - stig_rhel7_v1r4_v_72315_result != 'pass'
