# Vuln ID: V-71961
# Severity: high
# Group Title: SRG-OS-000080-GPOS-00048
# Rule ID: SV-86585r4_rule
# STIG ID: RHEL-07-010480
# Rule Title: Systems with a Basic Input/Output System (BIOS) must require authentication upon booting into single-user and maintenance modes.
# Discussion: If the system does not require valid root authentication before it boots into single-user or maintenance mode, anyone who invokes single-user or maintenance mode is granted privileged access to all files on the system. GRUB 2 is the default boot loader for RHEL 7 and is designed to require a password to boot into single-user mode or make modifications to the boot menu.
# IA Controls:
# Check Content: For systems that use UEFI, this is Not Applicable.
#
# Check to see if an encrypted root password is set. On systems that use a BIOS, use the following command:
#
# # grep -i ^password_pbkdf2 /boot/grub2/grub.cfg
#
# password_pbkdf2 [superusers-account] [password-hash]
#
# If the root password entry does not begin with "password_pbkdf2", this is a finding.
#
# If the "superusers-account" is not set to "root", this is a finding.
# Fix Text: Configure the system to encrypt the boot password for root.
#
# Generate an encrypted grub2 password for root with the following command:
#
# Note: The hash generated is an example.
#
# # grub2-mkpasswd-pbkdf2
#
# Enter Password:
# Reenter Password:
# PBKDF2 hash of your password is grub.pbkdf2.sha512.10000.F3A7CFAA5A51EED123BE8238C23B25B2A6909AFC9812F0D45
#
# Edit "/etc/grub.d/40_custom" and add the following lines below the comments:
#
# # vi /etc/grub.d/40_custom
#
# set superusers="root"
#
# password_pbkdf2 root {hash from grub2-mkpasswd-pbkdf2 command}
#
# Generate a new "grub.conf" file with the new password with the following commands:
#
# # grub2-mkconfig --output=/tmp/grub2.cfg
# # mv /tmp/grub2.cfg /boot/grub2/grub.cfg
#
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000213
# The information system enforces approved authorizations for logical access to information and system resources in accordance with applicable access control policies.
# NIST SP 800-53 :: AC-3
# NIST SP 800-53A :: AC-3.1
# NIST SP 800-53 Revision 4 :: AC-3
#
#
- name: check stig_rhel7_v1r4 v_71961
  set_fact: stig_rhel7_v1r4_results['v_71961'] = 'fail'
  when: '"v_71961" in stig_rhel7_v1r4_check_findings'


# Vuln ID: V-71963
# Severity: high
# Group Title: SRG-OS-000080-GPOS-00048
# Rule ID: SV-86587r3_rule
# STIG ID: RHEL-07-010490
# Rule Title: Systems using Unified Extensible Firmware Interface (UEFI) must require authentication upon booting into single-user and maintenance modes.
# Discussion: If the system does not require valid root authentication before it boots into single-user or maintenance mode, anyone who invokes single-user or maintenance mode is granted privileged access to all files on the system. GRUB 2 is the default boot loader for RHEL 7 and is designed to require a password to boot into single-user mode or make modifications to the boot menu.
# IA Controls:
# Check Content: For systems that use BIOS, this is Not Applicable.
#
# Check to see if an encrypted root password is set. On systems that use UEFI, use the following command:
#
# # grep -i password /boot/efi/EFI/redhat/grub.cfg
#
# password_pbkdf2 [superusers-account] [password-hash]
#
# If the root password entry does not begin with "password_pbkdf2", this is a finding.
#
# If the "superusers-account" is not set to "root", this is a finding.
# Fix Text: Configure the system to encrypt the boot password for root.
#
# Generate an encrypted grub2 password for root with the following command:
#
# Note: The hash generated is an example.
#
# # grub2-mkpasswd-pbkdf2
#
# Enter Password:
# Reenter Password:
# PBKDF2 hash of your password is grub.pbkdf2.sha512.10000.F3A7CFAA5A51EED123BE8238C23B25B2A6909AFC9812F0D45
#
# Edit "/etc/grub.d/40_custom" and add the following lines below the comments:
#
# # vi /etc/grub.d/40_custom
#
# set superusers="root"
#
# password_pbkdf2 root {hash from grub2-mkpasswd-pbkdf2 command}
#
# Generate a new "grub.conf" file with the new password with the following commands:
#
# # grub2-mkconfig --output=/tmp/grub2.cfg
# # mv /tmp/grub2.cfg /boot/efi/EFI/redhat/grub.cfg
#
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000213
# The information system enforces approved authorizations for logical access to information and system resources in accordance with applicable access control policies.
# NIST SP 800-53 :: AC-3
# NIST SP 800-53A :: AC-3.1
# NIST SP 800-53 Revision 4 :: AC-3
#
#
- name: check stig_rhel7_v1r4 v_71963
  set_fact: stig_rhel7_v1r4_results['v_71963'] = 'fail'
  when: '"v_71963" in stig_rhel7_v1r4_check_findings'


# Vuln ID: V-72067
# Severity: high
# Group Title: SRG-OS-000033-GPOS-00014
# Rule ID: SV-86691r3_rule
# STIG ID: RHEL-07-021350
# Rule Title: The operating system must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect data requiring data-at-rest protections in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards.
# Discussion: Use of weak or untested encryption algorithms undermines the purposes of using encryption to protect data. The operating system must implement cryptographic modules adhering to the higher standards approved by the federal government since this provides assurance they have been tested and validated.
#
# Satisfies: SRG-OS-000033-GPOS-00014, SRG-OS-000185-GPOS-00079, SRG-OS-000396-GPOS-00176, SRG-OS-000405-GPOS-00184, SRG-OS-000478-GPOS-00223
# IA Controls:
# Check Content: Verify the operating system implements DoD-approved encryption to protect the confidentiality of remote access sessions.
#
# Check to see if the "dracut-fips" package is installed with the following command:
#
# # yum list installed | grep dracut-fips
#
# dracut-fips-033-360.el7_2.x86_64.rpm
#
# If a "dracut-fips" package is installed, check to see if the kernel command line is configured to use FIPS mode with the following command:
#
# Note: GRUB 2 reads its configuration from the "/boot/grub2/grub.cfg" file on traditional BIOS-based machines and from the "/boot/efi/EFI/redhat/grub.cfg" file on UEFI machines.
#
# # grep fips /boot/grub2/grub.cfg
# /vmlinuz-3.8.0-0.40.el7.x86_64 root=/dev/mapper/rhel-root ro rd.md=0 rd.dm=0 rd.lvm.lv=rhel/swap crashkernel=auto rd.luks=0 vconsole.keymap=us rd.lvm.lv=rhel/root rhgb fips=1 quiet
#
# If the kernel command line is configured to use FIPS mode, check to see if the system is in FIPS mode with the following command:
#
# # cat /proc/sys/crypto/fips_enabled
# 1
#
# If a "dracut-fips" package is not installed, the kernel command line does not have a fips entry, or the system has a value of "0" for "fips_enabled" in "/proc/sys/crypto", this is a finding.
# Fix Text: Configure the operating system to implement DoD-approved encryption by installing the dracut-fips package.
#
# To enable strict FIPS compliance, the fips=1 kernel option needs to be added to the kernel command line during system installation so key generation is done with FIPS-approved algorithms and continuous monitoring tests in place.
#
# Configure the operating system to implement DoD-approved encryption by following the steps below:
#
# The fips=1 kernel option needs to be added to the kernel command line during system installation so that key generation is done with FIPS-approved algorithms and continuous monitoring tests in place. Users should also ensure that the system has plenty of entropy during the installation process by moving the mouse around, or if no mouse is available, ensuring that many keystrokes are typed. The recommended amount of keystrokes is 256 and more. Less than 256 keystrokes may generate a non-unique key.
#
# Install the dracut-fips package with the following command:
#
# # yum install dracut-fips
#
# Recreate the "initramfs" file with the following command:
#
# Note: This command will overwrite the existing "initramfs" file.
#
# # dracut -f
#
# Modify the kernel command line of the current kernel in the "grub.cfg" file by adding the following option to the GRUB_CMDLINE_LINUX key in the "/etc/default/grub" file and then rebuild the "grub.cfg" file:
#
# fips=1
#
# Changes to "/etc/default/grub" require rebuilding the "grub.cfg" file as follows:
#
# On BIOS-based machines, use the following command:
#
# # grub2-mkconfig -o /boot/grub2/grub.cfg
#
# On UEFI-based machines, use the following command:
#
# # grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
#
# If /boot or /boot/efi reside on separate partitions, the kernel parameter boot=<partition of /boot or /boot/efi> must be added to the kernel command line. You can identify a partition by running the df /boot or df /boot/efi command:
#
# # df /boot
# Filesystem 1K-blocks Used Available Use% Mounted on
# /dev/sda1 495844 53780 416464 12% /boot
#
# To ensure the boot= configuration option will work even if device naming changes between boots, identify the universally unique identifier (UUID) of the partition with the following command:
#
# # blkid /dev/sda1
# /dev/sda1: UUID="05c000f1-a213-759e-c7a2-f11b7424c797" TYPE="ext4"
#
# For the example above, append the following string to the kernel command line:
#
# boot=UUID=05c000f1-a213-759e-c7a2-f11b7424c797
#
# Reboot the system for the changes to take effect.
#
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000068
# The information system implements cryptographic mechanisms to protect the confidentiality of remote access sessions.
# NIST SP 800-53 :: AC-17 (2)
# NIST SP 800-53A :: AC-17 (2).1
# NIST SP 800-53 Revision 4 :: AC-17 (2)
#
# CCI-001199
# The information system protects the confidentiality and/or integrity of organization-defined information at rest.
# NIST SP 800-53 :: SC-28
# NIST SP 800-53A :: SC-28.1
# NIST SP 800-53 Revision 4 :: SC-28
#
# CCI-002450
# The information system implements organization-defined cryptographic uses and type of cryptography required for each use in accordance with applicable federal laws, Executive Orders, directives, policies, regulations, and standards.
# NIST SP 800-53 Revision 4 :: SC-13
#
# CCI-002476
# The information system implements cryptographic mechanisms to prevent unauthorized disclosure of organization-defined information at rest on organization-defined information system components.
# NIST SP 800-53 Revision 4 :: SC-28 (1)
#
#
- name: check stig_rhel7_v1r4 v_72067
  set_fact: stig_rhel7_v1r4_results['v_72067'] = 'fail'
  when: '"v_72067" in stig_rhel7_v1r4_check_findings'


# Vuln ID: V-72075
# Severity: medium
# Group Title: SRG-OS-000364-GPOS-00151
# Rule ID: SV-86699r1_rule
# STIG ID: RHEL-07-021700
# Rule Title: The system must not allow removable media to be used as the boot loader unless approved.
# Discussion: Malicious users with removable boot media can gain access to a system configured to use removable media as the boot loader. If removable media is designed to be used as the boot loader, the requirement must be documented with the Information System Security Officer (ISSO).
# IA Controls:
# Check Content: Verify the system is not configured to use a boot loader on removable media.
#
# Note: GRUB 2 reads its configuration from the "/boot/grub2/grub.cfg" file on traditional BIOS-based machines and from the "/boot/efi/EFI/redhat/grub.cfg" file on UEFI machines.
#
# Check for the existence of alternate boot loader configuration files with the following command:
#
# # find / -name grub.cfg
# /boot/grub2/grub.cfg
#
# If a "grub.cfg" is found in any subdirectories other than "/boot/grub2" and "/boot/efi/EFI/redhat", ask the System Administrator if there is documentation signed by the ISSO to approve the use of removable media as a boot loader.
#
# Check that the grub configuration file has the set root command in each menu entry with the following commands:
#
# # grep -c menuentry /boot/grub2/grub.cfg
# 1
# # grep ‘set root’ /boot/grub2/grub.cfg
# set root=(hd0,1)
#
# If the system is using an alternate boot loader on removable media, and documentation does not exist approving the alternate configuration, this is a finding.
# Fix Text: Remove alternate methods of booting the system from removable media or document the configuration to boot from removable media with the ISSO.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000318
# The organization audits and reviews activities associated with configuration controlled changes to the system.
# NIST SP 800-53 :: CM-3 e
# NIST SP 800-53A :: CM-3.1 (v)
# NIST SP 800-53 Revision 4 :: CM-3 f
#
# CCI-000368
# The organization documents any deviations from the established configuration settings for organization-defined information system components based on organization-defined operational requirements.
# NIST SP 800-53 :: CM-6 c
# NIST SP 800-53A :: CM-6.1 (v)
# NIST SP 800-53 Revision 4 :: CM-6 c
#
# CCI-001812
# The information system prohibits user installation of software without explicit privileged status.
# NIST SP 800-53 Revision 4 :: CM-11 (2)
#
# CCI-001813
# The information system enforces access restrictions.
# NIST SP 800-53 Revision 4 :: CM-5 (1)
#
# CCI-001814
# The Information system supports auditing of the enforcement actions.
# NIST SP 800-53 Revision 4 :: CM-5 (1)
#
#
- name: check stig_rhel7_v1r4 v_72075
  set_fact: stig_rhel7_v1r4_results['v_72075'] = 'fail'
  when: '"v_72075" in stig_rhel7_v1r4_check_findings'
