# Vuln ID: V-72057
# Severity: medium
# Group Title: SRG-OS-000480-GPOS-00227
# Rule ID: SV-86681r1_rule
# STIG ID: RHEL-07-021300
# Rule Title: Kernel core dumps must be disabled unless needed.
# Discussion: Kernel core dumps may contain the full contents of system memory at the time of the crash. Kernel core dumps may consume a considerable amount of disk space and may result in denial of service by exhausting the available space on the target file system partition.
# IA Controls:
# Check Content: Verify that kernel core dumps are disabled unless needed.
#
# Check the status of the "kdump" service with the following command:
#
# # systemctl status kdump.service
# kdump.service - Crash recovery kernel arming
#    Loaded: loaded (/usr/lib/systemd/system/kdump.service; enabled)
#    Active: active (exited) since Wed 2015-08-26 13:08:09 EDT; 43min ago
#  Main PID: 1130 (code=exited, status=0/SUCCESS)
# kernel arming.
#
# If the "kdump" service is active, ask the System Administrator if the use of the service is required and documented with the Information System Security Officer (ISSO).
#
# If the service is active and is not documented, this is a finding.
# Fix Text: If kernel core dumps are not required, disable the "kdump" service with the following command:
#
# # systemctl disable kdump.service
#
# If kernel core dumps are required, document the need with the ISSO.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel7_v1r4 v_72057
  set_fact: stig_rhel7_v1r4_results['v_72057'] = 'fail'
  when: '"v_72057" in check_findings'


# Vuln ID: V-77825
# Severity: medium
# Group Title: SRG-OS-000480-GPOS-00227
# Rule ID: SV-92521r1_rule
# STIG ID: RHEL-07-040201
# Rule Title: The operating system must implement virtual address space randomization.
# Discussion: Address space layout randomization (ASLR) makes it more difficult for an attacker to predict the location of attack code he or she has introduced into a process's address space during an attempt at exploitation. Additionally, ASLR also makes it more difficult for an attacker to know the location of existing code in order to repurpose it using return-oriented programming (ROP) techniques.
# IA Controls:
# Check Content: Verify the operating system implements virtual address space randomization.
#
# Check that the operating system implements virtual address space randomization with the following command:
#
# # grep kernel.randomize_va_space /etc/sysctl.conf
#
# kernel.randomize_va_space=2
#
# If "kernel.randomize_va_space" does not have a value of "2", this is a finding.
# Fix Text: Configure the operating system implement virtual address space randomization.
#
# Set the system to the required kernel parameter by adding the following line to "/etc/sysctl.conf" (or modify the line to have the required value):
#
# kernel.randomize_va_space=2
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel7_v1r4 v_77825
  set_fact: stig_rhel7_v1r4_results['v_77825'] = 'fail'
  when: '"v_77825" in check_findings'
