- name: stig section checks
  include_tasks: '{{ item }}.yml'
  with_items: '{{ stig_rhel7_v1r4_sections }}'
  notify: stig section fixes

- name: stig results
  set_fact: stig_rhel7_v1r4_results = "{{ stig_rhel7_v1r4_results }}{{ item }} : {{ 'stig_rhel7_v1r4_' ~ item ~ '_result' }}\n"
  with_items: '{{ stig_rhel7_v1r4_findings }}'

- name: stig result compilation
  debug: '{{ stig_rhel7_v1r4_results }}'
