# Vuln ID: V-71897
# Severity: medium
# Group Title: SRG-OS-000029-GPOS-00010
# Rule ID: SV-86521r1_rule
# STIG ID: RHEL-07-010090
# Rule Title: The operating system must have the screen package installed.
# Discussion: A session time-out lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system but does not log out because of the temporary nature of the absence. Rather than relying on the user to manually lock their operating system session prior to vacating the vicinity, operating systems need to be able to identify when a user's session has idled and take action to initiate the session lock.
#
# The screen package allows for a session lock to be implemented and configured.
# IA Controls:
# Check Content: Verify the operating system has the screen package installed.
#
# Check to see if the screen package is installed with the following command:
#
# # yum list installed | grep screen
# screen-4.3.1-3-x86_64.rpm
#
# If is not installed, this is a finding.
# Fix Text: Install the screen package to allow the initiation a session lock after a 15-minute period of inactivity for graphical users interfaces.
#
# Install the screen program (if it is not on the system) with the following command:
#
# # yum install screen
#
# The console can now be locked with the following key combination:
#
# ctrl+A x
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000057
# The information system initiates a session lock after the organization-defined time period of inactivity.
# NIST SP 800-53 :: AC-11 a
# NIST SP 800-53A :: AC-11.1 (ii)
# NIST SP 800-53 Revision 4 :: AC-11 a
#
#
- name: check stig_rhel7_v1r4 v_71897
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_71897: 'fail'})}}
  when: '"v_71897" in stig_rhel7_v1r4_checks'


# Vuln ID: V-71967
# Severity: high
# Group Title: SRG-OS-000095-GPOS-00049
# Rule ID: SV-86591r1_rule
# STIG ID: RHEL-07-020000
# Rule Title: The rsh-server package must not be installed.
# Discussion: It is detrimental for operating systems to provide, or install by default, functionality exceeding requirements or mission objectives. These unnecessary capabilities or services are often overlooked and therefore may remain unsecured. They increase the risk to the platform by providing additional attack vectors.
#
# Operating systems are capable of providing a wide variety of functions and services. Some of the functions and services, provided by default, may not be necessary to support essential organizational operations (e.g., key missions, functions).
#
# The rsh-server service provides an unencrypted remote access service that does not provide for the confidentiality and integrity of user passwords or the remote session and has very weak authentication.
#
# If a privileged user were to log on using this service, the privileged user password could be compromised.
# IA Controls:
# Check Content: Check to see if the rsh-server package is installed with the following command:
#
# # yum list installed rsh-server
#
# If the rsh-server package is installed, this is a finding.
# Fix Text: Configure the operating system to disable non-essential capabilities by removing the rsh-server package from the system with the following command:
#
# # yum remove rsh-server
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000381
# The organization configures the information system to provide only essential capabilities.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (ii)
# NIST SP 800-53 Revision 4 :: CM-7 a
#
#
- name: check stig_rhel7_v1r4 v_71967
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_71967: 'fail'})}}
  when: '"v_71967" in stig_rhel7_v1r4_checks'


# Vuln ID: V-71969
# Severity: high
# Group Title: SRG-OS-000095-GPOS-00049
# Rule ID: SV-86593r1_rule
# STIG ID: RHEL-07-020010
# Rule Title: The ypserv package must not be installed.
# Discussion: Removing the "ypserv" package decreases the risk of the accidental (or intentional) activation of NIS or NIS+ services.
# IA Controls:
# Check Content: The NIS service provides an unencrypted authentication service that does not provide for the confidentiality and integrity of user passwords or the remote session.
#
# Check to see if the "ypserve" package is installed with the following command:
#
# # yum list installed ypserv
#
# If the "ypserv" package is installed, this is a finding.
# Fix Text: Configure the operating system to disable non-essential capabilities by removing the "ypserv" package from the system with the following command:
#
# # yum remove ypserv
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000381
# The organization configures the information system to provide only essential capabilities.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (ii)
# NIST SP 800-53 Revision 4 :: CM-7 a
#
#
- name: check stig_rhel7_v1r4 v_71969
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_71969: 'fail'})}}
  when: '"v_71969" in stig_rhel7_v1r4_checks'


# Vuln ID: V-72077
# Severity: high
# Group Title: SRG-OS-000095-GPOS-00049
# Rule ID: SV-86701r1_rule
# STIG ID: RHEL-07-021710
# Rule Title: The telnet-server package must not be installed.
# Discussion: It is detrimental for operating systems to provide, or install by default, functionality exceeding requirements or mission objectives. These unnecessary capabilities or services are often overlooked and therefore may remain unsecured. They increase the risk to the platform by providing additional attack vectors.
#
# Operating systems are capable of providing a wide variety of functions and services. Some of the functions and services, provided by default, may not be necessary to support essential organizational operations (e.g., key missions, functions).
#
# Examples of non-essential capabilities include, but are not limited to, games, software packages, tools, and demonstration software not related to requirements or providing a wide array of functionality not required for every mission, but which cannot be disabled.
# IA Controls:
# Check Content: Verify the operating system is configured to disable non-essential capabilities. The most secure way of ensuring a non-essential capability is disabled is to not have the capability installed.
#
# The telnet service provides an unencrypted remote access service that does not provide for the confidentiality and integrity of user passwords or the remote session.
#
# If a privileged user were to log on using this service, the privileged user password could be compromised.
#
# Check to see if the telnet-server package is installed with the following command:
#
# # yum list installed | grep telnet-server
#
# If the telnet-server package is installed, this is a finding.
# Fix Text: Configure the operating system to disable non-essential capabilities by removing the telnet-server package from the system with the following command:
#
# # yum remove telnet-server
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000381
# The organization configures the information system to provide only essential capabilities.
# NIST SP 800-53 :: CM-7
# NIST SP 800-53A :: CM-7.1 (ii)
# NIST SP 800-53 Revision 4 :: CM-7 a
#
#
- name: check stig_rhel7_v1r4 v_72077
  set_fact:
    stig_rhel7_v1r4_results: '{{stig_rhel7_v1r4_results|combine({v_72077: 'fail'})}}
  when: '"v_72077" in stig_rhel7_v1r4_checks'
