# Vuln ID: V-72297
# Severity: medium
# Group Title: SRG-OS-000480-GPOS-00227
# Rule ID: SV-86921r2_rule
# STIG ID: RHEL-07-040680
# Rule Title: The system must be configured to prevent unrestricted mail relaying.
# Discussion: If unrestricted mail relaying is permitted, unauthorized senders could use this host as a mail relay for the purpose of sending spam or other unauthorized activity.
# IA Controls:
# Check Content: Verify the system is configured to prevent unrestricted mail relaying.
#
# Determine if "postfix" is installed with the following commands:
#
# # yum list installed postfix
# postfix-2.6.6-6.el7.x86_64.rpm
#
# If postfix is not installed, this is Not Applicable.
#
# If postfix is installed, determine if it is configured to reject connections from unknown or untrusted networks with the following command:
#
# # postconf -n smtpd_client_restrictions
# smtpd_client_restrictions = permit_mynetworks, reject
#
# If the "smtpd_client_restrictions" parameter contains any entries other than "permit_mynetworks" and "reject", this is a finding.
# Fix Text: If "postfix" is installed, modify the "/etc/postfix/main.cf" file to restrict client connections to the local network with the following command:
#
# # postconf -e 'smtpd_client_restrictions = permit_mynetworks,reject'
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: check stig_rhel7_v1r4 v_72297
  set_fact: stig_rhel7_v1r4_v_72297_result = 'fail'
  when: '"v_72297" in check_findings'
