# Vuln ID: V-71971
# Severity: medium
# Group Title: SRG-OS-000324-GPOS-00125
# Rule ID: SV-86595r1_rule
# STIG ID: RHEL-07-020020
# Rule Title: The operating system must prevent non-privileged users from executing privileged functions to include disabling, circumventing, or altering implemented security safeguards/countermeasures.
# Discussion: Preventing non-privileged users from executing privileged functions mitigates the risk that unauthorized individuals or processes may gain unnecessary access to information or privileges.
#
# Privileged functions include, for example, establishing accounts, performing system integrity checks, or administering cryptographic key management activities. Non-privileged users are individuals who do not possess appropriate authorizations. Circumventing intrusion detection and prevention mechanisms or malicious code protection mechanisms are examples of privileged functions that require protection from non-privileged users.
# IA Controls:
# Check Content: Verify the operating system prevents non-privileged users from executing privileged functions to include disabling, circumventing, or altering implemented security safeguards/countermeasures.
#
# Get a list of authorized users (other than System Administrator and guest accounts) for the system.
#
# Check the list against the system by using the following command:
#
# # semanage login -l | more
# Login Name  SELinux User   MLS/MCS Range  Service
# __default__  user_u    s0-s0:c0.c1023   *
# root   unconfined_u   s0-s0:c0.c1023   *
# system_u  system_u   s0-s0:c0.c1023   *
# joe  staff_u   s0-s0:c0.c1023   *
#
# All administrators must be mapped to the "sysadm_u" or "staff_u" users with the appropriate domains (sysadm_t and staff_t).
#
# All authorized non-administrative users must be mapped to the "user_u" role or the appropriate domain (user_t).
#
# If they are not mapped in this way, this is a finding.
# Fix Text: Configure the operating system to prevent non-privileged users from executing privileged functions to include disabling, circumventing, or altering implemented security safeguards/countermeasures.
#
# Use the following command to map a new user to the "sysdam_u" role:
#
# #semanage login -a -s sysadm_u <username>
#
# Use the following command to map an existing user to the "sysdam_u" role:
#
# #semanage login -m -s sysadm_u <username>
#
# Use the following command to map a new user to the "staff_u" role:
#
# #semanage login -a -s staff_u <username>
#
# Use the following command to map an existing user to the "staff_u" role:
#
# #semanage login -m -s staff_u <username>
#
# Use the following command to map a new user to the "user_u" role:
#
# # semanage login -a -s user_u <username>
#
# Use the following command to map an existing user to the "user_u" role:
#
# # semanage login -m -s user_u <username>
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-002165
# The information system enforces organization-defined discretionary access control policies over defined subjects and objects.
# NIST SP 800-53 Revision 4 :: AC-3 (4)
#
# CCI-002235
# The information system prevents non-privileged users from executing privileged functions to include disabling, circumventing, or altering implemented security safeguards/countermeasures.
# NIST SP 800-53 Revision 4 :: AC-6 (10)
#
#
- name: check stig_rhel7_v1r4 v_71971
  set_fact: stig_rhel7_v1r4_results['v_71971'] = 'fail'
  when: '"v_71971" in stig_rhel7_v1r4_checks'


# Vuln ID: V-71989
# Severity: high
# Group Title: SRG-OS-000445-GPOS-00199
# Rule ID: SV-86613r2_rule
# STIG ID: RHEL-07-020210
# Rule Title: The operating system must enable SELinux.
# Discussion: Without verification of the security functions, security functions may not operate correctly and the failure may go unnoticed. Security function is defined as the hardware, software, and/or firmware of the information system responsible for enforcing the system security policy and supporting the isolation of code and data on which the protection is based. Security functionality includes, but is not limited to, establishing system accounts, configuring access authorizations (i.e., permissions, privileges), setting events to be audited, and setting intrusion detection parameters.
#
# This requirement applies to operating systems performing security function verification/testing and/or systems and environments that require this functionality.
# IA Controls:
# Check Content: Verify the operating system verifies correct operation of all security functions.
#
# Check if "SELinux" is active and in "Enforcing" mode with the following command:
#
# # getenforce
# Enforcing
#
# If "SELinux" is not active and not in "Enforcing" mode, this is a finding.
# Fix Text: Configure the operating system to verify correct operation of all security functions.
#
# Set the "SELinux" status and the "Enforcing" mode by modifying the "/etc/selinux/config" file to have the following line:
#
# SELINUX=enforcing
#
# A reboot is required for the changes to take effect.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-002165
# The information system enforces organization-defined discretionary access control policies over defined subjects and objects.
# NIST SP 800-53 Revision 4 :: AC-3 (4)
#
# CCI-002696
# The information system verifies correct operation of organization-defined security functions.
# NIST SP 800-53 Revision 4 :: SI-6 a
#
#
- name: check stig_rhel7_v1r4 v_71989
  set_fact: stig_rhel7_v1r4_results['v_71989'] = 'fail'
  when: '"v_71989" in stig_rhel7_v1r4_checks'


# Vuln ID: V-71991
# Severity: high
# Group Title: SRG-OS-000445-GPOS-00199
# Rule ID: SV-86615r3_rule
# STIG ID: RHEL-07-020220
# Rule Title: The operating system must enable the SELinux targeted policy.
# Discussion: Without verification of the security functions, security functions may not operate correctly and the failure may go unnoticed. Security function is defined as the hardware, software, and/or firmware of the information system responsible for enforcing the system security policy and supporting the isolation of code and data on which the protection is based. Security functionality includes, but is not limited to, establishing system accounts, configuring access authorizations (i.e., permissions, privileges), setting events to be audited, and setting intrusion detection parameters.
#
# This requirement applies to operating systems performing security function verification/testing and/or systems and environments that require this functionality.
# IA Controls:
# Check Content: Verify the operating system verifies correct operation of all security functions.
#
# Check if "SELinux" is active and is enforcing the targeted policy with the following command:
#
# # sestatus
#
# SELinux status:                 enabled
#
# SELinuxfs mount:                /selinux
#
# SELinux root directory:         /etc/selinux
#
# Loaded policy name:             targeted
#
# Current mode:                   enforcing
#
# Mode from config file:          enforcing
#
# Policy MLS status:              enabled
#
# Policy deny_unknown status:     allowed
#
# Max kernel policy version:      28
#
#
# If the "Policy from config file" is not set to "targeted", or the "Loaded policy name" is not set to "targeted", this is a finding.
#
# Fix Text: Configure the operating system to verify correct operation of all security functions.
#
# Set the "SELinuxtype" to the "targeted" policy by modifying the "/etc/selinux/config" file to have the following line:
#
# SELINUXTYPE=targeted
#
# A reboot is required for the changes to take effect.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-002165
# The information system enforces organization-defined discretionary access control policies over defined subjects and objects.
# NIST SP 800-53 Revision 4 :: AC-3 (4)
#
# CCI-002696
# The information system verifies correct operation of organization-defined security functions.
# NIST SP 800-53 Revision 4 :: SI-6 a
#
#
- name: check stig_rhel7_v1r4 v_71991
  set_fact: stig_rhel7_v1r4_results['v_71991'] = 'fail'
  when: '"v_71991" in stig_rhel7_v1r4_checks'
