- name: check if vsftpd is installed
  command: rpm -qi vsftpd
  args:
      warn: False
  ignore_errors: True
  register: vsftpd_installed

# - debug:
#     msg: "{{vsftpd_installed}}"

- name: include fixes if command succeeded (package is installed)
  include_tasks: harden_vsftpd.yml
  when: vsftpd_installed is succeeded
