- name: remove journal files
  shell: rm -f /var/named/*.jnl
  args:
      warn: False

- name: check named config
  command: named-checkconf -z -j
  changed_when: False

- name: restart named
  service:
      name: named
      state: restarted
