- name: parse /etc/passwd
  passwd_dump:
  register: passwd

# - debug:
#     msg: "{{passwd}}"

- name: collect login_defs
  login_defs_dump:
  register: login_defs

# - debug:
#     msg: "{{login_defs}}"

- set_fact:
    uid_min: "{{login_defs.login_defs.UID_MIN|int}}"

- set_fact:
    interactive_accounts: "{{passwd.passwd|selectattr('uid', 'ge', uid_min|int)|selectattr('uid', 'lt', 65500)|map(attribute='login')|list}}"

- set_fact:
    service_accounts: "{{passwd.passwd|selectattr('uid', 'gt', 0)|selectattr('uid', 'lt', uid_min|int)|map(attribute='login')|list}}"
