# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72077 (SV-86701r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38587 (SV-50388r1_rule)
- name: remove package
  yum:
      name: telnet-server
      state: absent

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38589 (SV-50390r2_rule)
- name: disable, stop service
  service:
      name: telnet
      enabled: no
      state: stopped
