- name: check if gdm is installed
  command: rpm -qi gdm
  args:
      warn: False
  ignore_errors: True
  changed_when: False
  failed_when: False
  register: gdm_installed

- name: include harden
  include_tasks: harden.yml
  when:
      - gdm_installed.rc == 0
