- name: gdm is installed
  shell: yum list installed gdm 2&>1 >/dev/null || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: gdm_installed

- name: AutomaticLoginEnable = false in /etc/gdm/custom.conf [daemon]
  ini_file:
      path: /etc/gdm/custom.conf
      section: daemon
      mode: 0644
      option: AutomaticLoginEnable
      value: false
      state: present

- name: TimedLoginEnable = false in /etc/gdm/custom.conf [daemon]
  ini_file:
      path: /etc/gdm/custom.conf
      section: daemon
      mode: 0644
      option: TimedLoginEnable
      value: false
      state: present
