- name: gdm is installed
  shell: yum list installed gdm || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: gdm_installed

# - debug:
#     msg: "{{gdm_installed}}"
#
- set_fact:
    gdm_installed: "{{gdm_installed.failed == false and gdm_installed.stderr != ''}}"

# - debug:
#     msg: "{{gdm_installed}}"
#
- name: AutomaticLoginEnable = false in /etc/gdm/custom.conf [daemon]
  ini_file:
      path: /etc/gdm/custom.conf
      section: daemon
      mode: 0644
      option: AutomaticLoginEnable
      value: false
      state: present
  when:
      - not gdm_installed

- name: TimedLoginEnable = false in /etc/gdm/custom.conf [daemon]
  ini_file:
      path: /etc/gdm/custom.conf
      section: daemon
      mode: 0644
      option: TimedLoginEnable
      value: false
      state: present
  when:
      - not gdm_installed
