- name: gdm is installed
  shell: yum list installed gdm || true
  # following is so we don't get an error about using command instead of module
  args:
      warn: false
  # errors are expected; ignore
  ignore_errors: yes
  # this command doesn't actually change anything
  changed_when: false
  register: gdm_installed

- name: include harden
  include_tasks: harden.yml
  when: gdm_installed is succeeded
