# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71977 (SV-86601r1_rule)
- name: set gpgcheck in yum.conf
  ini_file:
      path: /etc/yum.conf
      section: main
      option: gpgcheck
      value: 1
      state: present

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71979 (SV-86603r1_rule)
- name: set localpkg_gpgcheck in yum.conf
  ini_file:
      path: /etc/yum.conf
      section: main
      option: localpkg_gpgcheck
      value: 1
      state: present

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71981 (SV-86605r1_rule)
- name: set repo_gpgcheck in yum.conf
  ini_file:
      path: /etc/yum.conf
      section: main
      option: repo_gpgcheck
      value: 1
      state: present
