# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71977 (SV-86601r1_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38483 (SV-50283r1_rule)
- name: set gpgcheck in yum.conf
  ini_file:
      path: /etc/yum.conf
      section: main
      option: gpgcheck
      value: 1
      no_extra_spaces: yes
      state: present

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38487 (SV-50288r1_rule)
- name: check for gpgcheck=0 in /etc/yum.repos.d/*.repo
  shell: grep --no-messages --files-with-matches '^gpgcheck\s*=\s*0' /etc/yum.repos.d/*.repo
  ignore_errors: True
  register: gpgcheck_repos

- name: replace gpgcheck=0 with gpgcheck=1 in /etc/yum.repo.d/*.repo
  replace:
      path: "{{item}}"
      regexp: ^gpgcheck\s*=\s*0
      replace: gpgcheck=1
  loop: "{{gpgcheck_repos.stdout_lines|default([])|list}}"

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71979 (SV-86603r1_rule)
- name: set localpkg_gpgcheck in yum.conf
  ini_file:
      path: /etc/yum.conf
      section: main
      option: localpkg_gpgcheck
      value: 1
      no_extra_spaces: yes
      state: present

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-71981 (SV-86605r1_rule)
- name: set repo_gpgcheck in yum.conf
  ini_file:
      path: /etc/yum.conf
      section: main
      option: repo_gpgcheck
      value: 1
      no_extra_spaces: yes
      state: present

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38487 (SV-50288r1_rule)
- name: import rpm gpg keys
  rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
      state: present
