# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72049 (SV-86673r1_rule)
- name: check home directories for umask files
  shell: grep --no-messages --files-with-matches '^umask\s' {{item.home}}/.*
  when: item.uid >= 1000
  loop: "{{passwd.passwd}}"
  register: home_umasks
  failed_when: False

- debug:
    msg: "{{home_umasks}}"

- name: set umask in interactive user dotfiles
  include_tasks: set_umask_in_files.yml
  when: not home_umask_result is skipped
  loop: "{{home_umasks.results}}"
  loop_control:
      loop_var: home_umask_result

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38642 (SV-50443r1_rule)
- name: set umask in /etc/init.d/functions
  lineinfile:
      path: /etc/init.d/functions
      regexp: ^umask\s+
      line: umask 022
      state: present

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38649 (SV-50450r1_rule)
- name: set umask in /etc/csh.cshrc
  lineinfile:
      path: /etc/csh.cshrc
      regexp: ^umask\s+
      line: umask 077
      state: present

# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38651 (SV-50452r1_rule)
- name: set umask in /etc/bashrc
  lineinfile:
      path: /etc/bashrc
      regexp: ^umask\s+
      line: umask 077
      state: present
