# Vuln ID: V-38642
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50443r1_rule
# STIG ID: RHEL-06-000346
# Rule Title: The system default umask for daemons must be 027 or 022.
# Discussion: The umask influences the permissions assigned to files created by a process at run time. An unnecessarily permissive umask could result in files being created with insecure permissions.
# IA Controls:
# Check Content: To check the value of the "umask", run the following command:
#
# $ grep umask /etc/init.d/functions
#
# The output should show either "022" or "027".
# If it does not, this is a finding.
# Fix Text: The file "/etc/init.d/functions" includes initialization parameters for most or all daemons started at boot time. The default umask of 022 prevents creation of group- or world-writable files. To set the default umask for daemons, edit the following line, inserting 022 or 027 for [UMASK] appropriately:
#
# umask [UMASK]
#
# Setting the umask to too restrictive a setting can cause serious errors at runtime. Many daemons on the system already individually restrict themselves to a umask of 077 in their own init scripts.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
# - name: fail stig_rhel6_v1r18 v_38642
#   set_fact:
#     stig_rhel6_v1r18_v_38642_result: 'fail'
#   when:
#     - "'v_38642' in stig_rhel6_v1r18_checks"
#     - stig_rhel6_v1r18_v_38642_result != 'pass'


# Vuln ID: V-38645
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50446r1_rule
# STIG ID: RHEL-06-000345
# Rule Title: The system default umask in /etc/login.defs must be 077.
# Discussion: The umask value influences the permissions assigned to files when they are created. A misconfigured umask value could result in files with excessive permissions that can be read and/or written to by unauthorized users.
# IA Controls:
# Check Content: Verify the "umask" setting is configured correctly in the "/etc/login.defs" file by running the following command:
#
# # grep -i "umask" /etc/login.defs
#
# All output must show the value of "umask" set to 077, as shown in the below:
#
# # grep -i "umask" /etc/login.defs
# UMASK 077
#
#
# If the above command returns no output, or if the umask is configured incorrectly, this is a finding.
# Fix Text: To ensure the default umask controlled by "/etc/login.defs" is set properly, add or correct the "umask" setting in "/etc/login.defs" to read as follows:
#
# UMASK 077
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
# - name: fail stig_rhel6_v1r18 v_38645
#   set_fact:
#     stig_rhel6_v1r18_v_38645_result: 'fail'
#   when:
#     - "'v_38645' in stig_rhel6_v1r18_checks"
#     - stig_rhel6_v1r18_v_38645_result != 'pass'


# Vuln ID: V-38647
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50448r1_rule
# STIG ID: RHEL-06-000344
# Rule Title: The system default umask in /etc/profile must be 077.
# Discussion: The umask value influences the permissions assigned to files when they are created. A misconfigured umask value could result in files with excessive permissions that can be read and/or written to by unauthorized users.
# IA Controls:
# Check Content: Verify the "umask" setting is configured correctly in the "/etc/profile" file by running the following command:
#
# # grep "umask" /etc/profile
#
# All output must show the value of "umask" set to 077, as shown in the below:
#
# # grep "umask" /etc/profile
# umask 077
#
#
# If the above command returns no output, or if the umask is configured incorrectly, this is a finding.
# Fix Text: To ensure the default umask controlled by "/etc/profile" is set properly, add or correct the "umask" setting in "/etc/profile" to read as follows:
#
# umask 077
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
# - name: fail stig_rhel6_v1r18 v_38647
#   set_fact:
#     stig_rhel6_v1r18_v_38647_result: 'fail'
#   when:
#     - "'v_38647' in stig_rhel6_v1r18_checks"
#     - stig_rhel6_v1r18_v_38647_result != 'pass'


# Vuln ID: V-38649
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50450r1_rule
# STIG ID: RHEL-06-000343
# Rule Title: The system default umask for the csh shell must be 077.
# Discussion: The umask value influences the permissions assigned to files when they are created. A misconfigured umask value could result in files with excessive permissions that can be read and/or written to by unauthorized users.
# IA Controls:
# Check Content: Verify the "umask" setting is configured correctly in the "/etc/csh.cshrc" file by running the following command:
#
# # grep "umask" /etc/csh.cshrc
#
# All output must show the value of "umask" set to 077, as shown in the below:
#
# # grep "umask" /etc/csh.cshrc
# umask 077
#
#
# If the above command returns no output, or if the umask is configured incorrectly, this is a finding.
# Fix Text: To ensure the default umask for users of the C shell is set properly, add or correct the "umask" setting in "/etc/csh.cshrc" to read as follows:
#
# umask 077
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
# - name: fail stig_rhel6_v1r18 v_38649
#   set_fact:
#     stig_rhel6_v1r18_v_38649_result: 'fail'
#   when:
#     - "'v_38649' in stig_rhel6_v1r18_checks"
#     - stig_rhel6_v1r18_v_38649_result != 'pass'


# Vuln ID: V-38651
# Severity: low
# Group Title: SRG-OS-999999
# Rule ID: SV-50452r1_rule
# STIG ID: RHEL-06-000342
# Rule Title: The system default umask for the bash shell must be 077.
# Discussion: The umask value influences the permissions assigned to files when they are created. A misconfigured umask value could result in files with excessive permissions that can be read and/or written to by unauthorized users.
# IA Controls:
# Check Content: Verify the "umask" setting is configured correctly in the "/etc/bashrc" file by running the following command:
#
# # grep "umask" /etc/bashrc
#
# All output must show the value of "umask" set to 077, as shown below:
#
# # grep "umask" /etc/bashrc
# umask 077
# umask 077
#
#
# If the above command returns no output, or if the umask is configured incorrectly, this is a finding.
# Fix Text: To ensure the default umask for users of the Bash shell is set properly, add or correct the "umask" setting in "/etc/bashrc" to read as follows:
#
# umask 077
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
# - name: fail stig_rhel6_v1r18 v_38651
#   set_fact:
#     stig_rhel6_v1r18_v_38651_result: 'fail'
#   when:
#     - "'v_38651' in stig_rhel6_v1r18_checks"
#     - stig_rhel6_v1r18_v_38651_result != 'pass'
