# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38618 (SV-50419r2_rule)
- name: stop, disable service
  service:
      name: avahi-daemon
      enabled: no
      state: stopped

- name: remove package
  yum:
      name: avahi
      state: absent
