- name: collect interactive user home dir stat
  stat:
      path: "{{item.home}}"
  loop: "{{users_dump.users}}"
  when:
      - not item.is_sys
  register: interactive_home_stat

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72017 (SV-86641r2_rule)
- name: "check stat mode is <= {{home_dirs_perm|oct}}"
  file:
      path: "{{item.item.home}}"
      mode: "{{home_dirs_perm}}"
  loop: "{{interactive_home_stat.results}}"
  when:
      - not item is skipped
      - item.stat.mode is perm_gt(home_dirs_perm)

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72019 (SV-86643r4_rule)
- name: "check stat owner is user"
  file:
      path: "{{item.item.home}}"
      owner: "{{item.item.name}}"
      state: directory
  loop: "{{interactive_home_stat.results}}"
  when:
      - not item is skipped
      - item.stat.pw_name != item.item.name

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72021 (SV-86645r4_rule)
- name: "check stat group is user's primary group"
  file:
      path: "{{item.item.home}}"
      group: "{{item.item.gid}}"
      state: directory
  loop: "{{interactive_home_stat.results}}"
  when:
      - not item is skipped
      - item.stat.gid != item.item.gid

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72023 (SV-86647r1_rule)
- name: recurse directory for owner
  file:
      path: "{{item.home}}"
      owner: "{{item.name}}"
      state: directory
      recurse: yes
  loop: "{{users_dump.users}}"
  when:
      - not item.is_sys

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72025 (SV-86649r1_rule)
# TODO: this requires recursing through every file in the users home dir and
# checking if the group owner is one of the user's groups
