- name: install ansible dependencies
  yum:
      name: "{{item}}"
      state: installed
  loop: "{{ansible_dependencies}}"

- group_by:
    key: "os_{{ansible_distribution}}_{{ ansible_distribution_major_version }}"

- include_tasks: "{{item}}"
  loop:
      - wheel_user.yml

- name: trust distro key
  rpm_key:
      key: "{{distribution_key_file}}"
      state: present

- include_role:
    name: "{{item}}"
  loop:
      - repo_client
      - ntp_client
