- name: install ansible dependencies
  yum:
      name: "{{item}}"
      state: installed
  loop: "{{ansible_dependencies}}"

- group_by:
    key: "os_{{ansible_distribution}}_{{ ansible_distribution_major_version }}"

- name: repo fstab
  mount:
      src: "{{repo_server}}:{{repo_share}}"
      path: "{{repo_share}}"
      fstype: nfs
      opts: ro,insecure,all_squash
      state: mounted
  when: not is_repo_server

- name: repo link
  file:
      path: "/etc/yum.repos.d/{{repo_server}}.repo"
      src: "{{repo_share}}/{{repo_server}}.repo"
      state: link
  when: not is_repo_server

- name: remove subscription-manager, rhn* pkags
  yum:
      name: "{{item}}"
      state: absent
  loop:
      - subscription-manager
      - rhn*
  when: not is_repo_server
