- name: install ansible dependencies
  yum:
      name: "{{item}}"
      state: installed
  loop: "{{ansible_dependencies}}"

- group_by:
    key: "os_{{ansible_distribution}}_{{ ansible_distribution_major_version }}"

- include_tasks: "{{item}}"
  loop:
      - repo_client.yml
      - wheel_user.yml
