- name: wheel user
  user:
      name: "{{wheel_user}}"
      password: "{{wheel_user_password}}"
      groups:
          - wheel
      append: yes
      create_home: yes
      state: present

- name: wheel user authorized ssh keys
  lineinfile:
      path: "/home/{{wheel_user}}/.ssh/authorized_keys"
      line: "{{item}}"
      owner: "{{wheel_user}}"
      group: "{{wheel_user}}"
      mode: 0600
      state: present
  loop: "{{wheel_user_keys}}"
