- name: install packages
  yum:
      name: "{{item}}"
      state: installed
  loop:
      - dhcp

- name: template dhcpd.conf
  template:
      src: templates/etc/dhcp/dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      owner: root
      group: root
      mode: 0640
  notify:
      - check dhcpd config
      - restart dhcpd

- name: service enabled, started
  service:
      name: dhcpd
      enabled: yes
      state: started

- name: firewall exception, permanent
  firewall_cmd_zone:
      permanent: yes
      service: dhcp
      state: present

- name: firewall exception
  firewall_cmd_zone:
      permanent: no
      service: dhcp
      state: present
