# NOTE: we assume users_dump is parsed into register users_dump

- set_fact:
    uid: "{{ users_dump.users|selectattr('uid', 'gt', 300)|map(attribute='uid')|min - 1 }}"

# NOTE: can't use usermod for uid 0
- name: renumber uid==0 accounts other than root; use wheel as primary group
  replace:
    path: /etc/passwd
    regexp: "^({{user_name}}:[^:]*):0:[^:]+:(.*)$"
    replace: '\1:{{uid}}:10:\2'

- name: change ownership of home directory
  file:
    path: "{{users_dump.users|selectattr('login', 'eq', user_name)|map(attribute='home')}}"
    owner: "{{uid}}"
    group: 10
    recurse: yes

- name: reparse
  users_dump:
  register: users_dump
