# Vuln ID: V-38460
# Severity: low
# Group Title: SRG-OS-000104
# Rule ID: SV-50260r1_rule
# STIG ID: RHEL-06-000515
# Rule Title: The NFS server must not have the all_squash option enabled.
# Discussion: The "all_squash" option maps all client requests to a single anonymous uid/gid on the NFS server, negating the ability to track file access by user ID.
# IA Controls:
# Check Content: If the NFS server is read-only, in support of unrestricted access to organizational content, this is not applicable.
#
# The related "root_squash" option provides protection against remote administrator-level access to NFS server content.  Its use is not a finding.
#
# To verify the "all_squash" option has been disabled, run the following command:
#
# # grep all_squash /etc/exports
#
#
# If there is output, this is a finding.
# Fix Text: Remove any instances of the "all_squash" option from the file "/etc/exports".  Restart the NFS daemon for the changes to take effect.
#
# # service nfs restart
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000764
# The information system uniquely identifies and authenticates organizational users (or processes acting on behalf of organizational users).
# NIST SP 800-53 :: IA-2
# NIST SP 800-53A :: IA-2.1
# NIST SP 800-53 Revision 4 :: IA-2
#
#
- name: fix stig_rhel6_v1r18 v_38460



# Vuln ID: V-38652
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-50453r2_rule
# STIG ID: RHEL-06-000269
# Rule Title: Remote file systems must be mounted with the nodev option.
# Discussion: Legitimate device files should only exist in the /dev directory. NFS mounts should not present device files to users.
# IA Controls:
# Check Content: To verify the "nodev" option is configured for all NFS mounts, run the following command:
#
# $ mount | grep "nfs "
#
# All NFS mounts should show the "nodev" setting in parentheses, along with other mount options.
# If the setting does not show, this is a finding.
# Fix Text: Add the "nodev" option to the fourth column of "/etc/fstab" for the line which controls mounting of any NFS mounts.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: fix stig_rhel6_v1r18 v_38652



# Vuln ID: V-38654
# Severity: medium
# Group Title: SRG-OS-999999
# Rule ID: SV-50455r2_rule
# STIG ID: RHEL-06-000270
# Rule Title: Remote file systems must be mounted with the nosuid option.
# Discussion: NFS mounts should not present suid binaries to users. Only vendor-supplied suid executables should be installed to their default location on the local filesystem.
# IA Controls:
# Check Content: To verify the "nosuid" option is configured for all NFS mounts, run the following command:
#
# $ mount | grep nfs
#
# All NFS mounts should show the "nosuid" setting in parentheses, along with other mount options.
# If the setting does not show, this is a finding.
# Fix Text: Add the "nosuid" option to the fourth column of "/etc/fstab" for the line which controls mounting of any NFS mounts.
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000366
# The organization implements the security configuration settings.
# NIST SP 800-53 :: CM-6 b
# NIST SP 800-53A :: CM-6.1 (iv)
# NIST SP 800-53 Revision 4 :: CM-6 b
#
#
- name: fix stig_rhel6_v1r18 v_38654



# Vuln ID: V-38677
# Severity: high
# Group Title: SRG-OS-000104
# Rule ID: SV-50478r1_rule
# STIG ID: RHEL-06-000309
# Rule Title: The NFS server must not have the insecure file locking option enabled.
# Discussion: Allowing insecure file locking could allow for sensitive data to be viewed or edited by an unauthorized user.
# IA Controls:
# Check Content: To verify insecure file locking has been disabled, run the following command:
#
# # grep insecure_locks /etc/exports
#
#
# If there is output, this is a finding.
# Fix Text: By default the NFS server requires secure file-lock requests, which require credentials from the client in order to lock a file. Most NFS clients send credentials with file lock requests, however, there are a few clients that do not send credentials when requesting a file-lock, allowing the client to only be able to lock world-readable files. To get around this, the "insecure_locks" option can be used so these clients can access the desired export. This poses a security risk by potentially allowing the client access to data for which it does not have authorization. Remove any instances of the "insecure_locks" option from the file "/etc/exports".
# False Positives:
# False Negatives:
# Documentable: false
# Mitigations:
# Potential Impact:
# Third Party Tools:
# Mitigation Control:
# Responsibility:
# Severity Override Guidance:
# Check Content Reference: M
# Classification: Unclass
# STIG: Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# VMS Asset Posture:
#  CCI: CCI-000764
# The information system uniquely identifies and authenticates organizational users (or processes acting on behalf of organizational users).
# NIST SP 800-53 :: IA-2
# NIST SP 800-53A :: IA-2.1
# NIST SP 800-53 Revision 4 :: IA-2
#
#
- name: fix stig_rhel6_v1r18 v_38677

