- name: include non-specific roles
  include_role:
    name: "{{harden_role}}"
  loop:
    - harden_abrt
    - harden_aide
    - harden_antivirus
    - harden_at
    - harden_auditd
    - harden_autofs
    - harden_avahi
    - harden_cron
    - harden_filesystems
    - harden_firewalld
    - harden_gdm
    - harden_gnome
    - harden_group
    - harden_grub
    - harden_gshadow
    - harden_init
    - harden_iptables
    - harden_issue
    - harden_kdump
    - harden_libuser
    - harden_limits
    - harden_login
    - harden_logrotate
    - harden_modules
    - harden_nfs_server
    - harden_nslcd
    - harden_ntpd
    - harden_oddjob
    - harden_openldap
    - harden_pam
    - harden_passwd
    - harden_postfix
    - harden_profile
    - harden_pwquality
    - harden_resolv_conf
    - harden_rexec
    - harden_rhn
    - harden_rlogind
    - harden_rsh
    - harden_rsyslogd
    - harden_samba_client
    - harden_screen
    - harden_securetty
    - harden_selinux
    - harden_sendmail
    - harden_shadow
    - harden_snmpd
    - harden_sshd
    - harden_sssd
    - harden_sudo
    - harden_sysctl
    - harden_systemd
    - harden_tcpwrappers
    - harden_telnet
    - harden_tftpd
    - harden_umask
    - harden_usbguard
    - harden_useradd
    - harden_vsftpd
    - harden_xinetd
    - harden_ypbind
    - harden_ypserv
    - harden_yum
  loop_control:
    loop_var: harden_role
