# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72079 (SV-86703r2_rule)
- name: install packages
  yum:
      state: installed
      name: '{{item}}'
  with_items:
      - audit
      - audispd-plugins

# NOTE: service running,enabled is at the bottom so rules can be defined before
# startup

- include_tasks: auditd.yml

- include_tasks: audisp_rhel7.yml
  when: ansible_distribution_major_version == '7'

- include_tasks: audisp_rhel6.yml
  when: ansible_distribution_major_version == '6'

- name: df | grep -i '^/' | awk '{print $6}'
  shell: df | grep -i '^/' | awk '{print $6}'
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: audit_local_filesystems

- name: find {{item}} -xdev -type f \( -perm -4000 -o -perm -2000 \) 2>/dev/null
  shell: find {{item}} -xdev -type f \( -perm -4000 -o -perm -2000 \) 2>/dev/null
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: audit_setuid_setgid_fs
  with_items: '{{audit_local_filesystems.stdout_lines}}'

- set_fact:
    audit_setuid_setgid_files: []

- name: combine audit_setuid_setgid_fs results
  set_fact:
      audit_setuid_setgid_files: '{{audit_setuid_setgid_files}} + {{item.stdout_lines}}'
  with_items: '{{audit_setuid_setgid_fs.results}}'


- include_tasks: rules_rhel7.yml
  when: ansible_distribution_major_version == '7'

- include_tasks: rules_rhel6.yml
  when: ansible_distribution_major_version == '6'

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72079 (SV-86703r2_rule)
# Red Hat Enterprise Linux 6 Security Technical Implementation Guide :: Release: 18 Benchmark Date: 26 Jan 2018
# V-38628 (SV-50429r2_rule)
# V-38631 (SV-50432r2_rule)
# V-38632 (SV-50433r2_rule)
- name: service running
  service:
      name: auditd
      enabled: yes
      state: started
