# The rules files have each rule(set) tagged within them
- name: copy rule files
  copy:
      src: "files/etc/audit/rules.d/{{item}}"
      dest: "/etc/audit/rules.d/{{item}}"
      owner: root
      group: root
      mode: 0600
  loop:
      - 00_header.rules
      - access.rules
      - delete.rules
      - identity.rules
      - logins.rules
      - module-change.rules
      - perm_mod.rules
      - privileged-actions.rules
      - privileged-cron.rules
      - privileged-mount.rules
      - privileged-pam.rules
      - privileged-passwd.rules
      - privileged-postfix.rules
      - privileged-priv_change.rules
      - privileged-ssh.rules
      - zz_enabled.rules
  notify: generate audit rules

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72095 (SV-86719r5_rule)
- name: df | grep -i '^/' | awk '{print $6}'
  shell: df | grep -i '^/' | awk '{print $6}'
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: audit_local_filesystems

- name: find {{item}} -xdev -type f \( -perm -4000 -o -perm -2000 \) 2>/dev/null
  shell: find {{item}} -xdev -type f \( -perm -4000 -o -perm -2000 \) 2>/dev/null
  ignore_errors: yes
  changed_when: False
  failed_when: False
  register: audit_setuid_setgid
  with_items: '{{audit_local_filesystems.stdout_lines}}'

- set_fact:
    audit_setuid_setgid_combined: []

- name: combine audit_setuid_setgid results
  set_fact:
      audit_setuid_setgid_combined: '{{audit_setuid_setgid_combined}} + {{item.stdout_lines}}'
  with_items: '{{audit_setuid_setgid.results}}'

- name: setuid_setgid audit rules
  template:
      src: etc/audit/rules.d/setuid_setgid.rules.j2
      dest: /etc/audit/rules.d/setuid_setgid.rules
      mode: 0600
  notify: generate audit rules
