# The rules files have each rule(set) tagged within them
- name: copy rule files
  copy:
      src: "files/etc/audit/rules.d/{{item}}"
      dest: "/etc/audit/rules.d/{{item}}"
      owner: root
      group: root
      mode: 0600
  loop:
      - 00_header.rules
      - access.rules
      - delete.rules
      - identity.rules
      - logins.rules
      - module-change.rules
      - perm_mod.rules
      - privileged-actions.rules
      - privileged-cron.rules
      - privileged-mount.rules
      - privileged-pam.rules
      - privileged-passwd.rules
      - privileged-postfix.rules
      - privileged-priv_change.rules
      - privileged-ssh.rules
      - zz_enabled.rules
  notify: generate audit rules

# Red Hat Enterprise Linux 7 Security Technical Implementation Guide :: Release: 4 Benchmark Date: 26 Jan 2018
# V-72095 (SV-86719r5_rule)
- name: setuid,setgid audit rules
  lineinfile:
      path: /etc/audit/rules.d/setuid_setgid.rules
      line: "-a always,exit -F path={{item}} -F perm=x -F auid>=1000 -F auid!=4294967295 -k setuid_setgid"
      state: present
  loop: "{{audit_setuid_setgid_files}}"
  notify: generate audit rules
